### ISSUE TITLE
Are there any requirements for this to work ?

### ISSUE THREAD

**Issue by stve-a** [ChromaControl/ChromaControl#10]
Hi, 

Could you please inform or document if there are any requirements like aura connect had, where you had to have aura armory crate or asus aura installed ?

Or is this one fully stand alone and not dependent on anything else ?

Regards
S

**Comment by AndrewBabbitt97** [comment]
Uninstall any old version and try the beta: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
