### ISSUE TITLE
Corsair RAM rgb stuck. 

### ISSUE THREAD

**Issue by hugopua** [ChromaControl/ChromaControl#101]
Hi. 

The rgb of Corsair ram will stuck when power on and boot to windows. ( with Light effect on icue is turn on). 

But if I turn all rgb light off and no issue when boot into windows. 

Do I need turn all light off in icue to make chroma connect to work?

Thank you.

**Comment by hugopua** [comment]
the problem happened again when I first power & boot up to windows. It’s working if restart pc.

**Comment by AndrewBabbitt97** [comment]
Need list of devices you are using, what versions of Corsair software you have installed, as well as which ChromaControl modules you are using.

**Comment by hugopua** [comment]
AMD Ryzen 5950x
ASUS crosshair VIII dark hero
Corsair Dominator Platinum 3600Mhz 8GB x 4
ASUS ROG Strix RTX 3090
Razer Addressable RGB controller 
Lian Li Dynamic O11 XL

*Razer Synapse 3*
Link to Razer Controller:
1. GPU monoblock
2. Motherboard monoblock
3. Distro plate
4. FLT 360
5. NZXT underglow (use converter to ARGB 3pin)

*Armoury Crate*
Link to Asus motherboard argb header:
1. Top & bottom led strips 
2. Lian Li dynamic o11 xl front LED
*L-connect enabled motherboard sync*
3. Unifan x 7 via uni hub
*Corsair icue*
4. Corsair Dominator Platinum RGB

Software installed version:
Corsair icue 4.12.214
Armoury crate 3.1.0.0
Chroma connect - Corsair 1.0.0.0
Chroma connect - Asus 1.0.0.0

chroma control for ASUS is working perfectly. 
Problem :
The lighting of RAM light up by hardware lighting and turn to software lighting after boot to windows. When I first turn on and boot to windows the lighting of ram stuck on software lighting (it happened sometime)

If I restarted the pc and everything work perfectly.

**Comment by hugopua** [comment]
[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6684951/Corsair.log)

**Comment by AndrewBabbitt97** [comment]
Don't use the Corsair module if you only use Corsair RAM. Uninstall the Corsair module and only use the ASUS module.

Enable ram control from Armory Crate: https://help.corsair.com/hc/en-us/articles/360035656371-Enable-Aura-Sync-control-for-your-Corsair-RGB-memory

You will probably also need to delete the ASUS folder, located inside the plugins folder in the iCUE install directory. (While iCUE is closed) so that iCUE doesn't clash with Chroma Control for device control.

**Comment by hugopua** [comment]
Hi. 

I follow your method and it’s working but the ram got issue sometime. I think same problem as this one. 

https://github.com/ChromaControl/ChromaControl/issues/16

Can I kill the icue and relaunch to fix the issue?

**Comment by AndrewBabbitt97** [comment]
FYI: Not currently supporting iCUE 4.x as well, messed around with it on a friend's build as well and didn't have success with it.

Recommended iCUE 3.x with the AURA plugin installed from the Corsair website and the ASUS folder deleted from the iCUE install directory (adds support for ASUS motherboards to iCUE)

If testing:

1. Stop iCUE
2. Stop Corsair Chroma Control module
3. Start iCUE
4. Start Corsair Chroma Control module

**Comment by hugopua** [comment]
Hi. 

Are you mentioned the 4 steps to kill & relaunch icue & chroma connect is to testing the rgb stuck issue?

Do I need to follow below step to enable sync between icue & Armoury Crate?
To enable Armoury Crate on iCUE version 3:

1. Install or update iCUE.
2. Install the ASUS plugin.
3. Install Armoury Crate.
4. Open iCUE.
5. Click SETTINGS.
6. Select your system memory.
7. Open Armoury Crate.
8. Click the Aura Sync section.
9. Click the Link/Unlink button beneath the DRAM icon; the icon will change to white when linked.
10. When asked if you want to save changes, click Yes.

What to do after Step 4 to Step 6? Just leave it?

thank you

**Comment by hugopua** [comment]
@AndrewBabbitt97 I tried your suggestion. It’s working perfectly. But something weird thing is the ram rgb stuck on every morning I turn off the pc (I turned off the pc on night time). I have to kill and relaunch icue & chroma connect to make it working again.

**Comment by AndrewBabbitt97** [comment]
Can I get a picture of your iCUE UI for reference.

May be fixed by #105 becoming available in 1.1.0

**Comment by hugopua** [comment]
![icue](https://user-images.githubusercontent.com/81452768/123038105-609fe400-d422-11eb-815e-340b90d4548c.jpg)

**Comment by AndrewBabbitt97** [comment]
Based on your logs in #103 this is the same issue. Its just any time the PC pauses/wakes you have this issue.

#105 may help, but this technically shouldn't matter. Could be an issue just in iCUE (its buggy sometimes) and the way it connects to AURA. Not much I can do besides implement #105 in 1.1.0. I might try some reliability improvements in 1.0.1 but we will see.

**Comment by AndrewBabbitt97** [comment]
Tracking in #105
