### ISSUE TITLE
slowness of chroma effects

### ISSUE THREAD

**Issue by Raicko** [ChromaControl/ChromaControl#104]
currently im using Asus and MSI mystic(Mobo and gpu). however the effects are very slow compared to Razer keyboard and mouse

**Comment by AndrewBabbitt97** [comment]
Delay is from the AURA SDK calls, unfortunately nothing I can do on this side. This is inherent lag on the ASUS side of stuff.

**Comment by Raicko** [comment]
appreciate your support and great app
