### ISSUE TITLE
Chroma Control Not Working With Xpg G20

### ISSUE THREAD

**Issue by TaylanErol** [ChromaControl/ChromaControl#106]
Chroma control isn't working with Xpg G20 ssd. I have other asus devices connected to armory create program they sync with razer chroma thanks to chroma control but my ssd is not. Xpg G20 is connected to asus armory too but it does not change while others do when I change some settings in razer chroma software. @AndrewBabbitt97

**Comment by AndrewBabbitt97** [comment]
See #53 and #56
