### ISSUE TITLE
chroma connect doesnt install

### ISSUE THREAD

**Issue by XeanXeus** [ChromaControl/ChromaControl#107]
Hello, I have recently installed a new m.2 drive in my pc and when I try to install chroma connect it opens the command prompt window and it appears to crash because synapse doesnt get the aura plugin. I had it installed on my pc before with aura connect but I havent had any luck getting it to show up in synapse since installing the new drive

**Comment by AndrewBabbitt97** [comment]
What version of windows 10? Are you running the latest version of app installer? https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1?activetab=pivot:overviewtab

**Comment by XeanXeus** [comment]
windows 10 pro 21h2, do I need to have c++ installed?

**Comment by AndrewBabbitt97** [comment]
21h2? Isn't that Windows 11?

Can I get a build number?

I also have slight confusion, did the MSIX not install or did the program fail to start when you opened it? You don't make that clear in your original issues text.

**Comment by Whiplash4731** [comment]
I am having an issue installing as well. I receive the following error message each time I try to install it. 

**This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)**  

I have the following OS installed:

**Edition	Windows 10 Home
Version	20H2
Installed on	‎2020-‎12-‎13
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0**

 I verified that I have the newest version of the app installer program from windows. 

Thanks for your help!

**Comment by AndrewBabbitt97** [comment]
@Whiplash4731 current release that's set up on the website is for testing the release pipeline. I don't actually expect you to be able to install it. This error is expected.

My current certificate from Sectigo doesn't have the correct attributes to sign right now so I'm waiting for a replacement. I'll see about adding a warning banner to the website letting people know it's not currently released.

**Comment by AndrewBabbitt97** [comment]
Issue was fixed in recent release.
