### ISSUE TITLE
incompatibility with razer synapse on windows 11

### ISSUE THREAD

**Issue by SkuldNorniern** [ChromaControl/ChromaControl#108]
I was using the ChromaControl on windows 10 
and a few days ago I have installed the insider build after the razer synapse is not showing the chroma control all the time 
I know that this program is not optimized on windows 11 yet and windows 11 is currently buggy.
because I haven't seen the other issue related to windows 11 I'm here to inform the error from windows 11

**Comment by AndrewBabbitt97** [comment]
I will be running all Windows 11 insider builds to verify compatibility. I have it installed on my dev machine I have not however installed Chroma Control due to time right now, I will be doing some more testing starting tomorrow and or this weekend.

Once I have taken a closer look expect a new build in the following week.

**Comment by AndrewBabbitt97** [comment]
Windows 11 works as expected with the current MSIX beta as well as latest version of Synapse and Armory Crate.

If you are having issues, the upgrade to Windows 11 might have messed up your Synapse/Armory crate drivers or state. Would recommend reinstalling the apps and try again.

**Comment by KyleStilkey** [comment]
For me, Windows 11 pulled this from my Startup devices. I just ran the program and turned it back on in my startup options. Other than that little fluke it's working across 4 machines I have here on Windows 11.

**Comment by SkuldNorniern** [comment]
I Think the inconsistent was because of ASUS's side problem,  I have checked the logs again and reinstalled the Armory Crate.
and the issue is only happening when the Armory Crate is splitting the errors
