### ISSUE TITLE
How can i uninstall chroma control?

### ISSUE THREAD

**Issue by NICULLTD** [ChromaControl/ChromaControl#109]
It's great, it works well haven't had any issues with it. I have an ASUS TUF B450 PLUS motherboard. I just want to remove it so i can use the armoury crate audio sync effect since its better than what razer does to my fans. I tried using revo uninstaller pro and other software can't find it anywhere.

**Comment by NICULLTD** [comment]
Nvm im just utterly retarded. It's in settings > Apps. (I'm quite new to windows 10, having only ever used 7 my entire life.) One thing i hope would get fixed is the slider in the devices section, it doesn't actually turn it off i have to add a black color in chroma studio to do so.

**Comment by AndrewBabbitt97** [comment]
MSIX is a Windows 10/ Windows 11 app packaging format and so it doesn't show up in the old control panel. You can find it in the apps section of the Settings app or by clicking uninstall from the right click context menu of the start menu.

An alternative if you only want to temporarily disable it is to just kill it from the task manager. Eventually I will be implementing a Windows 11 widget as well as a UI to do this easily.
