### ISSUE TITLE
Not Appearing in Razer Synapse

### ISSUE THREAD

**Issue by Szat74** [ChromaControl/ChromaControl#11]
After installing the file, none of my corsair and ASUS aura products appeared in Razer Synapse... Is there some step I'm missing? Help would be greatly appreciated.

**Comment by AndrewBabbitt97** [comment]
Uninstall the old version and try the beta: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
