### ISSUE TITLE
Steps for activating Chroma Control (Corsair)

### ISSUE THREAD

**Issue by Maleficen** [ChromaControl/ChromaControl#119]
In order for Chroma Control to appear in the Synapse app, you need to activate the option "Enable Software Integration" on the Corsair iCUE software, otherwise it won't show and it will seem like is not installed:

![image](https://user-images.githubusercontent.com/42087862/125583581-17662f8d-ce87-4357-b9b9-1a861aa91c14.png)

Is important to mention this somewhere in the main page or documentation, because this option comes disabled by default and is not visible for people, so many will think that Chroma Control is not working or even installed.

**Comment by AndrewBabbitt97** [comment]
Not testing against the new iCUE version yet, SDK hasn't been updated to the latest revision yet as well. This is coming in the next week or so.

**Comment by AndrewBabbitt97** [comment]
Grouping with #40
