### ISSUE TITLE
not working with advanced animations

### ISSUE THREAD

**Issue by fudoido** [ChromaControl/ChromaControl#12]
as title says, i downloaded and tested the software today.
asus b450 plus mobo, 2x Crucial Ballistix Tactical Tracer rgb (addressable), 2 regular non-addressable rgb strips connected to mobo, amd wraith non-addressable rgb cooler, synapse 3 with a cynosa v2 keyboard connected.

using the "normal" effects from synapse (solid colour, breathing, spectrum cycle, audio meter), rgb strips, ram and cooler make the effect as the keyboard but not syncing colour, except with audiometer which synced the pattern and colour, even after applying to any other chroma enabled devices (by using the button next to the drop down menu) only audiometer syncs colour.
any other animations leave the strips, cooler and ram with the last working alteration made, and the advanced effects render the aura "device" leaving all leds off.

as an elite:dangerous player, i use a app for synapse that gives game related animations and key marking with the lights and colours. (faded unneeded keys, red for attack keys, blue for defence keys, etc) --  https://github.com/poveden/EliteChroma
with this app enabled while playing the game, ram shows some animations, strips and cooler go dark and flash in what seems to be randomly, but i think it might have a actual sequence to it. makes me believe that your app is reading from one exclusive key or set of keys and tries to show what that/those key/s are showing.
also, by using this app, there is a small variation in colour depending of my location ingame (from a light blue when in space, to a light faint green when i am docked in a station). surprised how it works, even if limited, in this situation with an extra app, and doesnt work with the built razer software options.
despite the amount of rgb items in my case connected to aura, your app only shows 1 connection in synapse, but i see 4 dots in it. would be great if each dot represents a aura device (as my example, strips which are connected on the same hub, therefore same mobo connector, 2 dims ram, cooler, 4 devices) and we could somehow change values for each device individually, opening a bigger option also to the creator of the other app for elite:dangerous.
would this be achieved in future? in a fairly long future.......
regards.

**Comment by fudoido** [comment]
spectrum cycling seems to be syncing colours also, just updating the experience.

**Comment by AndrewBabbitt97** [comment]
Chroma Control doesn't mirror what a key on your keyboard is doing. If you look in Chroma Studio within Synapse you can see a "device" for Aura/iCUE. It will have some colors under it being updated like any other device in Synapse. Chroma Control just relays those colors Synapse sends over to Aura or iCUE.

Any issues that you see with something like EliteChroma are out of my control.

A video would still be useful going over all of the issues you are encountering, again however we just set the colors of the devices to what Synapse tells us to.

**Comment by fudoido** [comment]
its not exactly an issue, just letting you know that your app works toghether with elitechroma, although limited.
i will try to do a video soon and post the link here so you can see what features are enabled to me, and what is working wrong.
still a great tool, and hope it can get even better in the future.

**Comment by complexminded** [comment]
I think what is being said is that other applications allow for individual control of the 12v RGB headers on the MB individually.  The iCue Asus integration, for example, allows me to control my two individual headers on my MB so I can set different colors for each channel.  With this module, you can only set one color for all channels.  For me, all channels include my 12v rgb headers, my MB lighting, and my GPU.  With iCue's built-in integration, I was able to control those channels individually to assign different colors.

**Comment by AndrewBabbitt97** [comment]
Yes, this is a limitation of what the Chroma Connect API allows developers to do. I have asked for an expansion on this from the Razer Chroma developers, and for the time being there is no plan to change that but that may not always be the case.

I will however keep up with any future changes Razer makes to improve device integrations in Synapse and am in frequent contact with the devs regarding many things.

**Comment by fudoido** [comment]
as far i have read, asus is not very keen to let other brands "connect" to their stuff and allow more customization, while other brands such as msi are willing to cooperate their "mystic light" concept with razer to make it compatible. despite the limitations, i am happy to see this software integrate somehow both brands, and also some integration with another 3rd party software.
Another one i might try someday is "aurora", a software made to provide more animations and key colour code for certain games (euro truck simulator is the one i been using, aurora makes the strobes and blinkers of the trucks animate the keyboard syncronized with truck lights).
just today i tested with "blasck desert" game and it also provides some animations with the native game profile within synapse, no extra software needed since the game is using razer sdk natively.
i will try to make a video and showcase it someday soon.

**Comment by AndrewBabbitt97** [comment]
I'm gonna close this issue however, seeing as this issue isn't an actual issue but a limitation of the Razer Chroma Broadcast API, there's nothing I can do to make it any better unless they improve the API in the future. (And I will of course update the modules to use any new capabilities on the API).

**Comment by fudoido** [comment]
just letting 2 videos so you can check how it operates. its nice to see tehre is some game interactions with it, hence why i started the topic.
1st video is how its identyfied in synapse, as you might well know already. i had to activate that animation alone for the device as it doesnt pickup the animations, since they were not built for the device detected by your app.
[https://1drv.ms/v/s!AkXBtY_Q3jJGrhmSj_t3hXRbfowW?e=hHL7Dj](url)
2nd video is how it works with the elitechroma app running the game i mentioned. i didnt had to add any animations to the asus "device", elitechroma is ment to work with any synapse compatible device, and your app creates that device with aura.
[https://1drv.ms/v/s!AkXBtY_Q3jJGrhhN-sJb93b919eE?e=Y5GBJg](url)

might have to download the videos, the fastest way i had to upload them directly from my phone was to my onedrive.

**Comment by AndrewBabbitt97** [comment]
Yup, these are expected results. Chroma Broadcast API limitations don't give a lot of flexibility for lighting in certain situations.

You may be able to help it by moving the location of the AURA item inside chroma studio somewhere else, this can help with more advanced lighting effects but beyond that there's really nothing else.

You can also make the experience better by moving devices such as RGB strips off of your motherboard to Razers ARGB controller: https://www.razer.com/gaming-pc-accessories/razer-chroma-addressable-rgb-controller/RZ34-02140600-R3U1
