### ISSUE TITLE
Chroma Control not working (Corsair)

### ISSUE THREAD

**Issue by Maleficen** [ChromaControl/ChromaControl#120]
Chroma Control is not working properly with the Corsair iCUE software, even when is shown in the Synapse app after enabling the software integrations in iCUE.

I tried to disable and enable the Chroma Control from Synapse many times, restarted both Synapse and iCUE and even restarted the computer to see if it could work:

![image](https://user-images.githubusercontent.com/42087862/125587556-ac048a26-d719-4086-8ce8-fcd7cad21eec.png)

Just to add that I already have another 3rd party device (Seagate FireCuda) correctly working through the Chroma Connect; the iCUE software is detecting correctly that Chroma Control is being used to control the lights, but fails to show any light at all.

I'm adding also the log:

[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6814576/Corsair.log)

Let me know if you would need something else.

**Comment by AndrewBabbitt97** [comment]
I need to see the studio view of Synapse to verify the issue.

Not currently testing against the new version of iCUE. It could be that.

I won't be testing it until later this week as a part of the upcoming 0.1.0 build scheduled to be released on the 25th.

**Comment by Maleficen** [comment]
I'm leaving here the requested image:

![image](https://user-images.githubusercontent.com/42087862/125590572-cb1aaf17-91ce-432c-b534-0b70e1d31d66.png)

From the image, it seems is able to reach the device, but still no colors are displayed.

Maybe you are right and the new version has some issues, nevertheless let me know if you need some help from my side to test something specific, otherwise I will be waiting for you when you have some free time.

**Comment by AndrewBabbitt97** [comment]
Yeah this is looking to be on the Corsair side. Looks like the Corsair SDK had a new protocol version.

I can do the testing fine, I just don't use the Corsair module personally so I have to wait for others to report that it's broken.

I should have this fixed by 0.1.0

**Comment by Maleficen** [comment]
I just installed iCUE 3.38.61 and everything is working fine and out of the box, I didn´t even need to change a single thing in the iCUE settings or in Synapse; it detected everything automatically.

So yes, it seems that iCUE V4 has some different protocols or SDK.

**Comment by AndrewBabbitt97** [comment]
It's not that I don't use it, it's just that I don't have any Corsair hardware attached to the PC unless I'm testing this module. All my hardware I use daily is Razer, Asus, and EK Water Blocks.

I have a Corsair mouse but I only pull it out when stuff like this happens to make sure it's working.

Module will be out in the public 0.1.0 build after I update the SDK. I always verify that the code works before publishing :)

**Comment by AndrewBabbitt97** [comment]
Fixed with the latest CUESDK.NET release here: https://github.com/ChromaControl/CUESDK.NET/releases/tag/3.0.378.1

This will be a part of the upcoming 0.1.0 release next sunday.
