### ISSUE TITLE
App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80190194. (0x80190194)

### ISSUE THREAD

**Issue by jubairsaidi** [ChromaControl/ChromaControl#124]
Not able to install Chroma Control, I'm getting the following error:

```App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80190194. (0x80190194)```

Screenshot:
![image](https://user-images.githubusercontent.com/1675902/127506275-ab5e8bb9-14ff-450c-9745-be8b2b3a40c4.png)

**Comment by patcsong** [comment]
I made it work after the developer advise to install releases/download/0.1.0/ChromaControl_0.1.0.0_x86_x64.msixbundle

**Comment by jubairsaidi** [comment]
that worked, thanks!
