### ISSUE TITLE
synapse does not recognize chroma control

### ISSUE THREAD

**Issue by john-marcos** [ChromaControl/ChromaControl#126]
synapse does not recognize chroma control, it does not show up in chroma connect.

![cromaconnect](https://user-images.githubusercontent.com/88216326/127722127-0804f473-2059-42d7-ada8-67cba48d1414.jpg)

**Comment by AndrewBabbitt97** [comment]
Turn on debug mode then reflip the Asus switch

**Comment by john-marcos** [comment]
THAT?
![cromaconnect2](https://user-images.githubusercontent.com/88216326/127722375-8a7723b2-ef49-4bd2-bf1f-3271d613a7f5.jpg)

**Comment by john-marcos** [comment]
![cromaconnect3](https://user-images.githubusercontent.com/88216326/127722479-f2274956-67fa-474c-948e-71564bbfbf9f.jpg)

**Comment by AndrewBabbitt97** [comment]
This error is coming from the Aura SDK. I'd try reinstalling Armory Crate (without Aura Creator), update your bios, then ensure all updates inside Armory Crate are installed.

**Comment by john-marcos** [comment]
done however gave the same error.
![cromaconnect4](https://user-images.githubusercontent.com/88216326/127723679-f2eb8c77-84ad-4e0d-b852-ffd410e30351.jpg)

**Comment by AndrewBabbitt97** [comment]
![127723679-f2eb8c77-84ad-4e0d-b852-ffd410e30351](https://user-images.githubusercontent.com/2308261/127724661-06f53c43-899e-488c-8b33-65dc3487d37f.jpg)
You have to have this on

**Comment by john-marcos** [comment]
I enabled and restarted the computer but when i open the synapse or error 5 appears in the control's debug
![cromaconnect5](https://user-images.githubusercontent.com/88216326/127724833-be79639f-3ff6-42cc-8763-695db7a3e28c.jpg)

**Comment by AndrewBabbitt97** [comment]
Error is entirely related to your AURA install. That's about all I got. Even though the error shows in the Chroma Control window, the error is coming from AURA. It's something that's specific to your hardware & Aura.

There's not much else I can say to do beyond just messing with your install and stuff.

**Comment by luanfsp** [comment]
![image](https://user-images.githubusercontent.com/31630621/127725905-dd28ba1c-4e1b-4c0a-b440-331d5bb445a2.png)

This error even with AURA performance mode on and Armory Crate (without Aura Creator).

**Comment by luanfsp** [comment]
Now recognizes but same error.

![image](https://user-images.githubusercontent.com/31630621/127726001-84239a49-e57e-443e-947b-3a25eddfbf6d.png)

**Comment by AndrewBabbitt97** [comment]
Error is coming from AuraServiceLib, an ASUS component. Again the issue is with your install/setup.
