### ISSUE TITLE
Chroma Control shows up in Chroma Synapse Studio view; does not control lights.

### ISSUE THREAD

**Issue by dlamblin** [ChromaControl/ChromaControl#130]
## Issue
After installing Chroma Control and setting Asus On, Corsair Off and Debug On (or Off) The device appears in Chroma Synapse Studio view.
Right clicking it and choosing to `test lights` does not change any behavior. The lights only respond to Armoury Crate Aura Sync settings. If I have Aura Sync set to dark and they remain dark. If I set it to static white they remain static white. Despite Razer Synapse Studio having ALL devices set to a breathing green.

The board is an Asus TUF Gaming X570-PLUS (Wi-fi) MBoard; I am using the argb headers and control of those an the built in light strip on the edge of the board is being controlled by Armoury Crate. In-Game lighting effects is on/enabled. Aura Performace mode is off. I've tried rebooting, updating both Razer Synapse and Asus Armoury Crate, restarting a few times. So far Armoury Crate is primarily in control of the lights.

## Versions:
(just updated today)
- Windows 10 21H1 Build 19043.1110
- Armoury Crate 4.1.6.0 (2021-?-?)
- Asus Hal 20210309 (2021-04-08)
- Tuf Gaming X570-Plus (Wi-FI)
  - Device Kit 2.1.1.1 (2021-07-28)
  - Aura Kit 20200317 (2020-03-27)
  - HAL 1.1.7.0 (2021-04-26)
  - HTML 1.05.19 (2021-07-22)
  - Device SDK 2.01.22 (2021-07-13)
- Addressable LED Strip
  - Device Kit 2.1.1.1 (2021-07-28)
  - Aura Kit 20210205 (2021-03-03)
- Razer Synapse 3.6.731.72613
- Chroma Control 0.1.1.0 [Background Apps: On, Runs at log-in Chroma Control-Asus: On ; App 552MB Data 125KB]

There's no detailed install instructions, nor a pointer to where the logs might be saved.

I'm not sure I can provide the asus.log debug file. Its not in: `C:\Program Files (x86)\Razer Chroma SDK\logs ` and the location of Chroma Control is unclear. Oh I found `%localappdata%\Packages\ChromaControl_q2sx6sw85pbp2\LocalState\logs\ChromaControl.Asus.log`

```text
2021-08-03T00:34:20.7039467-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Initializing Chroma Control - Asus...
2021-08-03T00:34:20.7041902-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Initializing Device Provider...
2021-08-03T00:34:58.9126489-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Found Device: Mainboard_Master - 5 Lights
2021-08-03T00:34:58.9126768-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Found Device: AddressableStrip 1 - 120 Lights
2021-08-03T00:34:58.9126836-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Initializing Razer Chroma Broadcast SDK...
2021-08-03T00:34:58.9624411-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Chroma Control - Asus Started Succesfully!
2021-08-03T00:35:31.7875651-04:00	INFO	[ChromaControl.Hosting.ModuleService]	[0]	Razer Chroma Broadcast API Connected
```

**Comment by dlamblin** [comment]
Just updated from:
```
Item                       Version     
----                       -------     
Armoury Crate UWP App      4.1.6.0     
ROG Live Service           1.2.12.5    
AURA Service (Lighting)    3.05.06     
Armoury Crate lite servic  4.1.6       
ASUS AIOFan HAL            1.1.31      
ASUS AURA Motherboard HAL  1.1.7.0     
PHISON HAL                 1.0.6.0     
```
To this; Frankly I don't see why the (Aura Sync) Settings -> About didn't list all those items below before.
```
Item                       Version     
----                       -------     
Armoury Crate UWP App      4.1.6.0     
ROG Live Service           1.2.12.5    
AURA Service (Lighting)    3.05.06     
Armoury Crate lite servic  4.1.6       
ASUS AIOFan HAL            1.1.33      
ASUS AURA Extnsn Card HAL  1.1.0.10    
ASUS AURA Motherboard HAL  1.1.7.0     
AacVGA                     0.0.3.1     
KingstonDram               1.1.8       
AURA DRAM Component        1.1.11      
ENE RGB HAL                1.1.32.0    
ENE_EHD_M2_HAL             1.0.8.14    
PHISON HAL                 1.0.9.0     
Patriot Viper DRAM RGB     1.0.9.2     
Patriot Viper M2 SSD RGB   1.0.6.4     
Universal Holtek RGB DRAM  1.0.0.2     
WD_BLACK AN1500            1.0.13.0    
```

**Comment by dlamblin** [comment]
For context; I was able to run Chroma Control in a way that worked on this machine. It worked at boot time from a cold start after a power down. (showing green Razer controlled lighting)
After going to sleep, and then waking up however, it ceded control back to Armoury Crate's Aura Sync setting (showing blue lighting as previously configured in Aura Sync, contrary to what is configured in Razer's Chroma Synapse Studio.

**Comment by AndrewBabbitt97** [comment]
AURA SDK not responding after sleep is a known issue, you must restart the module by toggling it off then back on in the UI for the time being.

Debug mode only takes effect upon restarting the module, also done by turning the module off then back on. This functionality is being separated in an upcoming update.

**Comment by jogan81** [comment]
> AURA SDK not responding after sleep is a known issue, you must restart the module by toggling it off then back on in the UI for the time being.
> 
> Debug mode only takes effect upon restarting the module, also done by turning the module off then back on. This functionality is being separated in an upcoming update.

Hi Andrew, 

I couldn't get it to work either, I even did a clean install of windows.
I kept getting error 5.
So I installed AuraConnect that I still had and that works flawlessly.

Greetings,

John.

**Comment by AndrewBabbitt97** [comment]
> I couldn't get it to work either, I even did a clean install of windows.
> I kept getting error 5.

Would like more details, this is the first time I have seen an error 5.

> So I installed AuraConnect that I still had and that works flawlessly.

Just bear in mind AuraConnect is not supported at all and an archived project. I also highly recommend trying to get off of it, Chroma Control has a lot of perf improvements.

**Comment by AndrewBabbitt97** [comment]
Closing as this issue is stale, sleep issues in #37
