### ISSUE TITLE
closing the chroma control

### ISSUE THREAD

**Issue by alright-sudo** [ChromaControl/ChromaControl#131]
sorry maybe i am confused about something, is there a way to close the chroma control app and still have the profiles still sync up with synapse. the same way i can close synapse and have it still  my profiles

**Comment by AndrewBabbitt97** [comment]
The UI app doesn't need to stay open for the ASUS/Corsair modules to work. So long as they are enabled they will run in the background.

**Comment by alright-sudo** [comment]
when i click close on chroma control ASUS and Chroma contro, corsair.exe it stops the control of those two applications even though on chroma control both of functions are still on

**Comment by AndrewBabbitt97** [comment]
The switches enable the modules and have them start on login. Separate stop/restart buttons are being added later. For now the switches enable it at startup and stop/start the processes.

ChromaControl.Asus.exe is what actually syncs the RGB between Synapse and Aura.

**Comment by alright-sudo** [comment]
so basically i would have to turn it on and restart my pc  for the chroma control to run in the background

**Comment by AndrewBabbitt97** [comment]
Do you have debug mode on? Debug mode causes the modules to appear as Windows so you can see logging output.

It always runs in the background if debug mode is off.

**Comment by alright-sudo** [comment]
ah ok that worked. thank you very much
