### ISSUE TITLE
Wallpaper Engine. Asus Problem

### ISSUE THREAD

**Issue by Leowolf532** [ChromaControl/ChromaControl#132]
Hello, to day i installed Chroma control to try sinc all my RGB´s PC with Wallpaper Engine. Actually Razer and corsair RGB works, they are Sync but ASUS doesn´t Sync. 

What im doing wrong? 

Edit: 
I've gotten everything to work except the motherboard.  To make it work I have removed the components in the Aura Sync application but I cannot remove the motherboard

Edit 2: 

Ok when i close run machine "Chroma control.Asus" (this winsow)
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Chroma Control - Asus...
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Device Provider...
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Dram 1 - 5 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Dram 2 - 5 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: WaterCooler - 4 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Mainboard_Master - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 1 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Razer Chroma Broadcast SDK...
info: ChromaControl.Hosting.ModuleService[0]
      Chroma Control - Asus Started Succesfully!
info: ChromaControl.Hosting.ModuleService[0]
      Razer Chroma Broadcast API Connected
  
stop working but when run it sync works again.

**Comment by AndrewBabbitt97** [comment]
I don't support using Wallpaper Engine at the same time as Chroma Control. Will be up to the community to find solutions and workarounds for this stuff as I don't use it.
