### ISSUE TITLE
Chroma - Aura only works if I keep debug windows showing

### ISSUE THREAD

**Issue by eliitash** [ChromaControl/ChromaControl#133]
Hi, first thanks for the work!
These are the step I follow:
1) Activate Asus on (nothings happen)
2) Active debug mode,desactive asus mode y reactive asus mode
3) Debug windows starts running and then aura lighs are sincronized with chroma
But when I close debug mode windows, aura desincronized of chroma

What I do wrong? What can I do? Attached is a screenshot.

Thank you very much.
![Captura de pantalla 2021-08-13 214916](https://user-images.githubusercontent.com/88914733/129430926-aab82149-7d8c-4a85-996c-9fc570a0d951.png)

**Comment by AndrewBabbitt97** [comment]
The modules by default run in the background. Debug mode makes them run in the foreground as a console window for debugging issues. That's the only change between having debug mode on or off.

So:
1. Turn off the modules
2. Turn debug mode off
3. Turn on the modules

Wait around 30 seconds to a minute and all should be working the same as with debug mode just without the windows showing.

**Comment by eliitash** [comment]
Thank you very much for your fast reply. Recently I tried that, suposse that when in debuggin took a while to sinchronize them, I waited a seconds if it works. Exactly how you say. Now works perfectly. Thank you very much.
