### ISSUE TITLE
ICUE not recognizing Asus Motheboard on GUI

### ISSUE THREAD

**Issue by lucasfigueiredoweb** [ChromaControl/ChromaControl#135]
Config:
ICUE: 4 Up to date
ARMORY CRATE: up to date
Mobo: ASUS x570 Prime PRO with AuraSync

i've searched a lot recently, but i can't see my mobo on ICUE..
![image](https://user-images.githubusercontent.com/12434944/130826098-172e3dd5-f8a0-4510-b451-29bff95836db.png)

Can you guys help me ?

I want to sync all RGB

**Comment by AndrewBabbitt97** [comment]
Closing this issue due to it being unrelated to Chroma Control. Please ask on the Corsair forums or through their support.
