### ISSUE TITLE
Wont Initialize Correctly

### ISSUE THREAD

**Issue by kats1123** [ChromaControl/ChromaControl#136]
tried uninstalling, reinstalling, deleting a bunch of files nothing. Debug window disappears before I can scroll and read it all, but got this as a photo

https://imgur.com/a/coOggyZ

Edit 1: This is for the newest version, trying to mess with 0.1.0.0 to see if it works.

**Comment by AndrewBabbitt97** [comment]
Your image is cut off and doesnt show the start of the stack trace where the exception occurs.

However It looks like the exception is occurring in the Aura SDK. Seeing as there is no way for me to recover from Aura SDK crashes anyways, there's nothing I can do on my side to fix this. The error is inside of your Aura/Armory crate install. I recommend reinstalling armory crate and updating your bios. As a last resort you can try a reinstall of Windows. Armory Crate just has a tendency to cause issues at times and is out of my control.
