### ISSUE TITLE
ChromaControl devices not working after Synapse update 3.6.831.82317

### ISSUE THREAD

**Issue by GalibMura** [ChromaControl/ChromaControl#137]
After being perfectly working for a month, today's Synapse update did something and both, Asus and Corsair modules no longer displayed under Chroma Connect Devices.

Synapse 3 version: 3.6.831.82317

![image](https://user-images.githubusercontent.com/64557822/132079766-7cd9b7bf-4ed8-41f4-a8c3-44151bb3879c.png)

![image](https://user-images.githubusercontent.com/64557822/132079820-1a6bf24e-5ba2-4e1e-9740-5808e131a763.png)

**Comment by Firenzeo** [comment]
Experiencing the same issue

**Comment by leifdotwav** [comment]
exact same thing, even before the update.

**Comment by AndrewBabbitt97** [comment]
Please reinstall the connect module in Synapse. I have not been able to replicate this issue.

**Comment by AndrewBabbitt97** [comment]
Issue is not at all related to 8.6.831.82317. I am running this exact version and am unable to repro this issue.

My only solution I can offer again is to reinstall the Chroma Connect module & synapse. The Chroma Connect module has a tendency to randomly break.

**Comment by leifdotwav** [comment]
reinstalled chroma connect, restarted my machine, and that seemed to fix the issue.

**Comment by GalibMura** [comment]
Thank you @AndrewBabbitt97 I confirm that reinstalling the Chroma Connect module fixed the issue.
