### ISSUE TITLE
[FR] NZXT HUE CONTROL

### ISSUE THREAD

**Issue by icodesdeveloper** [ChromaControl/ChromaControl#139]
Dear,

I dont know if it is possible but an NZXT connection to Synapse also doesnt exist.
It would be very nice to see that also coming to this great program.

**Comment by AndrewBabbitt97** [comment]
NZXT does not provide a first party SDK. So as such this won't be happening.

**Comment by icodesdeveloper** [comment]
Dear maybe this third party api is still interesting:

https://github.com/akmadian/NZXTSharp

**Comment by AndrewBabbitt97** [comment]
I have looked at NZXTSharp. It's not updated frequently and breaks on my initial testing. It's on the community list for requested manufacturers already. It is low priority. Manufacturers that provide first party SDKs are what I am focusing on.
