### ISSUE TITLE
Works amazing! Can you also support Chroma RGBFusion?

### ISSUE THREAD

**Issue by alroy214** [ChromaControl/ChromaControl#14]
iCUE and AURA integration works with Synapse!
Can you try and see if it is possible to make RGBFUsion integration?

**Comment by AndrewBabbitt97** [comment]
I would like to, I however do not have any Gigabyte/Aorus hardware to test with.

**Comment by skins007** [comment]
If you could do this, it would be amazing! My last device to sync is my auros graphics card :(

**Comment by AndrewBabbitt97** [comment]
I will do RGBFusion support once I have finished more general dev work for the project, there's still a bunch of work to be done before I start working on adding new device support.

One of the upcoming things is a Discord server for the community, I would like to get some volunteers who have the hardware In a voice channel to do some development work. Will need a fast iteration loop to get it done quickly.

**Comment by TheRealNox** [comment]
Please ping me if you need help, I own a Gigabyte x570 Aorus Master, and I've been coding professionally for the past 10 years ort so now. I would love to help!

**Comment by AndrewBabbitt97** [comment]
@TheRealNox If you can code this makes it easier, most of the people who make these requests can't.

The big thing needed is an [RGBKit](https://github.com/RGBKit/RGBKit) provider. I'm always open to PRs on that project. Any hardware manufacturer who we get added to RGBKit is easy to create a Synapse integration for. I already have a Gigabyte ID for Synapse as well.

Gigabyte provides an SDK and there are some other open source .NET implementations. I always try to wrap manufacturers SDKs 1:1 in .NET like I did with [Corsairs](https://github.com/RGBKit/CUESDK.NET).

Not sure where most of your experience lies but I can always answer questions and assist where necessarily. I just don't have the ability to test any of it as I don't have the hardware.

**Comment by TheRealNox** [comment]
@AndrewBabbitt97 Sorry I missed your reply.
Not sure, but you're saying I should edit RGBKit and add Gygabite call to its SDK in it?

I'm a c++ dev, but I can see if I can do some .NET, did some in the paste.
Just need some help on where to start and where to look.

**Comment by AndrewBabbitt97** [comment]
@TheRealNox 

Refer to the CUESDK project I did for a reference on usage of native libraries in .NET: https://github.com/RGBKit/CUESDK.NET/tree/master/src/CUESDK.NET

Official documentation on PInvoke can be found here: https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke

Really the goal is to have a good native wrapper for the native SDK similar to what was done for the iCUE SDK. After that Its just adding a device provider in RGBKit by implementing all of the interfaces: https://github.com/RGBKit/RGBKit/tree/master/src/RGBKit.Core

You can see an example of this with the corsair device provider: https://github.com/RGBKit/RGBKit/tree/master/src/RGBKit.Providers.Cue

I can see about getting a repo up in the org for the native wrapper here soon. But that should overall be everything you need to get started.

**Comment by Horogg** [comment]
@AndrewBabbitt97 
If you are looking for tester for Gigabyte / Aorus, I'm here.

**Comment by AndrewBabbitt97** [comment]
@Horogg probably sometime next month, I'm moving here this week so things are gonna be a bit hectic for a bit.

Will definitely be open to willing testers, testing will be done through a Chroma Control discord server.

**Comment by AndrewBabbitt97** [comment]
Closing in favor of #94
