### ISSUE TITLE
Cant install app

### ISSUE THREAD

**Issue by WMR21** [ChromaControl/ChromaControl#140]
Hi, i try to install the app and the installer said error when try to open file from location ChromaControl_0.1.3.0_x86_x64.msixbundle. (0x80070490. my motherboard its an X570 ROG.

![Captura de pantalla 2021-09-12 142350](https://user-images.githubusercontent.com/90570785/132996913-152deede-264a-4f46-a31c-13cf54ac632b.jpg)

Thks for the time.

**Comment by AndrewBabbitt97** [comment]
Try manually downloading the msixbundle and open it: https://github.com/ChromaControl/ChromaControl/releases/tag/0.1.3

**Comment by Thim11** [comment]
I have the same problem, Manually downloading does not resolve this issue. I have this already works on my main account, but I added a second account on my computer and from here I cannot use this sofware, I tought it should be accessable for this account after I downloaded it from my main account but I cannot find Chroma Controller back and after trying to installing this app, it results also ni these error code.

**Comment by Xarkam** [comment]
Look at https://github.com/ChromaControl/ChromaControl/issues/160

**Comment by nathanschrope** [comment]
Im no doctor, but I think the cert just needs a timestamp. I think windows is made that there is no timestamp. @AndrewBabbitt97

**Comment by nathanschrope** [comment]
Switching the date to January worked though. Like the other issues seemed to suggest.

**Comment by AndrewBabbitt97** [comment]
Fixed in latest update.
