### ISSUE TITLE
Please add installation instructions and basic usage instructions to the Readme.

### ISSUE THREAD

**Issue by Griffork** [ChromaControl/ChromaControl#141]
I'm considering using this app, but I don't understand what I need installed to make it work or how intuitive it is (e.g. "Use the eye dropper to select a colour and then press apply to see the changes!") and if there's any 'gotchas' for programming the different things like not being able to do loops like corsair does. 

It would also be great to have a simple image of the program in operation so users can know what to expect  and some information on how easy/hard it is to start configuring stuff after installation (do you need to specify how long lighting strips are or whether or not things are in sequence to make fancy lighting effects, or are only basic lighting effects supported but it works out of the box?).

None of this needs to be in depth, just some dotpoints for each point would be great.

Thanks!

**Comment by AndrewBabbitt97** [comment]
Docs site is WIP right now and currently don't have much time to work on Chroma Control with work at the moment.

Installing is just hitting the download button on the website https://ChromaControl.github.io

Historically it's been a headless service so there was no configuration beyond just installing it. Now the UI just has toggles to turn on the modules you want and that's really it.

Documentation will be coming over time, we're still in early preview versions and a lot of UI is going to be changing in the next few releases.

**Comment by GalibMura** [comment]
@Griffork Hello!, by the explanation you´ve given on your question I think you are confused on what´s the purpose of this program.

Chroma Control is the binder between Razer Synapse 3 and products that are not compatible with Razer software, like Asus and Corsair.

When using Chroma Control you´ll be able to modify the lighting on those products using RAZER Software. There you´ll select the effects, the colors, the patterns and so.

Chroma Control won´t allow you to directly control the lighting of your hardware, you{ll do that in Razer Synapse.

I hope this information clears your expectations.

**Comment by blaze86vic** [comment]
@Griffork Hello, I just went for it and installed.  After intalling I found that you need to have iCue and Aura running.  The Chroma Control app would appear to me to enable Razer Chroma to control non-Razer devices through their perspective programs, not directly to the device.  Hope this clears things up.

**Comment by Griffork** [comment]
Thanks @blaze86vic !

**Comment by AndrewBabbitt97** [comment]
Install is handled via the website, which is also linked in the description of the repo as well as the Discord.
