### ISSUE TITLE
Unable connect to asus

### ISSUE THREAD

**Issue by RuninngDog69** [ChromaControl/ChromaControl#144]
![image](https://user-images.githubusercontent.com/90789172/133475468-01999db4-8919-4aad-b810-a946b601ed88.png)

**Comment by AndrewBabbitt97** [comment]
That error is coming from the Aura SDK. Something's up with your Armory Crate/Aura install.

**Comment by RuninngDog69** [comment]
> That error is coming from the Aura SDK. Something's up with your Armory Crate/Aura install.

Hi Andrew, thank for reply
I have try to reinstall everything, but it still encounter same error, have any solution to fix this ?
Again, thanks for the kind assist

**Comment by AndrewBabbitt97** [comment]
> > That error is coming from the Aura SDK. Something's up with your Armory Crate/Aura install.
> 
> Hi Andrew, thank for reply
> I have try to reinstall everything, but it still encounter same error, have any solution to fix this ?
> Again, thanks for the kind assist

Unfortunately no I don't have any solutions, Aura just has a tendency to be weird randomly and I'm not quite sure why.

**Comment by RuninngDog69** [comment]
> > > That error is coming from the Aura SDK. Something's up with your Armory Crate/Aura install.
> > 
> > 
> > Hi Andrew, thank for reply
> > I have try to reinstall everything, but it still encounter same error, have any solution to fix this ?
> > Again, thanks for the kind assist
> 
> Unfortunately no I don't have any solutions, Aura just has a tendency to be weird randomly and I'm not quite sure why.

Thanks for the answer
