### ISSUE TITLE
Palit ThunderMaster support?

### ISSUE THREAD

**Issue by thethiny** [ChromaControl/ChromaControl#145]
Hi,
Love your work and been using it for a while, and it's perfect and perfectly stable! Though I have a request. Yesterday I got a Palit RTX GPU and it comes with Sync support as well as its own ThunderMaster app. Think you can add it to the supported apps?

**Comment by AndrewBabbitt97** [comment]
Belongs in #94, need links to RGB SDKs for support. No RGB SDK = No support.
