### ISSUE TITLE
Suggestions/Idea could you add support for (SoundBlaster Command)Creative Sound-Blaster AE-5?

### ISSUE THREAD

**Issue by TestForFunOrSo** [ChromaControl/ChromaControl#148]
could you add support for (SoundBlaster Command)Creative Sound-Blaster AE-5? the sdk is downloadable from thei website see if it works: https://www.soundblaster.com/blasterx/aurorasdk/

**Comment by Supergrovercm** [comment]
I would welcome this also.

**Comment by AndrewBabbitt97** [comment]
Added to #94
