### ISSUE TITLE
Synapse doesn't have anything in the devices tab (Armory Crate)

### ISSUE THREAD

**Issue by Drew9140** [ChromaControl/ChromaControl#149]
I'm not getting the Asus tab (or whatever it is) to appear in Synapse. I have aura enabled in Armory Crate and have updated to the latest drivers and apps.
![Chroma](https://user-images.githubusercontent.com/50637409/139013995-74e7b5eb-6d8f-4124-be86-1b91a4d42276.png)
r

**Comment by AndrewBabbitt97** [comment]
Error message in the console window is from the AURA SDK. No known way to resolve this, something weird on your hardware/software level with AURA.
