### ISSUE TITLE
Error message on boot - AsIO3.sys

### ISSUE THREAD

**Issue by skins007** [ChromaControl/ChromaControl#15]
The program works fine, however on boot I need to wait for the below error message (which comes up twice), once I click OK then it syncs with Synapse.

![image](https://user-images.githubusercontent.com/47616334/105649606-c3876080-5f00-11eb-9a71-1ff59e12ad6f.png)

Log is also attached
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/5863590/ASUS.log)

**Comment by AndrewBabbitt97** [comment]
This error does not come from my software, its coming from the AURA DRAM HAL.

Make sure everything is up to date in Armory Crate, if the issue persists reinstall Armory Crate/drivers. This is specific to your windows/aura install.

**Comment by orng-e** [comment]
Everything is up to date with Aura, I'm not too sure why it would give me problems. I even reinstalled.
