### ISSUE TITLE
Cannot install Chroma Control

### ISSUE THREAD

**Issue by sherwinignatius** [ChromaControl/ChromaControl#151]
Hi,

I tried installing Chroma Control but I have an error saying "cannot open app package" with reason "An error occurred while accessing the file from the web. Please try downloading and opening the file locally."

Please help!

**Comment by weewee88** [comment]
Go to the latest release page:
https://github.com/ChromaControl/ChromaControl/releases/tag/0.1.3

Find and click on a file named "ChromaControl_0.1.3.0_x86_x64.msixbundle", it should download the file and you can install it like a .exe file.

**Comment by sherwinignatius** [comment]
Great! Thank you so much.

**Comment by radjin123** [comment]
Hi Andrewbabbitt97 thank yo so much for this. I'm wondering if you can help me? I'm still having trouble installing Chroma Control even after following these step? When I try to install the file above I get an error in the installer window saying: "This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)"
![App Installer 18_02_2022 11_38_48 AM](https://user-images.githubusercontent.com/99930581/154595482-ebcdf2e9-b258-48c1-ab35-7c4ee1f1357a.png)

**Comment by AndrewBabbitt97** [comment]
> Hi Andrewbabbitt97 thank yo so much for this. I'm wondering if you can help me? I'm still having trouble installing Chroma Control even after following these step? When I try to install the file above I get an error in the installer window saying: "This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)" ![App Installer 18_02_2022 11_38_48 AM](https://user-images.githubusercontent.com/99930581/154595482-ebcdf2e9-b258-48c1-ab35-7c4ee1f1357a.png)

Workaround in #169
