### ISSUE TITLE
Pls Help "Cant open Asl03.sys error 2"

### ISSUE THREAD

**Issue by JKiller99** [ChromaControl/ChromaControl#152]
hello I have a problem which I cannot find a solution anywhere. when I start my pc I get this error
Aac3572DramHal_x64.exe error
Can't open Asl03.sys !!
failed whit error code 2: the system cannot find the specified file.

This happened after when I bought a razer rgb product and installed chroma control, my pc went crazy and wouldn't let me use it, it gave me blue screens and I didn't find any other solution other than to restart it completely. I already had aura creator installed to change the rgb of my mother and my RAM but after the restart I could not install it again since the same error arose and I had to restart again. now i only have icue installed for my corsair mouse and keyboard, but i want to change the color of my mother and ram but i am afraid i will get the same error and have to reset everything again. I leave all the RGB components of my pc if it helps them.

Mother: PRIME B550M-A/CSM (update)
RAM: T-Force Delta RGB DDR4 3000
Cpu Cooler: Aerocool Cyclon 3 Argb
Mouse: Corsair Ironclaw
Keyboard: Corsair K60 RGB Pro MX Cherry Low Profil
<img width="374" alt="Error" src="https://user-images.githubusercontent.com/94877885/142957891-ef5cf8a2-c0df-4be9-8955-b9435ab746b4.png">
e

**Comment by AndrewBabbitt97** [comment]
This is not related to CC, this is an Aura/Armory Crate issue. Reach out to ASUS support.
