### ISSUE TITLE
Use of ChromaControl.Asus.exe causes FPS limit in Overwatch.

### ISSUE THREAD

**Issue by crkochan** [ChromaControl/ChromaControl#153]
This is kind of a strange one. Ever since September, people have been reporting FPS limits [on Reddit](https://www.reddit.com/r/Overwatch/comments/pj2sy8/is_your_game_stuck_at_6364_fps_please_read/) and in [the Blizzard forums](https://us.forums.blizzard.com/en/overwatch/t/locked-at-60-fps/631348/15) in the neighborhood of 60-ish frames per second in Overwatch when Chroma Effects are enabled for the game. I have been experiencing this bug as well.

As I noted in the linked threads above, I noticed recently that my Razer gaming laptop did not exhibit this FPS limit in OW, but my desktop using Chroma Control to sync my ASUS motherboard & G.SKILL RAM does. So I experimented and found that if `ASUS Enabled` is turned on in the Chroma Control panel, then I hit the FPS limit in OW. 

More interesting than that, if I go into Synapse and open the Connect module settings, flip to Devices, and turn off either the slider for `Chroma Control - ASUS` or the master slider for `CHROMA CONNECT`, I will still hit the FPS limit in OW, even though the Aura controlled RGB no longer follows the native Razer devices. Uninstalling the Connect module will also avoid the problem, of course.

During the course of investigating, I did full removal and reinstalls of both the Connect module as well as Chroma Control. Enabling debug mode showed no unusual messages in the ChromaControl.Asus console window when running the game.

```
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Chroma Control - Asus v0.1.3...
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Device Provider...
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS0 - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS1 - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS2 - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS3 - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Vga 1 - 1 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Mainboard_Master - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 1 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 2 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Razer Chroma Broadcast SDK...
info: ChromaControl.Hosting.ModuleService[0]
      Chroma Control - Asus Started Succesfully!
info: ChromaControl.Hosting.ModuleService[0]
      Razer Chroma Broadcast API Connected
```

Currently I am on v3.6.1130.111217 of Synapse, and v0.1.3 of Chroma Control and ASUS module.

**Comment by AndrewBabbitt97** [comment]
Issue is not currently reproducible in Overwatch 2.
