### ISSUE TITLE
Unable to sync armory crate controlled devices and synapse devices 

### ISSUE THREAD

**Issue by GWash7** [ChromaControl/ChromaControl#156]
I have armory crate, synapse, and chroma control installed. 
everything inside my pc case is synced together with armory and all peripherals are on synapse as they are razor. 
I am unable to get them all to sync. 

Inside synapse if I  go to connect there is no option to turn arura on.  
therefore there is no way of syncing. 

Can someone please help me. I have tried everything I know of.

**Comment by AndrewBabbitt97** [comment]
Issues should be resolved in the upcoming release, if not feel free to reopen.
