### ISSUE TITLE
Failed to install - this didn't happen before

### ISSUE THREAD

**Issue by ofirda** [ChromaControl/ChromaControl#157]
As I updated iCue and Auroa and Synapse I decided to uninstall and reinstall chroma control which was working fine
but now i file to install - i tried version 0.1.2 and 0.1.3

I get this error:
App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.3.0_neutral_~_q2sx6sw85pbp2 from:  (ChromaControl_0.1.3.0_x86_x64.msixbundle)  failed with error 0x8000FFFF. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8000ffff)
How do I overcome this?

**Comment by ofirda** [comment]
using windows 11 - is that what's causing the case?

**Comment by ofirda** [comment]
it dos install on another user account but wont show up in razer synapse latest version
any help will be appreciated

**Comment by Xarkam** [comment]
Hello, can you test my work around https://github.com/ChromaControl/ChromaControl/issues/160 ?
:)

**Comment by AndrewBabbitt97** [comment]
Should be resolved in the upcoming release, if not feel free to reopen.
