### ISSUE TITLE
How you install this? Nothing works win 11.  

### ISSUE THREAD

**Issue by Plusmies** [ChromaControl/ChromaControl#159]
You say open msix and install, but there is nothing to open and install in the file. I have win 11 and all application programs installed. I also tried a couple of msix editors from the microsoft store and nothing. Where is the problem?

**Comment by Xarkam** [comment]
Hello, test my work around https://github.com/ChromaControl/ChromaControl/issues/160.

**Comment by AndrewBabbitt97** [comment]
Fixed in latest update.
