### ISSUE TITLE
Asus Module not wotking: Open device Fail, Getlasterror: 5!

### ISSUE THREAD

**Issue by KarlosMvZ** [ChromaControl/ChromaControl#162]
Hi,
Asus module in Chroma Studio not showing, in debug mode shows this  
![image](https://user-images.githubusercontent.com/96927503/147840634-55ead5e3-64dd-415d-82a1-b6eee425393e.png)

I alreadyt reinstalled Synapse and ChromaControl

**Comment by AndrewBabbitt97** [comment]
That text comes from Aura, not Chroma Control. As for what it means we still don't know. Something internal to ASUS.
