### ISSUE TITLE
unable to download / install

### ISSUE THREAD

**Issue by nodiaque** [ChromaControl/ChromaControl#165]
Hello,

The link to download on the bottom of the readme doesn,t work anymore. Microsoft disable the app-storeinstaller from web browser.
https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web

I tried downloading all file in the release folder but when I try to install the msixbundle, it says it's signed with an untrusted certificate. I tried adding the .cer to the trusted cert but it doesn't work because it has expired.

**Comment by fr4j4** [comment]
The certificate appears to be expired 😢

**Comment by JasonLagace** [comment]
bump

**Comment by nodiaque** [comment]
Problem is the cert, and the bigger problem is the fact the app wasn't signed with a timestamp.

https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview

The following are the different scenarios around app signing with/out timestamping:
Timestamping
Scenario 	# App is signed without timestamping 	#App is signed with timestamping
Certificate is valid 	# App will install 	App will install
Certificate is invalid(expired) 	# App will fail to install 	# App will install as the authenticity of the cert was verified at signing by timestamping authority

**Comment by AlexLamond** [comment]
Can download from https://github.com/ChromaControl/ChromaControl/releases/download/preview/ChromaControl.appinstaller

**Comment by nodiaque** [comment]
Doesn't work, certificate expired on the file. When you sign, you must timestamp the signature to prevent that. As long as the certificate used to sign was valide at the time of sign, the apps continue to work past the expiration date.

**Comment by AlexLamond** [comment]
Set your clock back a couple of days and re-run the installer, then you can set your clock back to normal time. It's a weird workaround, but it installs

**Comment by nodiaque** [comment]
yeah, last time I did that, I broke other stuff in my computer. I run some time sensitive stuff on it. I guess I'll wait for the source to be packaged again.

**Comment by AndrewBabbitt97** [comment]
I'm aware the cert expired, it doesn't change the fact that MSIX is honestly still a pretty rough install format and UWP/Windows App SDK needs a lot of work.

Current workaround is to set your clock back for the time being.

A new installer and UI is coming out next weekend. I have no plans to renew the cert just for this.

Updates have been posted on this in the Discord already.

**Comment by AndrewBabbitt97** [comment]
Fixed in latest update.
