### ISSUE TITLE
Certificate for Chroma Control is outdated/expired!!

### ISSUE THREAD

**Issue by MadDevil13** [ChromaControl/ChromaControl#166]
Hi

I can not install Chroma controll after I master reset my computer. And then I found out that the certificate is expired 20.01.2022.
Windows system do not let me to install it without valid certificate with date etc..

![image](https://user-images.githubusercontent.com/98179677/150572190-9c1e6bac-3862-470b-b45d-9bd42598201c.png)

![image](https://user-images.githubusercontent.com/98179677/150581668-ee89e351-cbb9-44e9-aeaf-59e0d3f07580.png)

"_This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)_"

Can this be fixed and asap? 

MadDevil13

**Comment by vector-4** [comment]
yes please! same problem here

**Comment by BloxBoss6** [comment]
I also have the same issue

**Comment by AndrewBabbitt97** [comment]
I'm aware the cert expired, it doesn't change the fact that MSIX is honestly still a pretty rough install format and UWP/Windows App SDK needs a lot of work.

Current workaround is to set your clock back for the time being.

A new installer and UI is coming out next weekend. I have no plans to renew the cert just for this.

**Comment by AndrewBabbitt97** [comment]
Fixed in latest release.
