### ISSUE TITLE
Don't work with Asus Rog Strix Z390-F mobo

### ISSUE THREAD

**Issue by Albredo** [ChromaControl/ChromaControl#167]
Hey,

my ram works fine, but the leds on the mobo don't work.

**Comment by AndrewBabbitt97** [comment]
What motherboard?

**Comment by Albredo** [comment]
Ah, sry, asus rog strix z390‐f

**Comment by AndrewBabbitt97** [comment]
Turn on debug mode and restart your PC, get the console output after around a minute of it being shown

**Comment by Albredo** [comment]
Yeah

![20220204_201204](https://user-images.githubusercontent.com/98900142/152589067-f1b6d83a-5455-40bc-9716-0ebc37e47d40.jpg)

**Comment by khanhlumpy** [comment]
@AndrewBabbitt97 Hello Andrew, I'm using main Asus tuf B560m plus. Installed chroma control
![image](https://user-images.githubusercontent.com/101488629/158043357-48961d01-e708-4e16-a7a4-3587a68de645.png)
In the app, the color showing correctly but real time the color on the main is different than in Synapse. Could you help me you, please?

**Comment by AndrewBabbitt97** [comment]
Probably some other software causing issues. Chroma Control is fully functioning based on this image. You need to dig into your armory crate install or other clashing software on your PC to find what's going wrong.

If you want help from me, you will need to reinstall Windows and only install Armory Crate, Synapse, and Chroma Control and test again. If issue goes away then its likely some piece of software you had installed clashing.
