### ISSUE TITLE
Certificate Problem

### ISSUE THREAD

**Issue by Costiss** [ChromaControl/ChromaControl#169]
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)

**Comment by scrum87** [comment]
Is there any possibility this will be fixed in near future @AndrewBabbitt97 ? I am not getting it working with the workaround to set back the clock on my computer though :/

**Comment by AndrewBabbitt97** [comment]
Currently working on other stuff needed for an update over here: https://github.com/AndrewBabbitt97/BlazorDesktop

Workaround is to set your date back to January 1st then try to reinstall.

**Comment by vasic91** [comment]
> Currently working on other stuff needed for an update over here: https://github.com/AndrewBabbitt97/BlazorDesktop
> 
> Workaround is to set your date back to January 1st then try to reinstall.

Not working with date changing

**Comment by AndrewBabbitt97** [comment]
Fixed in latest release.
