### ISSUE TITLE
Support palit software

### ISSUE THREAD

**Issue by ImASadBoy** [ChromaControl/ChromaControl#17]
The software works amazing, would it be possible to support the palit RGB software too?

**Comment by AndrewBabbitt97** [comment]
I'm not seeing an SDK for Palit. I see they may have some cables to control GPU lights with a standard RGB header however.

Unless it's a major brand, it's unlikely to have an RGB SDK that I can use to add support.

**Comment by ImASadBoy** [comment]
Hey, I cannot see the elements on the synapse dashboard, I have a corsair
vengeance pro and an asus B450-F

Il giorno lun 1 feb 2021 alle ore 16:40 Andrew Babbitt <
notifications@github.com> ha scritto:
