### ISSUE TITLE
New Aura Creator

### ISSUE THREAD

**Issue by YU-wen-1998** [ChromaControl/ChromaControl#170]
Hi Andrew, I have been using your product for a while and it went well before. But after I updating my Asus Aura Creator, this software does not Sync with my Asus Laptop's RGB now. When I ran the debug mode and restarted my Laptop, the console ChromaControl.Asus poped up, 2 lines of code appeared and after a short time the ChromaControl.Asus console disappeared.
I have tried clear data of Aura Creator and it did not work.

**Comment by AndrewBabbitt97** [comment]
Aura Creator is not supported to be used with Chroma Control, it has the ability to override Chroma Controls ability to control devices. Uninstall Armory Crate and reinstall being sure not to check the option to install Aura Creator.

**Comment by YU-wen-1998** [comment]
Thanks Andrew!
