### ISSUE TITLE
error when installing 

### ISSUE THREAD

**Issue by savagetaco77** [ChromaControl/ChromaControl#172]
Hi all, 

I have been on discord and looked at all the issues here but have not seen a resolution to this one 

App installation failed with error message: Common::Deployment::MsixvcStagingSession::GetManifestReader in MsixvcStagingSession failed with error 0x80070570. (0x80070570)

**Comment by ma9851** [comment]
Any update on this? I get the same issue. Tried different release versions and all fail.

**Comment by AndrewBabbitt97** [comment]
Fixed in latest release.
