### ISSUE TITLE
I can't install chroma control?

### ISSUE THREAD

**Issue by on9gamerx** [ChromaControl/ChromaControl#173]
I was trying to install chroma control .. but windows don't allow me to install the files that i downloaded from github website.
when i try to install "ChromaControl_0.1.3.0_x86_x64.msixbundle" windows pop up this error messages "This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)" and i have checked the certificate expired date is on 2022/01/20. Please advise what can i do next?

**Comment by Blarnix** [comment]
Yeah. I'm also getting this issue, the certificate expired on 1/19/2022 and hasn't been updated to resign it. They need to renew the certificate before it's able to be installed again.

**Comment by SilkyZ** [comment]
same error 
![image](https://user-images.githubusercontent.com/2307734/164529937-e6a662e5-6c5d-429b-9b85-c0ff3ee335a3.png)

**Comment by rand92000** [comment]
> I can confirm it's a bug problem and seeing no known working solution to it. Please, help: @AndrewBabbitt97

**Comment by AndrewBabbitt97** [comment]
Download from the GitHub releases and install the MSIX manually. Will need to set the date back to Jan 1st to install because of an expired cert.

Most people use the Discord server for support where this has been addressed.

**Comment by rand92000** [comment]
> Download from the GitHub releases and install the MSIX manually. Will need to set the date back to Jan 1st to install because of an expired cert.
> 
> Most people use the Discord server for support where this has been addressed.

Ok, thank you. Sorry for being a noob - I just found out about ChromaControl like 30 minutes ago - I'm very new here.

SO, basically to sum this up - **here's the FIX** for noobs like me: 
**1.** From the "Releases", download [ChromaControl_0.1.3.0_x86_x64.msixbundle ](https://github.com/ChromaControl/ChromaControl/releases/download/0.1.3/ChromaControl_0.1.3.0_x86_x64.msixbundle) or newer (I guess it's only for Windows 10 or 11+ because of a build-in app for such extension files)
**2.** Change the system date back to 1st of January 2022
**3.** Install the .msixbundle
**4.** Change the date back. - SHOULD WORK NOW.

**Comment by SilkyZ** [comment]
alright, this is helpful, thanks!

I'll have to check the discord later then for anything else!

**Comment by NEUR0515** [comment]
> > Download from the GitHub releases and install the MSIX manually. Will need to set the date back to Jan 1st to install because of an expired cert.
> > Most people use the Discord server for support where this has been addressed.
> 
> Ok, thank you. Sorry for being a noob - I just found out about ChromaControl like 30 minutes ago - I'm very new here.
> 
> SO, basically to sum this up - **here's the FIX** for noobs like me: **1.** From the "Releases", download MANUALLY (not from the standalone website) [ChromaControl_0.1.3.0_x86_x64.msixbundle ](https://github.com/ChromaControl/ChromaControl/releases/download/0.1.3/ChromaControl_0.1.3.0_x86_x64.msixbundle) or newer (I guess it's only for Windows 10 or 11+ because of a build-in app for such extension files) **2.** Change the system date back to 1st of January 2022 manually **3.** Install the .msixbundle **4.** Change the date back to automatic. - SHOULD WORK NOW.

This resolved the issue for me

**Comment by Olive-Branches** [comment]
> > Download from the GitHub releases and install the MSIX manually. Will need to set the date back to Jan 1st to install because of an expired cert.
> > Most people use the Discord server for support where this has been addressed.
> 
> Ok, thank you. Sorry for being a noob - I just found out about ChromaControl like 30 minutes ago - I'm very new here.
> 
> SO, basically to sum this up - **here's the FIX** for noobs like me: **1.** From the "Releases", download MANUALLY (not from the standalone website) [ChromaControl_0.1.3.0_x86_x64.msixbundle ](https://github.com/ChromaControl/ChromaControl/releases/download/0.1.3/ChromaControl_0.1.3.0_x86_x64.msixbundle) or newer (I guess it's only for Windows 10 or 11+ because of a build-in app for such extension files) **2.** Change the system date back to 1st of January 2022 manually **3.** Install the .msixbundle **4.** Change the date back to automatic. - SHOULD WORK NOW.

Worked, thanks

**Comment by on9gamerx** [comment]
The chroma control doesn't work anymore, once you update the latest version of the razer synapse and Asus Armoury Crate.

**Comment by nfs2192** [comment]
> The chroma control doesn't work anymore, once you update the latest version of the razer synapse and Asus Armoury Crate.

What version works?

**Comment by RealRabidWolf** [comment]
> > > Download from the GitHub releases and install the MSIX manually. Will need to set the date back to Jan 1st to install because of an expired cert.
> > > Most people use the Discord server for support where this has been addressed.
> > 
> > 
> > Ok, thank you. Sorry for being a noob - I just found out about ChromaControl like 30 minutes ago - I'm very new here.
> > SO, basically to sum this up - **here's the FIX** for noobs like me: **1.** From the "Releases", download MANUALLY (not from the standalone website) [ChromaControl_0.1.3.0_x86_x64.msixbundle ](https://github.com/ChromaControl/ChromaControl/releases/download/0.1.3/ChromaControl_0.1.3.0_x86_x64.msixbundle) or newer (I guess it's only for Windows 10 or 11+ because of a build-in app for such extension files) **2.** Change the system date back to 1st of January 2022 manually **3.** Install the .msixbundle **4.** Change the date back to automatic. - SHOULD WORK NOW.
> 
> This resolved the issue for me

it worked

**Comment by patdogg** [comment]
currently have Razer Synapse, Armoury Crate, and Chroma Control all updated and am having issues connecting my asus laptop keyboard with my razer mouse through Razer Synapse.

**Comment by AndrewBabbitt97** [comment]
Fixed in latest release.
