### ISSUE TITLE
After installing Chroma Control: Mouse Pointer and Loading icon/animation constantly showing up

### ISSUE THREAD

**Issue by agigao** [ChromaControl/ChromaControl#175]
First of all thank you dude for this awesome work! 

I appreciate!

Now, the issue I'm facing right now - I wish I hadn't posted this, but after installing ChromaControl, I see loading icon/animation alongside pointer - constantly.

Screenshot:
![8ef2d47e-8297-41d8-bafc-ede56e80291f](https://user-images.githubusercontent.com/22436648/169609912-4a887262-5ffe-4e40-88fa-2888be6acab7.png)

Any ideas how to get rid of this annoyance? 

Thanks,
Giga

**Comment by AndrewBabbitt97** [comment]
Have never seen this, unless I can reproduce the issue theres nothing I can do to fix it. If there's a known 100% way to get this to occur we can look deeper but there must be repro steps to do so.

**Comment by AndrewBabbitt97** [comment]
Stale issue.
