### ISSUE TITLE
Corsair Products Don't Lightup after Awaking PC from Sleep

### ISSUE THREAD

**Issue by BB4LIFE** [ChromaControl/ChromaControl#177]
After awaking my PC from sleep, my corsair ram and fans stop lighting up.  They all sync fine after a restart though.

**Comment by Kaldaka** [comment]
Am having the same problem. I posted as well with a bit more information. Maybe the way I described the problem is also the same for you?

**Comment by AndrewBabbitt97** [comment]
Duplicate of #37
