### ISSUE TITLE
Document RzChromaBroadcastAPI GUIDs

### ISSUE THREAD

**Issue by ImASadBoy** [ChromaControl/ChromaControl#18]
I tried installing the latest release and the beta too, but they're both not showing in synapse. I cannot see chroma controls in my chroma apps

**Comment by AndrewBabbitt97** [comment]
Need logs from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

Along with this a screenshot from Synapse of the "Connect" menu, also make sure you are on the Devices subtab in that menu.

**Comment by ImASadBoy** [comment]
Nvm mind, now it is showing after some tweaks, but my Corsair Vegnance pro
RAM is not showing and can't be controlled by synapse


Il giorno mer 3 feb 2021 alle ore 23:55 Andrew Babbitt <
notifications@github.com> ha scritto:

**Comment by AndrewBabbitt97** [comment]
Please refer to #16, we have a potential fix for corsair ram.

**Comment by ImASadBoy** [comment]
Did it and didn't work, also another issue that just popped up is that
whenever i launch r6 siege or a "heavy game" chroma connect uses 60% of GPU
power, I had to uninstall it.

**Comment by AndrewBabbitt97** [comment]
Chroma Control using GPU power? Chroma Control doesn't even use any graphics APIs.

Also there's multiple Chroma Control modules, which one uses "GPU Power"?

**Comment by ImASadBoy** [comment]
I misspelled "CPU"

**Comment by AndrewBabbitt97** [comment]
Regardless, which module is using CPU?

**Comment by ImASadBoy** [comment]
The corsair one

**Comment by isaac-bender** [comment]
I also don't see the devices in Synapse, both with the released binaries, and with ones I built locally.
Your other releases, "Chroma Control - ASUS" and "Chroma Control - Corsair" do work, although I didn't build those myself. Uninstalling the other apps didn't help.

Just to see if it would work, I put a quick hack in the loop at the end of ChromaControl.Cue Worker's ExecuteAsync that sets the device colors to some hardcoded values, and it does successfully light up the RAM, so the issue appears to be solely with the Razer connection.

I noticed the RzChromaBroadcastAPI is being inited with a null GUID. Is that expected to work?

Here's the output from ChromaControle.Cue when I run it from Visual Studio. Breakpoints in Api_ConnectionChanged aren't being hit, and I don't see any "Razer Chroma Broadcast API *" messages.

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: L:\ChromaControl-master\src\ChromaControl.Cue
info: ChromaControl.Worker[0]
      Initializing ChromaControl.Cue...
info: ChromaControl.Worker[0]
      Found Device: CUE - VENGEANCE RGB PRO 1
info: ChromaControl.Worker[0]
      Found Device: CUE - VENGEANCE RGB PRO 2
info: ChromaControl.Worker[0]
      Found Device: CUE - VENGEANCE RGB PRO 3
info: ChromaControl.Worker[0]
      Found Device: CUE - VENGEANCE RGB PRO 4
info: ChromaControl.Worker[0]
      Found Device: CUE - ASUS Motherboard
info: ChromaControl.Worker[0]
      Found Device: CUE - ASUS GPU: Vga 1
info: ChromaControl.Worker[0]
      ChromaControl.Cue started successfully!

**Comment by AndrewBabbitt97** [comment]
@isaac-bender Sources for the MSIX beta aren't up yet, the old release plus the code on master don't work due to a bug in one of the NuGet packages on that release.

Sources will be released soon, a lot has changed.

As for the null GUID, the GUID's are generated by Razer and were not allowed to distribute them in the source code. They will be a secret on the release pipeline for builds in the future along with the signing key for the MSIX packages.
