### ISSUE TITLE
Trident Z Neo RAM lights are not working with ChromaControl.

### ISSUE THREAD

**Issue by Rycia** [ChromaControl/ChromaControl#180]
While running the latest version of Windows 10,
and Synapse X,
alongside Trident Z Lighting Control with "External Sync,"
and Armory Crate (without running it when my PC starts up,)

![image](https://user-images.githubusercontent.com/43384589/179838541-f46aa577-8826-4d37-88e5-2d022899adf5.png)
Here is my Trident Z Lighting control.
This was needed when AuraConnect was available for download and that program actually worked.. sometimes. I did the same setup as would work for AuraConnect.

![image](https://user-images.githubusercontent.com/43384589/179839221-aea4119a-dfb3-467d-8946-d2673e213c86.png)
Here is my enabled startup programs so it could be seen what launches with my PC on startup. I don't mess with this.

![image](https://user-images.githubusercontent.com/43384589/179839344-1ec9bd89-ca98-4fb3-a945-306173ed151b.png)
This is my page for Chroma Control.

![image](https://user-images.githubusercontent.com/43384589/179839433-162effc7-e7eb-4eb9-b80b-1cb35d829a04.png)
Main page for my Razer Synapse. Chroma Control does show.

And here's what that page looks like. I just have Asus enabled since I have no Corsair RGB products.
![image](https://user-images.githubusercontent.com/43384589/179839578-661fba6c-eb54-4d74-8070-8a5667fa4edc.png)

EDIT: Okay, as I was writing this, I found the issue.
I'll still post in case someone else has the same visual issue.
So, right when I was going to post the picture of my Synapse, since the issue was Chroma Studio was showing that my RAM lighting was supposed to be lighting up when physically on my PC my lighting wasn't reflecting what I was putting on it in Chroma Studio. Here's a screenshot of that.
![image](https://user-images.githubusercontent.com/43384589/179840746-ece9870a-7983-4e2d-b441-70dbcd6b4e84.png)

Well, you see, on the bottom right hand corner of that same screenshot, Chroma Control put an additional copy of that, but for Asus Lighting.
For some reason Chroma Control is creating both one for Asus and G.skill and only the Asus one works. Here is the screenshot in which the text on both and configuration is shown a bit better.
Honestly, there should be a way for Chroma Control to utilize just Asus.

I have no extra programs like Chroma Control installed, so the only thing that could be doing this is Chroma Control.
This is confusing.
Perhaps I need to uninstall G.skill lighting control? I thought by default it doesn't handle syncing up to Razer without an external program, unless there has been an update to it that allows it to, and henceforth, creates the one for G.skill? In that case, a note should be made that G.skill lighting control is replaced by Chroma Control, and conflicts/is incompatible and should be uninstalled.
![image](https://user-images.githubusercontent.com/43384589/179841256-31265aa7-82bd-4704-8ba0-57055d00b601.png)

**Comment by AndrewBabbitt97** [comment]
ASUS module also wants to control GSkill ram, this is addressed in #40

Our solution is to either pick the ASUS module or the GSkill software, cant use both at the same time.
