### ISSUE TITLE
Can not install the latest update.

### ISSUE THREAD

**Issue by gent00** [ChromaControl/ChromaControl#181]
The installation is failed: The appinstaller uri https://github.com/ChromaControl/ChromaControl/releases/download/preview/ChromaControl.appinstaller is already being used by another package and cannot be applied to package ChromaControl_s9a324077yex8 until the association is removed. (0x80004005)

![1](https://user-images.githubusercontent.com/5721191/181109381-6551e171-323c-4c18-9157-e088bd85689f.png)

**Comment by gent00** [comment]
I installed the previous version and the re-installed the newest one. It works when you do that. But it just does not update or overwrite.

**Comment by AndrewBabbitt97** [comment]
Uninstall the old version then install the new one.
