### ISSUE TITLE
Request: support wider/full range of iCue LEDs (making Asus integration likely unnecessary)

### ISSUE THREAD

**Issue by andyman1222** [ChromaControl/ChromaControl#183]
Running ChromaControl, iCue support works as expected, however Aura does nothing. I believe this is due to a conflict with iCue and ChromaCreator on the Aura SDK.

As of at least iCue 4, Corsair has integrated Aura support into their software, at least for motherboards (see picture). (I'm not sure about integration for other components)

![image](https://user-images.githubusercontent.com/14265340/181388480-f46d7465-5ad1-40fe-85a0-7f56ebb5ae14.png)

I previously created an integration program with Synapse, which used diyHue to emulate 10 LEDs, and diyHue would send the info back to my PC to a program that would work with iCue and Logitech (I never got MSI mystic light working with my monitor). (I since switched my setup, making my original program obselete for now, so I'm using ChromaControl now)

In iCue SDK rev. 14, according to include/CorsairLedIdEnum.h, there are over 1700 possible LEDs which the software can support. With a python script that looped thru all the IDs I was able to find that my motherboard works with iCue at around 1350, for instance.

Looking at the source code, it seems that ChromaControl retrieves individual devices with CorsairGetDeviceCount and CorsairGetDeviceInfo. My Corsair water cooler and headset both work with this software, however the motherboard integration does not, so I'm assuming that this extra device doesn't register with the SDK.

Instead of retrieving each device with the given functions and setting their LEDs, it might be better to loop from 1 to CLI_Last and set each LED color to the received color, modulo however many LEDs Synapse gives. This however might add significant latency, in which case a multithreaded/async method to divide all the LEDs might work out.

I'll see what I can do on my own version of the source, and if the results are good I'll submit a pull request.

**Comment by andyman1222** [comment]
Updates: The Cue SDK seems to have the individual LED setting function obsoleted, aka the code I made ended up not working. However, I built the project myself while testing and found out that Aura now works, so if anyone is having trouble getting Aura working then build the project yourself.

I started to look for ways to add Logitech support, when I stumbled on [RGB.NET](https://github.com/DarthAffe/RGB.NET). It's a NuGet package that seems to integrate multiple device SDKs into one system. It might be useful to implement ChromaControl with this package instead of individually for each SDK in the future.

**Comment by AndrewBabbitt97** [comment]
The ICUE SDK has a supported device list on their website: https://corsairofficial.github.io/cue-sdk/

I would never approve of a PR that just loops through all LEDs available in ICUE. It's super hacky and not how the SDK is intended to be used.

The SDK will always report all supported devices that work with the SDK. If motherboards we're added in a future SDK release we wouldn't have to change our code as the SDK would just return it as an additional device.

As for RGB.NET it's just an abstraction layer with more things than we need. We keep it simple: implement 3 interfaces and you're done adding a new device provider. These can be found in the abstractions project: https://github.com/ChromaControl/ChromaControl/tree/main/src/ChromaControl.Abstractions

**Comment by andyman1222** [comment]
I see that the Cue SDK will report supported devices. In the SDK motherboards should be CDT_Motherboard, and there's other types like GPUs, listed as CorsairDeviceType. I would think that my motherboard would show up in the SDK as such, however I can't seem to get any device showing up in my testing now (I think it's an issue with the SDK itself).

There are some LEDs that iCue supports but might not show up as devices, in particular "DIY devices" (CLD_C1_#...CLD_C3_#; 897 total IDs) and OEM LEDs (CLI_Oem#, 249 total IDs). It looks like DIY devices would work with Corsair's Commander Pro or Lighting Node Pro, which should show up in the SDK. The only device in the SDK I could find that might use the OEM IDs is a touchbar, so it might be that OEM LEDs exist without an SDK device. If people report issues with something like laptop lights not working, then adding a special device that manually sets the LEDS in the OEM range instead of retrieving a device might fix that.

And I understand keeping it simple, but RGB.NET has more lighting systems implemented, and works essentially the same as ChromaControl's abstractions, so I think it's worth taking a look at least to see how the APIs are implemented in that project, especially for ecosystems without an easy to find .NET package elsewhere.

**Comment by AndrewBabbitt97** [comment]
> There are some LEDs that iCue supports but might not show up as devices, in particular "DIY devices" (CLD_C1_#...CLD_C3_#; 897 total IDs) and OEM LEDs (CLI_Oem#, 249 total IDs). It looks like DIY devices would work with Corsair's Commander Pro or Lighting Node Pro, which should show up in the SDK. The only device in the SDK I could find that might use the OEM IDs is a touchbar, so it might be that OEM LEDs exist without an SDK device. If people report issues with something like laptop lights not working, then adding a special device that manually sets the LEDS in the OEM range instead of retrieving a device might fix that.

Generally haven't seen people having issues on the Corsair side besides devices not being in the SDK supported list. More issues tend to be on the Aura side not Corsair.

> And I understand keeping it simple, but RGB.NET has more lighting systems implemented, and works essentially the same as ChromaControl's abstractions, so I think it's worth taking a look at least to see how the APIs are implemented in that project, especially for ecosystems without an easy to find .NET package elsewhere.

I looked at RGB.NET when I started developing this project and opted not to use it. I have no plans to go back on this decision. RGB.NET is its own framework and it does not align with future plans for Chroma Control at this time. We prefer open SDKs over frameworks as It gives us more flexibility over implementation details.

**Comment by AndrewBabbitt97** [comment]
Topic has gone off the rails from the actual issue topic.

To summarize my perspective on the actual issue topic: We will always want to support an ASUS module as we dont want to force people to use ICUE. 

ICUE also does not support other ASUS devices (ex. Mice, Keyboards, Headsets, Laptops, Monitors, etc). Until this changes, we will continue to support both ASUS and Corsair devices as two separate modules.

Will accept PRs for new device providers, wont accept PRs that involve drastic architecture changes to existing modules (ex. migrating to RGB.NET).
