### ISSUE TITLE
Error while showing parsing app package on windows11

### ISSUE THREAD

**Issue by Jolerxx** [ChromaControl/ChromaControl#184]
I tried a lot of ways to put it, but I just can't install this program on Windows 11, hope the developer can provide some help.

**Comment by ximinjie** [comment]
Open ChromaControl with text tool and download the url in it individually
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x86_Microsoft.UI.Xaml.2.6.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x64_Microsoft.UI.Xaml.2.6.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x86_Microsoft.NET.Native.Framework.2.2.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x64_Microsoft.NET.Native.Framework.2.2.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x86_Microsoft.NET.Native.Runtime.2.2.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x64_Microsoft.NET.Native.Runtime.2.2.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x64_Microsoft.VCLibs.x64.14.00.appx
https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/x86_Microsoft.VCLibs.x86.14.00.appx
Finally run ChromaControl_0.1.4.0_x86_x64.msixbundle

**Comment by AndrewBabbitt97** [comment]
Will be resolved in the upcoming release, were getting rid of MSIX.
