### ISSUE TITLE
Asus Chroma Control Does not Work With Latest SDK Update

### ISSUE THREAD

**Issue by gent00** [ChromaControl/ChromaControl#185]
Asus Chroma Control Does not Work With Latest SDK Update

**Comment by fabiomagnoni** [comment]
I'm having the same problem now

**Comment by Bucklew** [comment]
Thanks, also having the same problem. No download link for the old Asus SDK....

**Comment by Bucklew** [comment]
Found a Workaround, simply reinstall the ArmoryCrate (maybe reinstall the current one before) from here:

https://www.asus.com/supportonly/Armoury%20Crate/HelpDesk_Download/

Afterwards ChromaControl works again.

**Comment by AndrewBabbitt97** [comment]
We only support the use of the latest SDK and HALs. These can always be fetched through the updates panel inside of Armory Crate as well.

You should also try to keep your bios up to date as well, there are aura firmware components that get delivered as a part of bios updates that can cause the SDK to stop working.

**Comment by gent00** [comment]
Thanks. Reinstalling ARMORY does the trick.
