### ISSUE TITLE
Chroma controll is not showing up in synapse 3

### ISSUE THREAD

**Issue by LolproYT** [ChromaControl/ChromaControl#186]
I downloaded chroma controll? and its not showing up in razer synapse 3? but it showing up in iCUE

**Comment by Hotpepere** [comment]
hello
check if you don't have a sour razer update and if chroma connect is greyed out or visible or not
uninstall and reinstall chroma control and if you still don't see it:
- uninstall chroma control
- uninstall razer chroma
 - reinstall the latest version of razer chroma
 - reinstall chroma control
all steps require a restart between each step
good luck

**Comment by bsiebold** [comment]
hello, 
i have done all the steps and i still can not control my asus motherboard. the only thing that is coming up is my keyboard. When i go to open Chroma Control, the window flashes open and then nothing happens. Please help

**Comment by AndrewBabbitt97** [comment]
> hello, 
> i have done all the steps and i still can not control my asus motherboard. the only thing that is coming up is my keyboard. When i go to open Chroma Control, the window flashes open and then nothing happens. Please help

Windows build number?

**Comment by bsiebold** [comment]
> > hello,
> > i have done all the steps and i still can not control my asus motherboard. the only thing that is coming up is my keyboard. When i go to open Chroma Control, the window flashes open and then nothing happens. Please help
> 
> Windows build number?

Windows 10 build 19044.2130

**Comment by AndrewBabbitt97** [comment]
Turn on debug mode and get me screenshots of the ASUS window after a restart
