### ISSUE TITLE
Chroma Control Can't Control My Graphics Card's RGB

### ISSUE THREAD

**Issue by Koophear** [ChromaControl/ChromaControl#188]
I have asus rog strix z390-f motherboard with asus rog strix rtx2060 graphics card. The RGB of motherboard works fine with the razer synapse, but the graphics card doesn't. The graphics card can be controlled with asus aura with no problem. When I started the pc while chroma control is in debug mode, I saw that the chroma control didn't started the RGB of my graphics card. What might be a problem and how can I solve it.
The debug console can be seen in the picture.

![1665364875914725266524964528261](https://user-images.githubusercontent.com/98094335/194788566-24a79a9f-9849-4503-813d-44a1447026fa.jpg)

**Comment by AndrewBabbitt97** [comment]
This is a duplicate issue of #178 please revert your GPU driver to 512.95. Closing this issue, please be sure to always check existing issues before opening new ones.
