### ISSUE TITLE
Nvidia Driver probleme -> armorycrate -> chroma control

### ISSUE THREAD

**Issue by Hotpepere** [ChromaControl/ChromaControl#189]
Hi Andrew
I have some problems with the identification of my gpu on Chroma control
It's a rog strix gtx1080ti and I think it comes from the nvidia driver.
It was doing various tests that I realized.
Do you have contacts at nvidia or information about it?
see
https://github.com/ChromaControl/ChromaControl/issues/178#issuecomment-1275670243
thank you in advance

**Comment by AndrewBabbitt97** [comment]
No contacts, there is no need to open a new thread to ask that.

This is an ASUS and NVidia issue, I have no way of addressing it myself.
