### ISSUE TITLE
Can not control ASUS TUF GeForce RTX 4090

### ISSUE THREAD

**Issue by jmartensson** [ChromaControl/ChromaControl#191]
I have enabled ASUS and it shows up in Synapse but nothing happens when I try to change the colors.

ASUS ROG STRIX X670E-F GAMING WIFI
ASUS TUF GeForce RTX 4090 24GB Gaming

I can change colors for the GÅU in Armoury Crate

**Comment by vishalchaudhary** [comment]
I can confirm the same behaviour with ASUS ROG STRIX 4090 and MSI MPG Z790 Carbon WIFI MB

**Comment by AndrewBabbitt97** [comment]
Duplicate of #178
