### ISSUE TITLE
Don't see Chroma Control- Asus or Connected Devices under Synapse Dashboard

### ISSUE THREAD

**Issue by JirachiBoi** [ChromaControl/ChromaControl#193]
I am using Armoury Crate and have Aura Sync compatible devices. I installed Chroma Control and selected Asus Enabled in the application. However, integration with Synapse 3 did not seem to activate. How do I fix this?

**Comment by AndrewBabbitt97** [comment]
Turn on debug mode, restart, then provide the output of the console window after its been open for more than a minute or two.

**Comment by AndrewBabbitt97** [comment]
Stale issue.
