### ISSUE TITLE
Installation error 0.1.4.0

### ISSUE THREAD

**Issue by fabiomagnoni** [ChromaControl/ChromaControl#194]
I reset my PC and now installing Chroma Control, it's taking forever to install and then says it failed to install. I don't remember it took forever like this before.

App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from:  (ChromaControl_0.1.4.0_x86_x64.msixbundle)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)

**Comment by AOUG** [comment]
I just also reset ym PC and cant install either but error differs slightly

App installation failed with error message: error 0x80072EFD: Opening the package from location x86_Microsoft.UI.Xaml.2.6.appx failed. (0x80072efd)

**Comment by Paslik19** [comment]
I have the same situation: Failed to install the program. Error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from: (ChromaControl_0.1.4.0_x86_x64.msixbundle) failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)

**Comment by AndrewBabbitt97** [comment]
Try manual install here: https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/ChromaControl_0.1.4.0_x86_x64.msixbundle

**Comment by AndrewBabbitt97** [comment]
Will also be resolved in the upcoming release.
