### ISSUE TITLE
Possible PC freeze while playing Battlefield 2042

### ISSUE THREAD

**Issue by fabiomagnoni** [ChromaControl/ChromaControl#195]
I'm facing PC freeze while playing Battlefield 2042, I was using Windows 11 Insider Program beta version, so I decided to reset my PC for stable release, installed all drivers and then I only installed the game, so far so good... then I started to install everything I use and after each install / pc restart I tested the game to try to find what would cause the issue... the freeze came back after I installed Chroma Control, if I stop the process after the pc boots, it also prevents the game from freezing, I strongly believe it's Chroma Control causing this problem, any advise to make sure this is the root of the problem I'm facing?

**Comment by AndrewBabbitt97** [comment]
Could be anti cheat causing issues, Chroma Control doesnt integrate with games so there is nothing it can do to freeze games. This is likely a Battlefield / anti cheat issue not a Chroma Control issue. There is nothing I can do to fix something like this. All I can recommend is bringing it up to the devs / disabling CC while you play.

**Comment by AndrewBabbitt97** [comment]
Closing issue as there's no way to resolve it in the Chroma Control code base.
