### ISSUE TITLE
pc freeze and reboot when playing APEX legends

### ISSUE THREAD

**Issue by shelby-z** [ChromaControl/ChromaControl#197]
windows10 21H2
install chroma control for two days, keep freezing and reboot when opening APEX.
with rog B450i motherboard and amd5600x CPU and amd 5700GPU
seems have Kernel Power 41 problem

**Comment by shelby-z** [comment]
power of pc is from corsair and have 600w, so the kernel power 41 problem seems no reason

**Comment by AndrewBabbitt97** [comment]
Dont play APEX, would need someone to comment if they are able to repro the issue. Even if they do, its not technically an issue with Chroma Control but likely APEX itself.

**Comment by AndrewBabbitt97** [comment]
Closing as issue is not inside of Chroma Control.
