### ISSUE TITLE
Icue control not showing up under Synapse

### ISSUE THREAD

**Issue by KyleStilkey** [ChromaControl/ChromaControl#2]
Not sure what the issue is, but my Corsair keyboard is not showing up under Synapse, I'm not sure if this is due to a recent update to ICue software or something else. ICue knows the device is being used by another third party controller but Synapse doesn't show any connected devices like it does on my personal rig at home with ASUS Sync software.

**Comment by AndrewBabbitt97** [comment]
This is something I have been investigating and working with the software team at Razer.

This has to do with Synapse, I'll keep this issue updated as I find out more.

**Comment by KyleStilkey** [comment]
Is there any update on this? Due to having to reinstall my system setup, I've lost all ability to even control my ASUS devices as I once was able to. Would be great to know what the current update is for this.

Thanks!

**Comment by sda13es** [comment]
Hi, I don't know what is the problem, but nothing appear in my sypnapse 3.0 to allow me to control Asus Mobo or Gpu.
Asus z270 maximus hero ix
Rog strix 1080 ti
Asus aura installed
ChromaControl.Aura.exe running, but nothing different than before
what i do bad??

**Comment by Infosecgamer** [comment]
Hi Andrew, wasn't sure if you had any updates in regards to the progress with the icue control panel not showing up within the synapse software? Also thank you so much for taking the time to develop this amazing software!!! Seriously! The community owes you!!! -Jude Hoffmann :)

**Comment by AndrewBabbitt97** [comment]
Sorry guys, I have been going through the process of getting a new job.

I'm investigating and will hopefully have a resolution in the next week.

**Comment by KyleStilkey** [comment]
Yeah no problem, I can understand. If you need any help do let me know and I can test anything you might need assistance with. Looking forward to when you have the chance to take a look at this again.

**Comment by cbellmyer** [comment]
Logs provided by the application don't reveal anything particularly insightful, so I have started to dig a little deeper into Windows Event Viewer to extract entries that are relevant to the icue and aura applications not appearing in synapse (I have found some and just need to parse/clear out irrelevant information). I'll update this post with relevant excerpts for @AndrewBabbitt97 ; however, if anyone else following this would like to help, I'll help pull together an entry in the wiki on how to obtain relevant logs for cross-referencing and debugging.

**Comment by OAlienado** [comment]
Hello, guys! @AndrewBabbitt97 @cbellmyer any updates? Thank you!

**Comment by MarshallYTHD** [comment]
if it is of any help his AuraConnect still works with the current version of aura and synapse but the one in this repo doesn't I had to uninstall it to get my aura synced again, it could be that his standalone ICUE sync also works? just an idea.

**Comment by cbellmyer** [comment]
> Hello, guys! @AndrewBabbitt97 @cbellmyer any updates? Thank you!

I'm sorry about not getting back sooner, some other stuff needed my attention at the time. After reinstalling ChromaControl, I replicated the issue again and was able to harvest logs from Event Viewer. There are three logs in particular that are relevant: a .NET Runtime log, an Application Error log, and a Windows Error Reporting log. They come in threes and I collated them into 1 text file while also including the log from ChromaControl. 

If some volunteers wouldn't mind, adding your error logs can help figure out if these are related or separate issues (and if so, we should break them up into separate issues for tracking and triage). 

It's a little late at the writing of this, but I have it down on my todo list to include expanding the wiki to have a walkthrough on how to grab this information from Event Viewer and help volunteers look for what could be relevant. I'm hoping to have it written up and ready by the end of the weekend. 

[chromacontrol.txt](https://github.com/ChromaControl/ChromaControl/files/4705082/chromacontrol.txt)
[ChromaControl.Cue.log](https://github.com/ChromaControl/ChromaControl/files/4705083/ChromaControl.Cue.log)

**Comment by Fayreon** [comment]
@cbellmyer The only log I'm seeing is 
[ChromaControl.Cue.log](https://github.com/ChromaControl/ChromaControl/files/4766316/ChromaControl.Cue.log)

Any update on that wiki page? I'd love for this program to work.

**Comment by kekegt** [comment]
I don't know if this could be relevant but the log file at C:\Program Files (x86)\Razer Chroma SDK\logs has a bunch of errors...
They are all like this : [2020-06-24 20:19:48][Error][APIChromaSDK] Error opening file! (2)

And a bunch of info lines like this : [2020-06-25 08:18:34][Info]千慭瑲楬桧楴杮敄楶散慍慮敧㩲䤺楮t | START
And like this [2020-06-24 20:19:57][Info]千慭瑲楬桧楴杮敄楶散慍慮敧㩲唺䥮楮t千慭瑲楬桧楴杮敄楶散慍慮敧㩲䄺摤敄楶散 | END | Result = 0

**Comment by AndrewBabbitt97** [comment]
RzChromaBtoadcastAPI.Net is going to be rewritten soon to hopefully gain some performance improvements.

I am rebuilding my PC over the next few weeks with new hardware. There's been issues with Aura and other stuff that's been blocking me from looking at much (Asus & MS broke stuff) so until then just hang tight.

**Comment by AndrewBabbitt97** [comment]
Reached out to Razer a bit ago to get some things I need on the development side, will be re-writing the Razer part of the code base as soon as they get back to me.

I will probably work the corsair part this weekend, looking at some hardware not sure if Dominator Platinum RGB will be supported, doesnt look like its responding to SDK commands. Also Hydro X hardware is not supported in their SDK right now. If your hardware isnt supported by their SDK the best way to get that pushed is to reach out to them. They recently opened a github project for their SDK and theres an open issue relating to SP Pro fans, QL fans, and Hydro X: https://github.com/CorsairOfficial/cue-sdk/issues/1

Best way to get more hardware in is to make your voice heard.

**Comment by OAlienado** [comment]
Thanks for the reply @AndrewBabbitt97 ! How about the Corsair Vengeance Pro RGB memories? They get buggy sometimes, with that infamous red triangle on iCue that shows up when they decide not to answer to software untill we force update they firmware...

**Comment by AndrewBabbitt97** [comment]
That's a corsair issue unfortunately, nothing I can do about that. That's up to them to fix it, consider bringing it up on their forum

**Comment by OAlienado** [comment]
People complain about that a lot there in their foruns... it's been an issue for years. I know it's beyond your powers, just worried that they might not work with your code, since you spoke about the Dominator ones...

Anyway thank you for your great work! AuraConnect is a masterpiece and I hope this one will be too

**Comment by SenseiMunchkin** [comment]
Is this fixed yet? I'm getting the exact issue.

**Comment by HumanGamer** [comment]
Check my recent issue https://github.com/ChromaControl/ChromaControl/issues/9 for a way to fix this in the meantime, assuming you know how to compile it yourself.

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
