### ISSUE TITLE
Software doesn't change RGB of my Corsair H100iGTX

### ISSUE THREAD

**Issue by larsy1995** [ChromaControl/ChromaControl#20]
So I got pretty much everything working except my watercooler, which will only stay the colour I set before enabling the SDK. 
From what I see in the log, it doesn't seem to find my watercooler at all, even though it is clearly in the devices section of iCUE. 
[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/5934060/Corsair.log)

**Comment by AndrewBabbitt97** [comment]
Which water cooler model?

**Comment by larsy1995** [comment]
> Which water cooler model?

It’s an H100i GTX.

**Comment by AndrewBabbitt97** [comment]
Can you link me to Corsairs page on it? I'm not seeing an RGB h100i GTX.

**Comment by larsy1995** [comment]
https://www.corsair.com/us/en/Categories/Products/Liquid-Cooling/Hydro-Series%E2%84%A2-H100i-GTX-Extreme-Performance-Liquid-CPU-Cooler/p/CW-9060021-WW

**Comment by larsy1995** [comment]
The logo in the centre of the CPU part is RGB.

**Comment by AndrewBabbitt97** [comment]
Doesn't look like it's supported in the [iCUE SDK](https://corsairofficial.github.io/cue-sdk/). Meaning there's no way for Chroma Control to control the device. Other coolers are supported, this is however an order cooler (around 6 years old now). I'm really surprised they still sell it, probably for low budget builds.

**Comment by larsy1995** [comment]
Ah, okay, that makes sense. I thought it might have been a bug since I could control it through the iCue system itself. 
Thanks for checking it out, though.
