### ISSUE TITLE
Syncs but doesn't...

### ISSUE THREAD

**Issue by DayRj** [ChromaControl/ChromaControl#21]
I had the Aura sync working and could change my Aura settings through synapse, but before I found the product that also links my corsair products, I was fiddling with different software that I have since uninstalled, but both before and after I uninstalled it, the aura settings had been unavailable to me through synapse. I uninstalled the ICUE software, the synapse software and re-installed the armory crate for aura settings, then installed the Chroma control software, however I can't see/access any of the other products/light settings in the synapse studio. When I went to ICUE software and attempted to turn my keyboard lights on, it told me, "lightings are exclusively controlled by a third party application." So in some way it is being recognized.... is there a synapse setting to accept third party lighting through your software? Have I missed something?

**Comment by AndrewBabbitt97** [comment]
You have che chroma connect module installed correct?

**Comment by AndrewBabbitt97** [comment]
Also need logs:

%localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs
%localappdata%\Packages\ChromaControl.Corsair_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs
