### ISSUE TITLE
Chroma Control - ASUS Showing in Razer Synapse, not changing lights

### ISSUE THREAD

**Issue by npjames** [ChromaControl/ChromaControl#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello. I am currently having an issue where when running Chroma Control, I can see the ASUS in Chroma Studio, but changing the lights does nothing, instead it defaults to the setting in Armoury Crate. I have tried reinstalling armoury crate, but I still get the same issue. I don't have Aura Creator installed either. (Debug Window results below). Only ASUS component is the ROG Delta and the Razer component is the Viper Ultimate. Running on Windows 10.

I have tried to find an issue in the existing issues like this, but I have not been able to find any solution that has worked for me so far.

![Debug_Window](https://user-images.githubusercontent.com/90289682/218322058-fe2f9bfc-9ce7-40c7-9284-f3a934189629.PNG)

**Comment by AndrewBabbitt97** [comment]
This is an armory crate issue / issue with your install. Or you have conflicting software that's overriding CCs ability to control your hardware. Reinstall armory crate and try again, otherwise I will ask that you attempt on a clean windows install with only Armory Crate, Chroma control, And Synapse installed to test.

**Comment by npjames** [comment]
Figured I could provide an update. Got my ROG Strix Scope NX TKL Moonlight White in the mail today, and that has no problem syncing up with chroma studio. Appears to be just the headset. I still haven't tried the clean windows install you recommended

**Comment by AndrewBabbitt97** [comment]
We don't differentiate between device types.

Given one device works and one doesn't, this is an external issue with Armory Crate / AURA. You will need to reach out to ASUS for support with that.
