### ISSUE TITLE
Color does not sync with Corsair Dark Core SE

### ISSUE THREAD

**Issue by camonlybruh** [ChromaControl/ChromaControl#22]
I tried you're earliest version of corsair plugin and it syncs the fans and k95 keyboard but leaves the color off on the Dark Core SE

**Comment by AndrewBabbitt97** [comment]
Its not supported by the Corsair iCUE SDK: https://forum.corsair.com/v3/showthread.php?t=199337

Corsair maintains that, so will have to wait on them for support.

**Comment by camonlybruh** [comment]
I do not have the pro version though. I have the standard SE version.

**Comment by AndrewBabbitt97** [comment]
AFAIK none of the Dark Core mice are supported through the SDK. None of the models are on the supported devices list: https://corsairofficial.github.io/cue-sdk/#supported-devices
