### ISSUE TITLE
NZXT implementation

### ISSUE THREAD

**Issue by Onisaku** [ChromaControl/ChromaControl#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

.

### Describe the solution you'd like

Hello , it would be great to see NZXT 's rgb also implemented , which often create sync problems with other programs , thanks for your fantastic work .

### Additional context

.

**Comment by AndrewBabbitt97** [comment]
Already accounted for in #94
