### ISSUE TITLE
Chroma control not starting after reboot, asus integration always disabled

### ISSUE THREAD

**Issue by des22059** [ChromaControl/ChromaControl#224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I installed asus aura and chroma control, everything working fine until I restart my pc. The chroma control is not launching and if I do that manually, asus toggle is always off. Debug mode stays on even after restart. I tried to enable startup for Chroma Control - Asus in the task manager but it's always disabled(!) after reboot. No errors in the logs

Windows: 10.0.19045 Build 19045
Motherboard: ROG STRIX Z690-I GAMING WIFI
Synapse: 3.8.209.20311
Asus Aura: 1.07.84_v2 (previously worked a year~ ago like that)

### Version number

preview

**Comment by AndrewBabbitt97** [comment]
Windows issue, will be resolved in the next release.

**Comment by des22059** [comment]
Found old sources for asus connect, built exe, created windows service and set it to start automatically. Works perfectly

**Comment by AndrewBabbitt97** [comment]
Running as a windows service isn't supported by synapse (thus the reason we dont do it anymore). Bear in mind the old version is not supported, as such you cannot get support on anything relating to the old version.

**Comment by des22059** [comment]
But it works on my side. I am pretty much sure that I completely uninstalled last version and right now it's only asus connect itself. I can control it in synapse flawlessly

**Comment by AndrewBabbitt97** [comment]
It may work, but Razer has explicitly asked me not to do so which is why it was changed.

**Comment by des22059** [comment]
Waiting for new version 🥺

**Comment by aftBINKO** [comment]
> Found old sources for asus connect, built exe, created windows service and set it to start automatically. Works perfectly

I'm having the same issue. Can you please tell me which sources you used to create exe?

**Comment by andrewbabbittdev** [comment]
> > Found old sources for asus connect, built exe, created windows service and set it to start automatically. Works perfectly
> 
> I'm having the same issue. Can you please tell me which sources you used to create exe?

Current main branch is based on OpenRGB, I'd suggest building that or you can find a build in our discord development channel pins.

I'll ask that you refrain from sharing / asking for the files for it the Chroma Control communities; as we were explicitly asked by Razer to replace some portions of the code because they used ASUS's integration code. We also generally don't want people using it and asking for support with it.
