### ISSUE TITLE
Document iCUE Configurations When Using ASUS Motherboard

### ISSUE THREAD

**Issue by smjkh** [ChromaControl/ChromaControl#23]
Hi, I used this to connect my ASUS motherboard and Corsair Vengeance RGB RAM but for some reason having this program installed causes the lights on the RAM to simply go out.  If I uninstall the program I regain control and they come back which is odd.  ASUS component works great, only having this issue with Corsair RAM.  The Corsair module shows up in Synapse under Chroma Connect devices but disabling that in Synapse doesn't turn the lighting back on and no settings in Synapse control the lighting/turn it back on.  iCUE shows the RAM as being controlled by a third party. 
![iCUE](https://user-images.githubusercontent.com/78837411/107464426-424de180-6b2e-11eb-952b-321caa58c08f.PNG)
![Chroma Connect](https://user-images.githubusercontent.com/78837411/107464453-4f6ad080-6b2e-11eb-8584-fab8f35c42a8.png)

**Comment by heavyoak** [comment]
I was having this same issue with stick 4, it was dark while the rest were lit. I crashed corsair chroma and the stick lit up.

**Comment by AndrewBabbitt97** [comment]
Issue is Corsair startup time. Ill have a configuration to edit startup delay in the future.

**Comment by TMM10** [comment]
im having an issue where my ram sticks are just blue. i think that was the color they were previously before setting up ChromaControl. ive tried restarting and killing icue and its still not allowing me to change them from blue. my corsair coller and asus mobo lighting sync fine though. im only having the issue with ram

**Comment by smjkh** [comment]
> I'm having an issue where my ram sticks are just blue. i think that was the color they were previously before setting up ChromaControl. ive tried restarting and killing icue and its still not allowing me to change them from blue. my corsair cooler and asus mobo lighting sync fine though. I'm only having the issue with ram
> 
> EDIT: I found that enabling "full software control" for the ram in icue fixed this issue.

It seems for my RAM I never had this option and on the newer versions of iCue it's not an option (seems like it's just enabled by default from what I can find).  I have Software & Game integrations both enabled.  Not sure if it's any help but under "Active Clients" it does list Chroma Control and says "Not supported" under "Events Access."

**Comment by AndrewBabbitt97** [comment]
Closing, as this is no longer relevant with OpenRGB.
