### ISSUE TITLE
EVGA Precision X1 Support

### ISSUE THREAD

**Issue by five710** [ChromaControl/ChromaControl#231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to sync my EVGA gpu with the rest of my system but there's no support

### Describe the solution you'd like

I would like to see EVGA Precision X1 added to chroma control to be able to sync evga cards

### Additional context

Precision X1 has rgb control just no way to sync it to razer synapse, just would like to be able to sync Precision X1

**Comment by AndrewBabbitt97** [comment]
Already tracked in #94.
