### ISSUE TITLE
Installation Hangs 27% on Asus Flow x16

### ISSUE THREAD

**Issue by devast8tor** [ChromaControl/ChromaControl#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from:  (ChromaControl_0.1.4.0_x86_x64.msixbundle)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)

### Expected behavior

Installation succeeded.

### Steps to reproduce

1) Launch Installer

### Version number

0.1.4.0

**Comment by AndrewBabbitt97** [comment]
Resolved by using the full bundle here: https://github.com/ChromaControl/ChromaControl/releases/download/0.1.4/ChromaControl_0.1.4.0_x86_x64.msixbundle

Otherwise we have a new installer coming in the next release.
