### ISSUE TITLE
Corsair keyboard goes blank after sleep/locking PC.

### ISSUE THREAD

**Issue by mannylouey2013** [ChromaControl/ChromaControl#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Upon locking my PC (or my PC going to sleep), my Corsair Keyboard no longer syncs with Razer Chroma. Here's what happens:
Upon locking my PC, the keyboard switches to it's 'Hardware lighting' setting, an rgb setting it reverts to when it can't contact iCue (for example, when in BIOS).
Upon unlocking my PC, the keyboard will just go dark. Switching Chroma Connect off and on from Razer Synapse, switching 'Corsair Enabled' off and on does not make a difference - when these settings are on, the device will stay dark. 

Only solution is to restart the PC.
I should note that my Razer Mouse is lit and the RGB behaves as normal there.

Keyboard is Corsair K65 Lux.

### Expected behavior

Upon waking the device, the keyboard's RGB should resume operation as normal - ie, being in sync with Razer chroma.

### Steps to reproduce

Allow your computer to fall asleep, or use windows + L to lock your device.
This is with a Corsair device.

### Version number

0.1.4

### Anything else?

Windows 10 22H2

Please advise if you require any further information.

**Comment by AndrewBabbitt97** [comment]
Should be resolved at the same time as #37

Closing in favor of that issue.
