### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by gamefreak2993** [ChromaControl/ChromaControl#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've tried installing the app but the installer gets stuck at `80%` and then fails:
![image](https://user-images.githubusercontent.com/8652332/230051693-cfeb8ad8-e222-4937-a348-37af32c4082e.png)

Error message:
```
App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from:  (ChromaControl_0.1.4.0_x86_x64.msixbundle)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)
```

Razer Synapse `v3.8.330.32816`
Armoury Crate `v5.4.10.0`

Armoury Crate Devices:
![image](https://user-images.githubusercontent.com/8652332/230052203-4c18939d-74e1-4253-90e0-4f71cc9657ac.png)

### Expected behavior

Installer finishes installing the app

### Steps to reproduce

1. Download installer from https://chromacontrol.github.io/
2. Execute installer
3. Notice installer gets stuck at 80%
4. Notice installer fails with error message:
```
App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from:  (ChromaControl_0.1.4.0_x86_x64.msixbundle)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)
```

### Exceptions or error messages (if any)

App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from:  (ChromaControl_0.1.4.0_x86_x64.msixbundle)  failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)

### Version number

Razer Synapse v3.8.330.32816, Armoury Crate v5.4.10.0

**Comment by gamefreak2993** [comment]
I've also tried installing straight after a cold boot without Razer Synapse closed but this time the installer got stuck at 57% for around 20 minutes until I stopped it. No error message.

**Comment by AndrewBabbitt97** [comment]
Download the MSIX from the releases page, otherwise wait for the new release this upcoming weekend.
