### ISSUE TITLE
Razer shutdown when doing things too fast

### ISSUE THREAD

**Issue by dchance284** [ChromaControl/ChromaControl#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

So, pretty niche issue - but when I switch the lighting effects too fast, everything just shuts off.  This happens to me when I am playing games that have lighting effects with razer, mostly Overwatch when I'm switching characters.  Actual razer devices will turn back on and sync but everything running through asus or icue just stays dark.  Annoying little bug to have because it will mess up pretty much everything running through synapse, like turning off my mouse and keyboard for about 30 seconds, which isn't fun when playing a fast paced comp game.

### Steps to reproduce

If you have overwatch - get in a game, pick a character, die, and then before you respawn pick another character.

**Comment by AndrewBabbitt97** [comment]
Not sure I have seen this issue, will try to repro soon.

**Comment by AndrewBabbitt97** [comment]
I was unable to repro this issue
