### ISSUE TITLE
Install duration: Hours not minutes for initall\ install

### ISSUE THREAD

**Issue by ash0a573** [ChromaControl/ChromaControl#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue: Install as admin or run as admin or run as standard user all have the same result.  I had this issue on my laptop and dismissed it at the time. New install on new PC same issue.  When I install the ChromaControl.appinstaller the progress is slow, hours slow to complete.  The install appears to hang at 27%

### Expected behavior

For the size of the app and the requirements are met. I would expect an installer to take minutes at best, not hours.

### Steps to reproduce

Download App -> https://chromacontrol.github.io/download/preview
Open Explorer
Right Click File -> Properties -> Unblock
Right click file -> Run As Administrator (tried as admin, run as admin, run as standard user
App checks dependencies; passes check, install begins
App reaches 27% and hangs.

I reboot, disable startup apps, try again, same result, repeat.... 

### Exceptions or error messages (if any)

None

### Version number

0.1.4.0

### Anything else?

Windows 11 Pro Workstation
AMD Ryzen 9 CPU 
64GB ram
All updates applies to all apps and OS
Malwarebytes Premium
AdGuard
Unifi DM SW
Starlink
Me <- Probable issue

**Comment by AndrewBabbitt97** [comment]
Not something we address. This is something specific to some PCs/environments and we have no control over it. Its something with the way Windows is downloading files.

Use the manual downloads from the releases page instead of the app installer if you run into issues. App installer is going away in a future release.

**Comment by ash0a573** [comment]
yep....PBEAK. resolved, content filter on gateway flagged it is naughty.
