### ISSUE TITLE
GPU Aura doesn't sync up

### ISSUE THREAD

**Issue by Misuku** [ChromaControl/ChromaControl#265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello,
i have a TUF-RTX4070TI-12G which doesn't work with Chroma. When i just use Aura Sync it works fine and is in sync with my motherboard. Now i activate Chroma and link it to Synapse. Now my motherboard is in sync with Synapse but my gpu stays in the same blue color. First i thought it was a problem because of the effect i was useing but even when i change to static green f.e. it stays in the blue color. I tried the Debug mode and it did nothing.

### Expected behavior

The gup to sync up with Synapse and Chroma

### Version number

Chroma 0.1.4 Armoury Crate 5.6.3.0

**Comment by AndrewBabbitt97** [comment]
We dont control the specifics of devices working. If your ASUS motherboard works but your GPU doesnt its an issue with Armory Crate / AURA and not Chroma Control. Only other thing it could be is #178
