### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by nitanmarcel** [ChromaControl/ChromaControl#27]
Hi!

It doesn't seem to work for me, I've tried changing every settings I could but with no success.

The only way I can still change the effects are from Armory Crate software and any change done from Razer Synapse doesn't change anything.

I'm using an Assus TUF Laptop (XF505DT) and maybe it's not compatible with it?

![image](https://user-images.githubusercontent.com/41646249/108626638-d76ba700-7459-11eb-9bca-1db54cb913e3.png)

**Comment by AndrewBabbitt97** [comment]
Laptops are not directly supported by me. They are on a "If it works cool, if not sorry you are out of luck"

This software is intended for desktops, laptops are notorious for not working with the Aura SDK so there's nothing I can really do about them.
