### ISSUE TITLE
So I dont know but its not working

### ISSUE THREAD

**Issue by EliasRyker** [ChromaControl/ChromaControl#28]
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6032925/ASUS.log)

I can get synapse to see the Chroma Control - ASUS but I cant make it work, plus, it stucks at unreachable

![Captura](https://user-images.githubusercontent.com/79552087/108938343-ae503f80-762e-11eb-903d-90b9056e6bcd.PNG)

**Comment by AndrewBabbitt97** [comment]
If still not working, restart your full PC. There will be a full guide on issues like this in the future. Other things to consider include reinstalling Synapse fully. Also make sure you don't have AuraConnect installed anymore.

Your logs tell me it's connecting and working fine. This could be something else on your computer causing a disconnect between ChromaControl and Synapse.

**Comment by EliasRyker** [comment]
Ok, I restarted my PC and it still didnt worked so I tried reinstalling everything but it remained unreachable. AuraConnect is uninstalled completly and now I dont have a log file anymore, I dont know about that tho.

If anything comes to mind its very much appreciated

**Comment by AndrewBabbitt97** [comment]
This seems PC specific. There's a ton of things that could be causing this, so its really hard to track down :(

**Comment by AndrewBabbitt97** [comment]
After all reinstalls still need logs from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by EliasRyker** [comment]
Hey, no need for that. This worked just fine for me: uninstall everything, armourycrate, chromaconnect/control, razer synapse. Make sure windows is up to date, restart your pc. Reinstall everything in the following order
-Chroma Control
-ArmouryCrate
-Razer Synapse 3

Go to studio and everything should be there

You can close the issue now. Ty!

**Comment by AndrewBabbitt97** [comment]
For future reference, Chroma Control should always be installed after ICUE/Armory Crate and Synapse as it depends on files installed by both.

This will be documented in the future.
