### ISSUE TITLE
Not showing up in Synapse 

### ISSUE THREAD

**Issue by lazerem** [ChromaControl/ChromaControl#29]
Installed the Chroma Control app for Corsair products. Installer finishes but I do not see Chroma Control listed under devices.

**Comment by AndrewBabbitt97** [comment]
Chroma connect module installed?

**Comment by AndrewBabbitt97** [comment]
Also logs
%localappdata%\Packages\ChromaControl.Corsair_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by lazerem** [comment]
> Chroma connect module installed?

Yes, I can see Chroma connect but I only see MSI Mystic Light, Chroma Control isn't there.

**Comment by AndrewBabbitt97** [comment]
Again, still need your log files %localappdata%\Packages\ChromaControl.Corsair_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by lazerem** [comment]
> Again, still need your log files %localappdata%\Packages\ChromaControl.Corsair_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs
I have some log files but nothing with that name/location. I didn't see Chroma Control in the local app data folder, searched for Chroma Control on my drive and the logs are in ProgramDate/ChromaControl. None of the file names have Corsair either but I do see one that is ChromaControlCue.log.

**Comment by AndrewBabbitt97** [comment]
Uninstall that version, it's unsupported.

Install the MSIX beta: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

**Comment by muhdbs86** [comment]
Hi Andrew, the CC Asus is not running on my comp.

IT's stuck at "2021-03-15T23:50:32.5331751+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit..."

As for Corsair, it's working.

[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6142699/ASUS.log)
[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6142703/Corsair.log)

**Comment by AndrewBabbitt97** [comment]
> Hi Andrew, the CC Asus is not running on my comp.
> 
> IT's stuck at "2021-03-15T23:50:32.5331751+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit..."
> 
> As for Corsair, it's working.
> 
> [ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6142699/ASUS.log)
> [Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6142703/Corsair.log)
> 
> 

This indicates a problem with your armory crate/Aura install. Either LightingService isn't running or the Aura API isn't accessable.

**Comment by muhdbs86** [comment]
> > Hi Andrew, the CC Asus is not running on my comp.
> > IT's stuck at "2021-03-15T23:50:32.5331751+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit..."
> > As for Corsair, it's working.
> > [ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6142699/ASUS.log)
> > [Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6142703/Corsair.log)
> 
> This indicates a problem with your armory crate/Aura install. Either LightingService isn't running or the Aura API isn't accessable.

Should i uninstall Armoury Crate, then just install standalone Aura Sync and reinstall your Asus?

**Comment by whitefox935** [comment]
Hi,

same problem here. Corsair Chroma Control is running fine but ASUS Chroma Control is stucked:

2021-03-24T22:17:40.5637952+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2021-03-24T22:17:40.5673401+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2021-03-24T22:17:40.5673673+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus
2021-03-24T22:17:41.5692856+01:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing Chroma Control - ASUS...
2021-03-24T22:17:42.5757221+01:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit...

Armoury Crate Service is running and I'm able to control the LEDs with Armoury Crate. Lightnig Service is running too.

Any idea?

**Comment by muhdbs86** [comment]
> Hi,
> 
> 
> 
> same problem here. Corsair Chroma Control is running fine but ASUS Chroma Control is stucked:
> 
> 
> 
> 2021-03-24T22:17:40.5637952+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
> 
> 2021-03-24T22:17:40.5673401+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
> 
> 2021-03-24T22:17:40.5673673+01:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus
> 
> 2021-03-24T22:17:41.5692856+01:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing Chroma Control - ASUS...
> 
> 2021-03-24T22:17:42.5757221+01:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit...
> 
> 
> 
> Armoury Crate Service is running and I'm able to control the LEDs with Armoury Crate. Lightnig Service is running too.
> 
> 
> 
> Any idea?

For me, I had to reformat my system as there's too much junk in it and my asus module doesn't work. I then clean instaled everything. And Asus module works. 😅

**Comment by whitefox935** [comment]
> For me, I had to reformat my system as there's too much junk in it and my asus module doesn't work. I then clean instaled everything. And Asus module works. 😅

No... No, no, no, that was NOT the answer I wanted to hear :-D But thanks for the reply, I'll try to clean up my system or reinstall it...

**Comment by muhdbs86** [comment]
> > For me, I had to reformat my system as there's too much junk in it and my asus module doesn't work. I then clean instaled everything. And Asus module works. 😅
> 
> No... No, no, no, that was NOT the answer I wanted to hear :-D But thanks for the reply, I'll try to clean up my system or reinstall it... 

The problem u have, is the same as mine at first. Asus module was not to communicate with Synapse. I tried many ways but failed. The last resort I did was to clean install it by reformatting my system. And it worked.

**Comment by whitefox935** [comment]
> 
> 
> > > For me, I had to reformat my system as there's too much junk in it and my asus module doesn't work. I then clean instaled everything. And Asus module works. 😅
> > 
> > 
> > No... No, no, no, that was NOT the answer I wanted to hear :-D But thanks for the reply, I'll try to clean up my system or reinstall it...
> 
> The problem u have, is the same as mine at first. Asus module was not able to communicate with Synapse. I tried many ways but failed. The last resort I did was to clean install it by reformatting my system. And it worked.

Worked with Aura Connect until one of the last Razer updates broke it. As System Engineer I know that a clean uninstall is sometimes the best way... Thanks, that will work, I am sure.

**Comment by AndrewBabbitt97** [comment]
Please also be aware of #46

**Comment by whitefox935** [comment]
Thanks, seems like it is / was a bug in Razer Synapse software. Got an update today and Chroma Control is working now - it is still a little bit unstable and crashes some times with an unhandled exception in the Razer API. But that seems to be a Razer issue.

**Comment by AndrewBabbitt97** [comment]
I would like the details on this exception if possible, I work with the Razer devs so can help sort out issues like that.

**Comment by whitefox935** [comment]
Hi Andrew, thanks, it is not working anymore. I've reinstalled Synapse, ASUS Aroury Crate, iCUE and CHroma Control incl. cleaning the Synapse Registry Keys. I had a conversation at Razer Insider. He told me that the Razer Devs will check it now. I've allready shared many logs and got a ticket now with a big to do list I will check today. If you are working with the Razer Devs and they are sharing information with you, the ticket number 210401-000781 might help you. If you wil not get all informations I will share it with you directly.

**Comment by whitefox935** [comment]
I've some good news! I don't know if there was an update for Razer Synapse (in Germany) within the last 48 hours but since today Chroma Control for ASUS is running again!

The following things I've done:
- Installed an update for ASUS HAL Central (to version 20210309 from 2021/04/08) in Armoury Crate
- Reinstalled Razer Synapse and all Apps (without deleting reg keys, files and directories)
- Reinstalled Chroma Connect for ASUS
- Reboot of the PC

After the reboot Chroma Control for ASUS appeared in Synapse and I were able to configure it in Chroma Studio.

I will watch it within the next days and give you another feedback, if it's not running stable or stopps working.

**Comment by whitefox935** [comment]
Today Chroma control for ASUS is no longer working. Yesterday everthing was fine and today it's showing up as "not connected" in Chroma Studio. Did only shut down the PC yesterday evening and started it up again today. Did not see or install any updates today. The log does only show "Initializing RGBKit...". Tried to disable / enable the "device" in Chroma Connect, disabled / enabled Chroma Connect App, restarted Chroma Control for ASUS and restarted the PC again. Still "not connected"...
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6291428/ASUS.log)

**Comment by whitefox935** [comment]
I have another update again. It seems like the problem today was the connection between ASUS Aura and iCUE for Corsair RAM. With the old version auf Aura Connect I had to install a iCUE plugin to connect iCUE with ASUS Aura. Synapse was only able to control the RAM via ASUS Aura API / connection. I’ve uninstalled the iCUE plugin for ASUS Aura now, reinstalled the Chroma Control for ASUS and after a reboot the ASUS Aura integration is running again - the RAM is connected now with Chroma Control for Corsair. 

I will have a look to it within the next days and give you a feedback.

**Comment by whitefox935** [comment]
Today, again not working... Nothing changed... A restart of the app or services does not help, restart of the PC does not help... Again, the log does only show "Initializing RGBKit...".... Frustrating, it worked for two days now.

**Comment by AndrewBabbitt97** [comment]
> Today, again not working... Nothing changed... A restart of the app or services does not help, restart of the PC does not help... Again, the log does only show "Initializing RGBKit...".... Frustrating, it worked for two days now. 

Have been seeing this myself, it's an AURA issue.

Go to your task manager and close Chroma Control, then kill Lighting Service.

Restart lighting service from the services tab in the task manager. Wait a few minutes for it to start then open Chroma Control.

**Comment by whitefox935** [comment]
Unfortunately, did not help. First time waited until LED "animation" started (about one minute) and next times gave it some more minutes (5/10/15). Still not connected and "Initializing RGBKit..." in the log file. LightnigService.log did not show an error message and Armoury Crate is working correctly.

Anything else I could check or test? Any logs I could have a look into?

**Comment by whitefox935** [comment]
Got the answer now, that Razer does not support 3rd party products - after about two or three weeks of communikation, sending logs, testing and loosing MUCH of time... Thank you, Andrew, for your software and your answer and I wich you much luck in future! Because of all the problem with Razer (stucked keys, analogue sticks, HUE not working anymore, ASUS not working anymore) I will sell or trash all my Razer devices and will never ever by one again... The Razer software is absolutely trash at the moment and the support ist a mess...

**Comment by AndrewBabbitt97** [comment]
3rd party integrations have never been directly supported through Razer. That's why its called 3rd party.

Sorry to hear you have been having problems with Razer software/hardware. Software bugs are normal in any piece of software, you will find them in any software based lighting ecosystem. There are many factors that can cause them to occur, the biggest one being your own Windows install/software on your PC. 

I can confirm that the latest version of Synapse does work (both the Hue and Connected Devices module). This issue you are having with the ASUS devices is a AURA bug, so the fault lies with ASUS. Their SDK is notoriously buggy and there's not much we can do about it besides hope that ASUS fixes it.

As for HUE, there's a lot that can cause issues including your own network and configuration with your HUE bridges. Beyond the scope of this, but I have also never had an issue with the HUE module over the past 2 years.

I wish you the best of luck with any ecosystem you decide to move to next.
