### ISSUE TITLE
  重点词汇 4/5000 传统翻译模型 通用场景 Debug window

### ISSUE THREAD

**Issue by 916157030** [ChromaControl/ChromaControl#294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello, why is the light not synchronized after I open the software? I need to open the debugging button. After the debugging of the lamp belt is completed, the light can be synchronized, but the debugging window cannot be closed, and the light will not be synchronized after closing.

### Version number

0.1.4

### Anything else?

![image](https://github.com/ChromaControl/ChromaControl/assets/68717935/dc2ec18b-2d92-49d6-ae5c-0c5fa5a25a2a)

**Comment by AndrewBabbitt97** [comment]
Turn off debug mode, restart and it will run in the background. Closing the debug window kills the process. Debug mode just means the process runs in the foreground instead of the background.
