### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by Astrikal** [ChromaControl/ChromaControl#3]
I installed the program, but it doesn't seem to work. I dont see a Corsair entry in Razer connect.

**Comment by OAlienado** [comment]
Same thing with me. Corsair goes into SDK mode, but does not show up in Synapse.

**Comment by cbellmyer** [comment]
Duplicate of #2

**Comment by Invicia** [comment]
Same for me, Aura goes to standby mode but it won't show any modified modules on my chroma studio. i cant find logs since its not even stored in the files perhaps

**Comment by crscaballero** [comment]
Same situation here

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
