### ISSUE TITLE
Chroma connect show "unreachable"

### ISSUE THREAD

**Issue by bai7675** [ChromaControl/ChromaControl#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey, Im having issue where sypnase show "unreachable". I believed this happened just after i updated armoury crate app, might be conflict rgb software controller or something. It works perfectly fine just before update the armoury crate. I have checked the debug log seems chroma control working fine but it actually didnt work, I spent 2 hours checking on armoury crate but cant solve the problem. Hopes reader or dev can help me solve this issue because ive seen this app kind good but its getting abandoned.

### Expected behavior

Synapse able to bypass armoury crate every startup

### Steps to reproduce

Update everything in armoury crate & maybe try play with colors effect available on armoury crate then it will block synapse control forever.

### Version number

Latest

**Comment by AndrewBabbitt97** [comment]
Turn on debug mode, restart, after console window shows up wait a few mins and post screenshot

**Comment by bai7675** [comment]
The steps you mentioned above didn't even help. Here's how I resolved the issue:

1. Uninstall Synapse.
2. Uninstall Chroma Control.
3. Uninstall Armoury Crate.
4. Restart the PC.
5. Install Synapse and Chroma Control, followed by Armoury Crate (make sure to uncheck Aura Creator during installation).

Please don't interact with the Armoury Crate RGB settings once you have successfully installed Armoury Crate. I have no idea what I'm doing, but everything goes back to normal after following these steps. I suggest developer look into and debug the relationship between Asus Aura and Synapse. They should develop something that can run and fix the issue instantly. 

ps: Anyway thank you for replying me, you rocks man👍🏻
