### ISSUE TITLE
Opening a CMD Window thats never closing

### ISSUE THREAD

**Issue by Andrevanhouten** [ChromaControl/ChromaControl#314]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When starting the PC, a CMD Window "ChromaControl.Asus" is opening. Seems like it is loading all the needed Modules.
the Link with Razer works, when it says 

info: ChromaControl.Hosting.ModuleService[0]
      Initializing Chroma Control - Asus v0.1.4...
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Device Provider...
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS0 - 5 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS1 - 5 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: WallPaper - 17 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Vga 1 - 4 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Mainboard_Master - 5 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 1 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Razer Chroma Broadcast SDK...
info: ChromaControl.Hosting.ModuleService[0]
      Chroma Control - Asus Started Succesfully!
info: ChromaControl.Hosting.ModuleService[0]
      Razer Chroma Broadcast API Connected

which is taking a lot of time.
and then, the window never closes. when i close the window manually, the link with the Razer synapse stops working.

### Expected behavior

when the CMD finished loading, it should close the window and the link with razer synapse should work.

### Version number

0.1.4

### Anything else?

Windows 11

**Comment by AndrewBabbitt97** [comment]
This is the debug mode window, turn off debug mode then restart and the window goes away.
