### ISSUE TITLE
app pny velocityX

### ISSUE THREAD

**Issue by Jaoznn** [ChromaControl/ChromaControl#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I'm trying to sync the rgb of my pny xlr8 gpu

### Describe the solution you'd like

add velocity app to chroma control

### Additional context

rtx 4060 ti xlr8 pny

**Comment by AndrewBabbitt97** [comment]
Covered in #94
