### ISSUE TITLE
RGB Not Working

### ISSUE THREAD

**Issue by Winomatics** [ChromaControl/ChromaControl#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Asus Strix z790 - E wifi i motherboard logo is stuck and the Lian Li evo 11 Led strip is stuck. The graphics card and RAM are working perfectly. I uninstalled the asus chroma control and the armoury crate and yet no result. Everything is updated to its latest drivers.

![PC](https://github.com/user-attachments/assets/51fda4cc-bb8e-40b9-bff1-75ac265b5570)

**Comment by AndrewBabbitt97** [comment]
First Grab the `Armoury Crate Uninstall Tool` from here: https://www.asus.com/supportonly/armoury%20crate/helpdesk_download/

Once Armory Crate is fully uninstalled, restart your PC.

Next use the `Armoury Crate Full Installation Package` from here: https://www.asus.com/supportonly/armoury%20crate/helpdesk_download/

**DO NOT UPDATE ARMORY CRATE AFTER THIS OR CHROMA CONTROL WILL NOT WORK**

Current Armory Crate updates are broken.

After install, restart your PC.

With Chroma Control installed and the ASUS module on, head over to Armory Crate and move the Chroma Control item up the priority list:

![mceclip3](https://github.com/user-attachments/assets/a1cd074b-d386-4969-8b3f-05dd36eaeaf3)

![image](https://github.com/user-attachments/assets/143d5b5b-cc72-4af7-9425-a4a69c5486e6)

After doing so, restart again. It should work upon coming back on. If not, please share a screenshot of your Synapse `Connect` tab.

**Comment by AndrewBabbitt97** [comment]
Also if you want more active support, please join the Chroma Control Discord community here: https://discord.gg/6xGy7cycrt

**Comment by AndrewBabbitt97** [comment]
Closing as the Armory Crate integration is being removed soon in favor of OpenRGB.

Others have figured out issues with Armory Crate and have workarounds in the discord server listed above, if you need further support until the next release please ask there.
