### ISSUE TITLE
Don’t know how to setup

### ISSUE THREAD

**Issue by Yajur28** [ChromaControl/ChromaControl#33]
I was using your auraconnect app until recently it stopped working. I opened an issue and you replied by saying auraconnect has been replaced by chromacontrol. But I have absolutely no idea on how to setup this. Can you please help.

**Comment by AndrewBabbitt97** [comment]
Download here https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

Just open the msixbundle of the manufacturer you want to install

**Comment by NewbieOKS** [comment]
Btw you mentioned "This also applies if you have AuraConnect, you must uninstall before using it. 

Just want to understand, does AuraConnect = Aura Sync in Asus Armoury Crate software ? So in order to install the msixbundle, do i need to uninstall the Asus Armoury Crate first from my PC?

**Comment by AndrewBabbitt97** [comment]
AuraConnect is my previous project, you cannot have AuraConnect and ChromaControl installed at the same time.

**Comment by NewbieOKS** [comment]
Ah ya gotcha, thanks for the clarification..

**Comment by Yajur28** [comment]
I deleted aura connect uninstalled everything related to that. But still after using chroma control. After restarting my pc aswell. It has the same issue. It recognised the app plugin in razer synapse. But when I actually change the colours. No change takes place. This was previously due to a problem I suspected when I was going through the task manger, in the services tab, aura connect was stopped. It wasn't starting. It was just stopped. It wasn't restating aswell. The same thing is happening with chroma control. Aura connect in services is stopped and I can't run it. Is that the root of my problem? If it is. Please provide a fix

**Comment by NewbieOKS** [comment]
I have some comments after I installed Chroma Control (I never installed Aura Connect before)..the program works as charm so the rgb devices in my PC follow the Chroma/Razer Synapse option/configuration as the main base rgb configuration

However, when I tried to disabling the Asus sync devices option/configuration in Razer Synapse (Chroma Connect tab) in order to go back using the rgb lighting options in Aura Sync (in Armoury Crate), I found out that the colour of my rgb devices were not properly respond/run as I intended to see/use (as in the Aura Sync option/configuration)

therefore I uninstall Chroma Control, restart my PC and try using back the Aura sync module in Armoury Crate and the rgb devices properly respond back as usual...

**Comment by AndrewBabbitt97** [comment]
That switch in Synapse just makes it so Synapse stops accepting requests from the Razer Broadcast API (which ChromaControl uses).

If for whatever reason you want to control your RGB from Armory Crate again you can either uninstall the program or disable the startup item for it in the task manager:

![startup](https://user-images.githubusercontent.com/2308261/110371218-e7fb5000-8009-11eb-934d-e3a3337da85e.png)

**Comment by Pruizcoder** [comment]
Hi, I really apprecaite what you are doing for the community, but I have an issue, i already did the setup and it's running, I can see my asus device in the studio but it won't sync, with an "unreachable" text on the device, is it only me or it happened to someone else? I have an asus rog x470f motherboard btw

**Comment by AndrewBabbitt97** [comment]
> Hi, I really apprecaite what you are doing for the community, but I have an issue, i already did the setup and it's running, I can see my asus device in the studio but it won't sync, with an "unreachable" text on the device, is it only me or it happened to someone else? I have an asus rog x470f motherboard btw

Need logs %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by EliasRyker** [comment]
If anything works, try what I did. Uninstall everything, ChromaConnect, ArmouryCrate, And RazerSynapse3. Reboot to clean everything. Install everything in the following order: ArmouryCrate, RazerSynapse3 and then ChromaConnect. Reboot and go to studio. It should do the trick

**Comment by KrispySkywalker** [comment]
Hey man, I can't seem to find an .exe file for me to run in order to install it? I hope you can help me on how to install it. Thank you!

**Comment by AndrewBabbitt97** [comment]
> Hey man, I can't seem to find an .exe file for me to run in order to install it? I hope you can help me on how to install it. Thank you!

Was my first reply on this thread: https://github.com/ChromaControl/ChromaControl/issues/33#issuecomment-792374814

Installers are no longer exe files, I have swapped to msix which is signed by me. They are installed by opening them normally in windows 10.

In the future there will be a website where you just click a button and it will prompt you to install it.

**Comment by KrispySkywalker** [comment]
What program/app is used to open them though? Coz I don't know, please bear with me not really knowledgeable with Github bro. Thank you

**Comment by AndrewBabbitt97** [comment]
msixbundle files are native windows 10 install files, they open with an app that comes with windows 10 called App Installer: https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1?activetab=pivot:overviewtab

They are the replacement for MSI/EXE installers.

**Comment by KrispySkywalker** [comment]
GOT IT! THANKS SO MUCH MY MAN! <3

**Comment by Revanchist522** [comment]
Thank you so much works like a charm, one question, are you planning to integrate ASRock Polychrome Sync as well, I have ASRock RX6900XT and Id like to sync it with the rest. I know polychrome already supports razer chroma but the specific version that works with my GPU PolychromeSYNC(v1.0.18) doesn't have the RazerChroma tab for some reason.

**Comment by nupetunesfault** [comment]
Hello. i cant get the chromecontrol app to startup in win10. just getting a generic 1001 error. 
Version=1
EventType=MoAppCrash
EventTime=132668990786353560
ReportType=2
Consent=1
UploadTime=132668994100902065
ReportStatus=100
ReportIdentifier=8b6f2e12-654e-49b8-8f39-0da78860107a
IntegratorReportIdentifier=5ea22558-419b-4947-8110-5682ee985a3f
Wow64Host=34404
NsAppName=praid:App
OriginalFilename=ChromaControl.Asus.dll
AppSessionGuid=00003b78-0001-004d-b5ca-5884be55d701
TargetAppId=U:ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg!App
TargetAppVer=1.0.0.0_x64_!2020//12//12:03:44:18!0!ChromaControl.Asus.exe
BootId=4294967295
TargetAsId=426
IsFatal=1
EtwNonCollectReason=1
Response.type=4
Sig[0].Name=Package Full Name
Sig[0].Value=ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg
Sig[1].Name=Application Name
Sig[1].Value=praid:App
Sig[2].Name=Application Version
Sig[2].Value=1.0.0.0
Sig[3].Name=Application Timestamp
Sig[3].Value=5fd43c92
Sig[4].Name=Fault Module Name
Sig[4].Value=KERNELBASE.dll
Sig[5].Name=Fault Module Version
Sig[5].Value=10.0.19041.964
Sig[6].Name=Fault Module Timestamp
Sig[6].Value=812662a7
Sig[7].Name=Exception Code
Sig[7].Value=e0434352
Sig[8].Name=Exception Offset
Sig[8].Value=0000000000034b89
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.19042.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=8b56
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=8b5647d43e584ad46cfb1279ae922981
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=2a41
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=2a4188068c04be948ab8bb0a33b8c5aa
UI[2]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe
LoadedModule[0]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\System32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\System32\USER32.dll
LoadedModule[5]=C:\Windows\System32\win32u.dll
LoadedModule[6]=C:\Windows\System32\GDI32.dll
LoadedModule[7]=C:\Windows\System32\gdi32full.dll
LoadedModule[8]=C:\Windows\System32\msvcp_win.dll
LoadedModule[9]=C:\Windows\System32\ucrtbase.dll
LoadedModule[10]=C:\Windows\System32\SHELL32.dll
LoadedModule[11]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[12]=C:\Windows\System32\msvcrt.dll
LoadedModule[13]=C:\Windows\System32\sechost.dll
LoadedModule[14]=C:\Windows\System32\RPCRT4.dll
LoadedModule[15]=C:\Windows\System32\IMM32.DLL
LoadedModule[16]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\hostfxr.dll
LoadedModule[17]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\hostpolicy.dll
LoadedModule[18]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\coreclr.dll
LoadedModule[19]=C:\Windows\System32\ole32.dll
LoadedModule[20]=C:\Windows\System32\combase.dll
LoadedModule[21]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[22]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[23]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Private.CoreLib.dll
LoadedModule[24]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\clrjit.dll
LoadedModule[25]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[26]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.dll
LoadedModule[27]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Runtime.dll
LoadedModule[28]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Windows.SDK.NET.dll
LoadedModule[29]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Runtime.InteropServices.dll
LoadedModule[30]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\WinRT.Runtime.dll
LoadedModule[31]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Collections.Concurrent.dll
LoadedModule[32]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Collections.dll
LoadedModule[33]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Threading.dll
LoadedModule[34]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Shared.dll
LoadedModule[35]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\netstandard.dll
LoadedModule[36]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Extensions.Hosting.Abstractions.dll
LoadedModule[37]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\RGBKit.Core.dll
LoadedModule[38]=C:\Windows\System32\clbcatq.dll
LoadedModule[39]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Runtime.CompilerServices.Unsafe.dll
LoadedModule[40]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Private.Uri.dll
LoadedModule[41]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.ObjectModel.dll
LoadedModule[42]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.ComponentModel.dll
LoadedModule[43]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Numerics.Vectors.dll
LoadedModule[44]=C:\Windows\SYSTEM32\icu.dll
LoadedModule[45]=C:\Windows\System32\Windows.ApplicationModel.dll
LoadedModule[46]=C:\Windows\System32\shcore.dll
LoadedModule[47]=C:\Windows\System32\twinapi.appcore.dll
LoadedModule[48]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Linq.dll
LoadedModule[49]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Memory.dll
LoadedModule[50]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Linq.Expressions.dll
LoadedModule[51]=C:\Windows\System32\BCrypt.dll
LoadedModule[52]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Security.Cryptography.Algorithms.dll
LoadedModule[53]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Security.Cryptography.Primitives.dll
LoadedModule[54]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Security.Cryptography.Csp.dll
LoadedModule[55]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Reflection.Emit.ILGeneration.dll
LoadedModule[56]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Reflection.Primitives.dll
LoadedModule[57]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Reflection.Emit.Lightweight.dll
LoadedModule[58]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Reflection.Emit.dll
LoadedModule[59]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.IO.FileSystem.dll
LoadedModule[60]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Extensions.Hosting.dll
LoadedModule[61]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Extensions.Logging.dll
LoadedModule[62]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Extensions.DependencyInjection.Abstractions.dll
LoadedModule[63]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[64]=C:\Windows\SYSTEM32\Wldp.dll
LoadedModule[65]=C:\Windows\System32\shlwapi.dll
LoadedModule[66]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Extensions.Configuration.Abstractions.dll
LoadedModule[67]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.Extensions.DependencyInjection.dll
LoadedModule[68]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.ComponentModel.TypeConverter.dll
LoadedModule[69]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.ComponentModel.Primitives.dll
LoadedModule[70]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\RGBKit.Providers.Aura.dll
LoadedModule[71]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[72]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\Microsoft.DiaSymReader.Native.amd64.dll
LoadedModule[73]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Diagnostics.StackTrace.dll
LoadedModule[74]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Reflection.Metadata.dll
LoadedModule[75]=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\System.Collections.Immutable.dll
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19042
OsInfo[3].Key=ubr
OsInfo[3].Value=985
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1033
OsInfo[7].Key=geoid
OsInfo[7].Value=244
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221112280
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.789.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32682
OsInfo[19].Key=svolsz
OsInfo[19].Value=465
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.985.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=FX:117B9872,FX:1183210E,FX:119E26AD,FX:11A8C293,FX:11A8C2FE,FX:11C0E96C,FX:11C3F9D5,FX:11C6E5C2,FX:11C7EB6A,FX:11C9408A,FX:11C940DB,FX:11C96C7A,FX:11CB9A9F,FX:11CB9AC1,FX:11CC111C,FX:11D5BFCD,FX:11D898D7,FX:11DB147C,FX:11DE505A,FX:11E11E97,FX:1DF5B12
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
File[0].CabName=WERInternalMetadata.xml
File[0].Path=WER85FF.tmp.WERInternalMetadata.xml
File[0].Flags=327682
File[0].Type=5
File[0].Original.Path=\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER85FF.tmp.WERInternalMetadata.xml
FriendlyEventName=Stopped working
ConsentKey=MoAppCrash
AppName=ChromaControl.Asus
AppPath=C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=29CE052BE012295E6808973FACADFF7E
MetadataHash=-1980033415

**Comment by bpritchard213** [comment]
I was using AsusConnect until the ChromaControl came out now I get this error on every start:  
c:\\programfiles\windowsapps\chormacontrol.asus_1.0.0.0_x64_846pf09jn2...\chromacontrol.asus.exe   

Incorrect Function

![image](https://user-images.githubusercontent.com/7834665/137526290-69ea985b-eb1e-4974-bd83-36866c832466.png)
I tried removing Both programs as you stated they can't be installed together.

**Comment by Equinox90002** [comment]
Hey is there any other way to link my ROG lc 240 cooler and other fans to razer synapse? Aura connect doesnt have a setup anymore+I cant find a way to run it.

**Comment by VisalbunKH** [comment]
My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too.
![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)

Please Help me! thanks!

**Comment by swappy242** [comment]
> My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too. ![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)
> 
> Please Help me! thanks!

having the same problem, everything works as long as this window is open, does anybody know how to work around, did your problem got solved, Thank you

**Comment by lipxxs** [comment]
> > My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too. ![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)
> > Please Help me! thanks!
> 
> having the same problem, everything works as long as this window is open, does anybody know how to work around, did your problem got solved, Thank you

having same problem too, does anybody can help? Thanks a lot

**Comment by lipxxs** [comment]
> > My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too. ![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)
> > Please Help me! thanks!
> 
> having the same problem, everything works as long as this window is open, does anybody know how to work around, did your problem got solved, Thank you

hey, just found how to solve this problem. U can trun off the debug mode switch in ChromaControl and this window will not show up again.

**Comment by lipxxs** [comment]
> > My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too. ![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)
> > Please Help me! thanks!
> 
> having the same problem, everything works as long as this window is open, does anybody know how to work around, did your problem got solved, Thank you

u can turn off the debug mode switch in ChromaControl and this window will not show up again

**Comment by lipxxs** [comment]
> My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too. ![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)
> 
> Please Help me! thanks!

turn off the debug mode switch.

**Comment by swappy242** [comment]
> > My ChromaControl.Asus is working well with RGB control and Connected with synapse, but why did ChromaControl.Asus window still pop up? and when i closed the ChromaControl's window the device can't connect to Synapse too. ![Capture](https://user-images.githubusercontent.com/98613882/151653217-fed9a06c-a94d-4e8d-a861-55091567953d.JPG)
> > Please Help me! thanks!
> 
> turn off the debug mode switch.

Hey lipxxs thanks for the advice, but there is a tiny bit problem. i dont know where the debug mode switch would be, if you could please drop a screenshot where i can find the debug switch that would be mighty generous of you. Thank you

**Comment by AndrewBabbitt97** [comment]
Its in the chroma control ui right under where you enable ASUS / corsair.
