### ISSUE TITLE
에러뜹니다. 

### ISSUE THREAD

**Issue by Pink-angel-wing** [ChromaControl/ChromaControl#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

windows부팅시 asus chroma error
![스크린샷 2024-09-16 060656](https://github.com/user-attachments/assets/6b87056c-9b60-45cd-90b3-a707ca5f3df0)
![스크린샷 2024-09-16 060656](https://github.com/user-attachments/assets/bb0bcb42-6eeb-45e8-a15b-7a503aa9a07a)

**Comment by AndrewBabbitt97** [comment]
This is machine specific, perhaps locale.

This wont be resolved on existing builds, try the dev build in Discord instead.
