### ISSUE TITLE
Support Logitech G-hub

### ISSUE THREAD

**Issue by NeoCooler** [ChromaControl/ChromaControl#35]
Hi,
Thanks for your hard work !!

Do you thinks it possible to use this tool to import logitech devices.

SDK from logitech:
https://www.logitechg.com/sdk/LED_SDK_9.00.zip

I can be beta tester for u if u need it for logitech,
i've:
-G502 Hero
-G910
-G933

I use ChromaControl to sync:
-Rog-Strix_RTX2060S
-Rog Spotlight

Inside Synapse i control:
-Razer Goliathus Extended Chroma
-ChromaControl
-Yeelight: -YEELIGHT YLTD003

Everything work fine but i want my Logitech devices inside synapse for better sync/control ;-)

In advance, big thanks for your time ;-)

**Comment by NeoCooler** [comment]
> Logitech should be doable. I don't imagine I'll be able to get around to it until I finish moving at the end of the month however.
> 
> Want to look at adding other manufacturers starting next month.

Nice, you rock !!!

And do u think it possible to get a option to control all devices alone but in synapse, because now when u add
Aura sync i  get one trigger in synapse, but i've two devices...

**Comment by beyondopinion** [comment]
I'm also interested in the ability to sync with G Hub and would be willing to test as well, I have a couple of Logitech devices and MSI Mystic Light.

**Comment by AndrewBabbitt97** [comment]
Closing in favor of #94
