### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by blupixlz** [ChromaControl/ChromaControl#350]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Installation Error

 After hitting the install button (in the app installer) i get an error:
"App installation failed with error message: The appinstaller uri https://github.com/ChromaControl/ChromaControl/releases/download/preview/ChromaControl.appinstaller is already being used by another package and cannot be applied to package"

### Expected behavior

Installing without error

### Steps to reproduce

Install v0.1.4.0 off github (on windows 11)

### Exceptions or error messages (if any)

App installation failed with error message: The appinstaller uri https://github.com/ChromaControl/ChromaControl/releases/download/preview/ChromaControl.appinstaller is already being used by another package and cannot be applied to package

### Version number

v0.1.4.0

### Anything else?

not admin of computer

**Comment by AndrewBabbitt97** [comment]
Seems this has been resolved in the forum over in the discord. If you need additional support continue replying to your thread there.
