### ISSUE TITLE
ChromaControl

### ISSUE THREAD

**Issue by JinxieQT** [ChromaControl/ChromaControl#4]
I cannot get Icue to show up in razer synapse 3
Please help

**Comment by SvupCity** [comment]
Im having the same issue, any fix yet? :)

**Comment by AndrewBabbitt97** [comment]
This project has mostly been on hold, things are coming soon. Merging of AuraConnect & Chroma Control. 

Just make sure you are on Windows 10 version 2004

**Comment by JinxieQT** [comment]
Cool thanks and yes that's what version I'm currently on.

**Comment by SvupCity** [comment]
Im running Windows 10 pro version 1903

> This project has mostly been on hold, things are coming soon. Merging of AuraConnect & Chroma Control.
> 
> Just make sure you are on Windows 10 version 2004

Im running Windows 10 pro version 1903

**Comment by AndrewBabbitt97** [comment]
I make no promises of using 1903, I'm evaluating features only on 2004

**Comment by SvupCity** [comment]
> I make no promises of using 1903, I'm evaluating features only on 2004

Im updating it right now, I'll let you know if it works :)

**Comment by SvupCity** [comment]
So I've updated to 2004, reinstalled both Synapse3, iCUE and Chroma Control again, but I still can't see iCUE in synapse.

**Comment by MarshallYTHD** [comment]
That’s because Andrew still developing the software, all you have to do right now is make sure you have the latest version of Windows 10 and wait. Andrew is currently busy so he can’t work 24/7 on this program, please understand and give him time to get everything wrapped up for a release.

**Comment by HumanGamer** [comment]
Check my recent issue https://github.com/ChromaControl/ChromaControl/issues/9 for a way to fix this in the meantime, assuming you know how to compile it yourself.

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
