### ISSUE TITLE
Make Enabling & Disabling Chroma Control Better

### ISSUE THREAD

**Issue by TheUKDave** [ChromaControl/ChromaControl#42]
I believe this is a feature request, although it may already be possible ...

It would be good to be able to set up a shortcut/macro/whatever to be able to disable Chroma Control without having to open Razer and toggle the switch within the app.  I cannot find a way to do this, is this currently possible?

Either that, or to have Chroma Control allow individual control over Corsair devices.

I have a rather niche use case for this, so I totally understand if it's not a priority - but I have my PC connected to monitors in 2 different rooms, one that has razer devices, and one that doesn't.  I would like to be able to sync _some_ of my corsair devices in the room that also has Razer devices, _or_ to be able to have a keyboard shortcut to turn off Chroma Control when I move between rooms.

**Comment by AndrewBabbitt97** [comment]
Switch in Synapse doesn't do anything.... Gonna try to reach out to the Chroma team to see if we can get that fixed. If we can get it fixed, then we could see if we can get the ability to toggle them through Synapse macros.

This is all gonna require coordination with the Synapse team so might be a bit. This is definitely a niche use case, generally Chroma Control is a set it and forget it thing where the goal is to enable lighting control for all of your devices through Synapse and to forget about any other RGB software.

If all the devices are supported in Chroma Control/Synapse you should be able to set a keyboard action to swap Chroma profiles no? Setting up a chroma profile that sets the devices you don't want lit to black (rgb 0,0,0) should turn them off for you or really anything you want.

**Comment by TheUKDave** [comment]
I have my (razer) keyboard/mouse/mat just set to spectrum cycle, and I want 2 Corsair devices (light towers) to match them.  The rest I don't want controlled by Razer, so yes, if I could group or control Corsair devices from within synapse, this would solve my problem.

However unless I'm missing something (very very possible), I can't see anything like that inside Synapse with ChromaControl installed.  I just see my Razer devices under 'DEVICES', and under 'CONNECTED DEVICES' there's 'Chroma Control - Corsair'.  Inside of that, I just have a toggle switch, and effect choices, no corsair devices.  So how could I set a profile that utilises only some of the corsair devices?

**Comment by AndrewBabbitt97** [comment]
In Chroma studio if you set the color of the Corsair devices to black it will turn them off, same goes for any device in Synapse:
![studio](https://user-images.githubusercontent.com/2308261/111539132-2512c100-8733-11eb-940f-db76744b3552.png)

The switch in the connect tab doesn't do anything, something I want to address with Razer just haven't had time:
![switch](https://user-images.githubusercontent.com/2308261/111539244-42478f80-8733-11eb-9ba2-c95dd5b83d4f.png)

**Comment by AndrewBabbitt97** [comment]
Theres also the ability to control lighting by changing key mappings and macros:
![macros](https://user-images.githubusercontent.com/2308261/111539487-8fc3fc80-8733-11eb-91c3-1d004ab2727b.png)

**Comment by TheUKDave** [comment]
I think I'm with you, yes.  To be honest, I've not played at all with the studio yet, I'm pretty unfamiliar, but can confirm that I can set the colour of the Chroma Control 'thing' to black, and the lights on the Corsair devices all turn off.

This isn't actually what I want however, I just wanted to disable the override that was in place, but subsequently have realised that that won't happen anyway, since 'Enable SDK' in iCue means that the default profiles there won't take over anyhow.

So the solutions for me would seem to be:

- to be able to turn off ChromaControl and have iCue take back over, and keyboard-shortcut that - seemingly impossible with 'Enable SDK' turned on in iCue
- to be able to control only _some_ of the corsair devices - again seemingly impossible since the 'Enable SDK' is global in iCue
- to be able to control individual, or groups of, Corsair devices (setting different lighting patterns for each) in Razer - massive job that I don't expect you to be implementing!
- to be able to keyboard-shortcut the enable/disable SDK setting in iCue - not your problem :D

Cheers anyway, and other than my niche user case, great job.

**Comment by AndrewBabbitt97** [comment]
Regarding your points:

1. You could probably use TASKKILL such as in #83 to toggle Chroma Control on and off through a Synapse macro.
2. Might be possible, most SDKs request exclusive control over all devices. So this may or may not be implemented due to confusion that may occur because of things only Corsair allows.
3. Limitation of the Chroma Connect API. Its something I want eventually, just not possible right now.
4. Probably possible with scripting/coding a solution to change the config setting in iCUE then using a macro to control it in Synapse. Not on my priority list at this time.

**Comment by AndrewBabbitt97** [comment]
Addressed with the MSIX releases.
