### ISSUE TITLE
ASUS "Unreachable"?

### ISSUE THREAD

**Issue by Kwyntonix** [ChromaControl/ChromaControl#44]
First off, you're doing amazing things here, and I love this project! I installed the ChromaControl, and it's showing up in my Razer Synapse. Armoury Crate can control my ram just fine, but when I go to Synapse, I can't do anything with it. There are two ASUS bubbles that show up in Chroma Studio. One is "Aura Sync, ASUS" which says Unreachable in the studio, and the other one is "Chroma Control - ASUS",and it also says "Unreachable", but neither respond. I don't have the older version "Aura Connect" installed either. Do you know how to fix this issue?

-Thank you in advance :)

**Comment by Hotpepere** [comment]
hi personal friend I have already had this phenomenon. Start by checking if in armory crate \ aura sync
 in advanced effects light illumination games is ON. if so
 Well the problem may come from the link Chroma - aura and chroma control in the middle. I will start by uninstalling chroma control go to this link to download armory crate uninstaller
https://www.asus.com/support/FAQ/1041654/
then you make a pass with the Ccleaner software and you reinstall armory crate and finally Chroma control and tell us what it gave

**Comment by AndrewBabbitt97** [comment]
A reinstall of Synapse & Chroma Control should get rid of the old Aura entries in Synapse.

Before that you can also consider doing the following if you feel comfortable deleting some registry keys:

1. Close all Razer software from running in the background
2. Open regedit
3. Navigate to ```Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Razer\ChromaBroadcast```
4. Delete the keys inside there, you should see keys such as ```Chroma Control - ASUS.exe```
5. Restart synapse and the extra devices should be gone, I have seen this fix some weird issues with Synapse communicating with Chroma Control before as well.

Ill probably make a formal tool to do this in the future as well, one of the things I'm looking to do to hopefully resolve common issues.

**Comment by bigbutler** [comment]
no beta is alpha so many broken

**Comment by AndrewBabbitt97** [comment]
> no beta is alpha so many broken

The source has been tested for around two years, the only part that was beta was the installer.

99% of all issues come from Synapse, Armory Crate, or iCUE and are pretty much always resolved with reinstalls.

I see this is your first post on my project and that you have not actually opened any issues relating to it. Constructive feedback would be appreciated more than just saying its bad. Yes I see you downvoting several issues. If you are having an issue open an issue and actually leave info.

**Comment by bigbutler** [comment]
99 percent I have to laugh a little bit. Why don't they get it here to update the codes to be released by asus and Razer 4 to 5 days in advance after update they need 2 to 3 weeks or more to improve it or even recognize the problems a codex for programming they don't know everything just half. To this a group is already to do their work a lot better nevertheless respect but they are like many others busy on many projects that also the reason why not everything runs as it could be nice evening still!

**Comment by AndrewBabbitt97** [comment]
> 99 percent I have to laugh a little bit. Why don't they get it here to update the codes to be released by asus and Razer 4 to 5 days in advance after update they need 2 to 3 weeks or more to improve it or even recognize the problems a codex for programming they don't know everything just half. To this a group is already to do their work a lot better nevertheless respect but they are like many others busy on many projects that also the reason why not everything runs as it could be nice evening still!

So first, this message isn't coherent English and so it's hard to understand what you are saying. Based off what it seems like you are trying to say; its mostly complaining and as such is off topic on this thread. If you have an issue open a new issue.

**Comment by Kwyntonix** [comment]
I think I might have done an oopsie. I went to the "keys?" in the Registry Editor, went to ChromaBroadcast, and deleted the stuff in there (I thought that's the stuff that I was supposed to delete), but now theres just one thing in there with the icon "ab" that says "(Default) REG_SZ (value not set)". I think I messed something up and I'm not sure how to fix it. Other than my own mistake, I appreciate your help a lot and you're doing great things, despite the negativity you're getting from it. Thank you a bunch!

**Comment by AndrewBabbitt97** [comment]
> I think I might have done an oopsie. I went to the "keys?" in the Registry Editor, went to ChromaBroadcast, and deleted the stuff in there (I thought that's the stuff that I was supposed to delete), but now theres just one thing in there with the icon "ab" that says "(Default) REG_SZ (value not set)". There were other things in there that said stuff like "major ver" and "minor ver", but I didn't know what any of it was. I assume it was processes that allowed the program to run it's course, now that I think about it. I think I messed something up and I'm not sure how to fix it. Other than my own mistake, I appreciate your help a lot and you're doing great things, despite the negativity you're getting from it. Thank you a bunch!

Keys look like folders in the registry editor. Inside the ```ChromaBroadcast``` key there should have been another key called ```Chroma Control - ASUS.exe``` you may have also seen ones for things like MSI, Corsair, GSkill or any other Razer Connected Devices manufacturers you use. You were only supposed to delete the folder (key) of manufacturers you wanted to clear from Synapse. 

If you deleted things you don't think you should have, you can always just uninstall all of Synapse and reinstall it and you should be back in working order.

**Comment by Kwyntonix** [comment]
Awesome! Works fine now in the quick effects column, just not the advanced effects, as I've seen some other issues being commented too. Thank you so very much!

**Comment by AndrewBabbitt97** [comment]
> Awesome! Works fine now in the quick effects column, just not the advanced effects, as I've seen some other issues being commented too. Thank you so very much! Can't wait until it works with advanced effects!

So you are saying your issue is the same as #46?

If so we will close this issue and move the conversation there. Trying to track down when people first started getting that update.

**Comment by AndrewBabbitt97** [comment]
Issue should have been solved through Synapse updates.
