### ISSUE TITLE
Mise a jour razer Chroma

### ISSUE THREAD

**Issue by Hotpepere** [ChromaControl/ChromaControl#45]
Good evening everyone, this little Chroma control works great. On the other hand, the razer update has taken place and causes little synchronization problems.
 think it's related because the razer vizualiser works niquel and the quick effects works too
The problem comes only from Chroma Studio, asus is available and accessible but impossible to add any effect and save it. Tell me if you have the same problem

**Comment by AndrewBabbitt97** [comment]
I'm on the latest version, setting effects on the "Chroma Control - ASUS" node works normally and as expected.

If you are having issues with it a reinstall of Synapse & Chroma Control may help.

**Comment by NeoCooler** [comment]
No prb with the last version for me ;-)

**Comment by Hotpepere** [comment]
Ok if its working for you the problem comes from some files lying around or from the latest version of armory crate. Can you give me yours as information that I compare to mine. Chroma control since I tried to properly installed the latest G-SKILL software ... and that's kidding besides.
On the other hand Andrew version 1.00.18 of the G-skill software presented the same default CPU consumption.Chroma Control still eats as much Cpu as will have connected but G-Skilla has previously solved the problem with their last beta version ... as soon as I manage to synchronize everything I will keep you posted. solving this cpu problem would be a huge step forward I think. thank you in advance for all your work

**Comment by AndrewBabbitt97** [comment]
> Ok if its working for you the problem comes from some files lying around or from the latest version of armory crate. Can you give me yours as information that I compare to mine. Chroma control since I tried to properly installed the latest G-SKILL software ... and that's kidding besides.
> On the other hand Andrew version 1.00.18 of the G-skill software presented the same default CPU consumption.Chroma Control still eats as much Cpu as will have connected but G-Skilla has previously solved the problem with their last beta version ... as soon as I manage to synchronize everything I will keep you posted. solving this cpu problem would be a huge step forward I think. thank you in advance for all your work

Armory Crate version isn't what matters, device HAL version is what matters but unless you have a Maximus XII Formula like me they wont match. Armory Crate isn't what's required for the software to work, its Lighting Service + your device specific HALs that allow Chroma Control to work. Armory Crate just allows you to download and update those pieces.

As for CPU usage, most CPU cycles go to calling the ASUS SDK. This isn't code I control. GSkill gets to pass doing that because they control the RAM without the ASUS SDK.

**Comment by AndrewBabbitt97** [comment]
I got this update you were referring to today. There's two threads running right now about this, lets move talk over to #46
