### ISSUE TITLE
Connected but not working in Studio

### ISSUE THREAD

**Issue by muhdbs86** [ChromaControl/ChromaControl#46]
Hi Sir,

Both the Corsair and Asus are detected. However, upon going to studio to set it up, it doesn't work.

You can refer to my logs as attached.

[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6177584/Corsair.log)
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177585/ASUS.log)

**Comment by steamwasd** [comment]
I am having the same problem. I can customize my viper ultimate, charging dock, and my ornata V2 but does not work well with aura sync. They are working properly when I use effects like spectrum cycling. But when I try to make a custom effect with studio, I can't customize chroma control.

**Comment by Inqie** [comment]
I'm having the same problem on Zephyrus Duo 15 SE with the built in RGB keyboard. Chroma Connect works with the basic effects present in Synapse, but when I go to Studio, all 4 dots on Chroma Control are black and it doesn't respond to any changes (though it is not coming up as unreachable). 

[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177721/ASUS.log)

**Comment by Inqie** [comment]
I'm having a similar problem on Zephyrus Duo 15 SE with the built in RGB keyboard. Chroma Connect (Asus) works with the basic effects present in Synapse, but when I go to Studio, all 4 dots on Chroma Control will appear black and won't respond to any changes (it is not coming up as unreachable). The only time they light up is if I create a new effect with the default Spectrum Cycling, but the second I change it, they go black and don't respond. While in Studio, my keyboard also periodically flashes red, whether or not the Spectrum Cycling is active. 

[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177769/ASUS.log)

**Comment by AndrewBabbitt97** [comment]
> Hi Sir,
> 
> Both the Corsair and Asus are detected. However, upon going to studio to set it up, it doesn't work.
> 
> You can refer to my logs as attached.
> 
> [Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6177584/Corsair.log)
> [ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177585/ASUS.log)

Logs are telling me everything is working, both the Corsair and ASUS modules detected your devices and Synapse connected to the modules successfully. Screenshots of what Chroma Studio looks like with a static color effect applied to the Corsair/ASUS nodes would be useful.

> I am having the same problem. I can customize my viper ultimate, charging dock, and my ornata V2 but does not work well with aura sync. They are working properly when I use effects like spectrum cycling. But when I try to make a custom effect with studio, I can't customize chroma control.

Need details on the custom effect you are trying to use so I can replicate.

> I'm having a similar problem on Zephyrus Duo 15 SE with the built in RGB keyboard. Chroma Connect (Asus) works with the basic effects present in Synapse, but when I go to Studio, all 4 dots on Chroma Control will appear black and won't respond to any changes (it is not coming up as unreachable). The only time they light up is if I create a new effect with the default Spectrum Cycling, but the second I change it, they go black and don't respond. While in Studio, my keyboard also periodically flashes red, whether or not the Spectrum Cycling is active.
> 
> [ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177769/ASUS.log)

Screenshot with all layers in Chroma Studio would be useful. Good results cannot be promised when using keyboards due to Synapse only supporting 4 LEDs worth of color at a time, so we can only use 4 colors sent by synapse for all keys on a keyboard.

**Comment by muhdbs86** [comment]
> > Hi Sir,
> > Both the Corsair and Asus are detected. However, upon going to studio to set it up, it doesn't work.
> > You can refer to my logs as attached.
> > [Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6177584/Corsair.log)
> > [ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177585/ASUS.log)
> 
> Logs are telling me everything is working, both the Corsair and ASUS modules detected your devices and Synapse connected to the modules successfully. Screenshots of what Chroma Studio looks like with a static color effect applied to the Corsair/ASUS nodes would be useful.
> 
> > I am having the same problem. I can customize my viper ultimate, charging dock, and my ornata V2 but does not work well with aura sync. They are working properly when I use effects like spectrum cycling. But when I try to make a custom effect with studio, I can't customize chroma control.
> 
> Need details on the custom effect you are trying to use so I can replicate.
> 
> > I'm having a similar problem on Zephyrus Duo 15 SE with the built in RGB keyboard. Chroma Connect (Asus) works with the basic effects present in Synapse, but when I go to Studio, all 4 dots on Chroma Control will appear black and won't respond to any changes (it is not coming up as unreachable). The only time they light up is if I create a new effect with the default Spectrum Cycling, but the second I change it, they go black and don't respond. While in Studio, my keyboard also periodically flashes red, whether or not the Spectrum Cycling is active.
> > [ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6177769/ASUS.log)
> 
> Screenshot with all layers in Chroma Studio would be useful. Good results cannot be promised when using keyboards due to Synapse only supporting 4 LEDs worth of color at a time, so we can only use 4 colors sent by synapse for all keys on a keyboard.

Hi Sir,

Currently I’m at work and will be back 14hrs later as of this reply. Just to let u know, in Studio, I have 
A) razer keyboard
B) razer mousepad
C) both chromacontrol

When using standard wave or spectrum rgb settings, it all links up and working. However in Studio, I tried all effects, only (A&B) will be syncing up and not (C).

(C) has been showing black color on the dots for both no matter how many times it was selected together over and over again. Even tried to reset it back to default.

**Comment by AndrewBabbitt97** [comment]
Just got an update to Synapse today, I can replicate this. Issue looks to be a bug in the latest update. Reaching out to Synapse devs for this one.

**Comment by AndrewBabbitt97** [comment]
![effects](https://user-images.githubusercontent.com/2308261/111928402-1d2b8780-8a79-11eb-8b71-f61926db82b0.png)
Of note you can use quick effects fine right now, just not advanced effects. I will keep this thread updated as I hear back from Razer.

**Comment by muhdbs86** [comment]
> ![effects](https://user-images.githubusercontent.com/2308261/111928402-1d2b8780-8a79-11eb-8b71-f61926db82b0.png)
> 
> Of note you can use quick effects fine right now, just not advanced effects. I will keep this thread updated as I hear back from Razer.

Yes Sir, this is what happened. Will wait for your updates.

**Comment by Inqie** [comment]
> Screenshot with all layers in Chroma Studio would be useful. Good results cannot be promised when using keyboards due to Synapse only supporting 4 LEDs worth of color at a time, so we can only use 4 colors sent by synapse for all keys on a keyboard.

Well that sucks. I'm assuming that is just a limitation of Chroma Connect and Razer's APIs. Wish there was some way to trick Synapse into thinking it was sending to a Razer KB but translate it for Asus :/ Oh well. 

Not sure screenshots will help at all in this situation, but here. I'm glad you reached out to Synapse though, hopefully this can be resolved :)
[Static](https://i.imgur.com/IzMXxsq.png), [Spectrum](https://i.imgur.com/X0sDUoV.png)

**Comment by AndrewBabbitt97** [comment]
> > Screenshot with all layers in Chroma Studio would be useful. Good results cannot be promised when using keyboards due to Synapse only supporting 4 LEDs worth of color at a time, so we can only use 4 colors sent by synapse for all keys on a keyboard.
> 
> Well that sucks. I'm assuming that is just a limitation of Chroma Connect and Razer's APIs. Wish there was some way to trick Synapse into thinking it was sending to a Razer KB but translate it for Asus :/ Oh well. 
> 
> Not sure screenshots will help at all in this situation, but here. I'm glad you reached out to Synapse though, hopefully this can be resolved :)
> [Static](https://i.imgur.com/IzMXxsq.png), [Spectrum](https://i.imgur.com/X0sDUoV.png)

Screenshots are no longer needed. Thanks though :)

And yes the LED limitation is a Razer Broadcast API limitation. I have requested more from the dev teams at Razer it's just not a current priority/on their roadmap. Believe me if a better way to do this comes out I will implement it ASAP.

**Comment by Hotpepere** [comment]
> Just got an update to Synapse today, I can replicate this. Issue looks to be a bug in the latest update. Reaching out to Synapse devs for this one.


Well, it's okay then, reassures me that you find the same problem as us and for my part I was almost sure that it came from the synapse update ... we had the same problem with a previous update day and aura connect.Sa resolved itself with the next synapse update to follow.

**Comment by WyRmiE** [comment]
+1 same issues. basic works for me as well

thanks for keeping this updated even after 2 years, you are GOD

**Comment by rubilacxe95** [comment]
+1 on the issues. finally found you after using your program now. Thank you for your work it has made my life so much easier.

**Comment by AndrewBabbitt97** [comment]
Synapse release that fixes this is being planned for release in the next few weeks.

I will let you all know as soon as I hear word of the update going live.

**Comment by ElguishexD** [comment]
Hi good sir, first at all I apologize for my bad english...
I guess I have the same problem as muhdbs86...
 
I have a corsair vengeance rgb pro and asus tuf b 550... I can control the RGB througt the armory crate app, but nothing happend on razer synapse 3... I have chroma control

**Comment by muhdbs86** [comment]
@AndrewBabbitt97 received update for Synapse. Currently all working now.

![IMG_20210328_231701.jpg](https://user-images.githubusercontent.com/33008026/112757290-b92a3580-901b-11eb-8317-c4d7fe99bf2e.jpg)

**Comment by ElguishexD** [comment]
![Sin título](https://user-images.githubusercontent.com/81433453/112785495-1aed9e00-9022-11eb-868b-00b3ba92d818.jpg)
same here,

**Comment by ElguishexD** [comment]
![Sin título](https://user-images.githubusercontent.com/81433453/112785659-859ed980-9022-11eb-83a8-592824ab701c.jpg)
Same here!!!

**Comment by nodiaque** [comment]
If you got something else playing with the RGB, it will stop the plugin. I myself have only the Aura Service (no armory crate, no aura sync) and it's working. I also have openrgb and I found out that if I send a specific mode with openrgb to my asus device, Razer chroma won't work with asus. The way to make it work again, I disable in chroma connect, start openrgb and select direct mode. This turn off the led then enable razer chroma, bang, working again.

Samething happen with iCUE for corsair. Once installed, iCUe with SDK enabled, ram is 100% control by Razer.

Problem I myself have is they all , either corsair or asus, show only 5 LED. My Asus board have 6 onboard, 2 RGB header and 1 ARGB header supporting 120 led. In OpenRGB, I can control all LED thus it's possible to do so.

**Comment by qandres12** [comment]
Had recently set up chroma control with my razer products and asus motherboard. Today Synapse updated by itself, really annoying, and it made it so advanced effects wouldnt be controlled by Synapse. Only quick effects. I checked the ausus log and everything was connecting fine on it. Uninstalled and reinstalled everything. Cleared the registry across the board. Synapse, Armoury, and Chroma Control. Same thing, only quick effects worked. Tried the previous version of Synapse I was able to find online, ver. 3.6.0130.011816 and everything started working again. Seems ver. 3.6.0415.040812 breaks the advanced effects. Funny enough I had set this all up on the 15th when the new update was released, I must have grabbed the previous version from the Razer website before the new one went live LOL Anyways doesnt seem like you can prevent Synapse from auto updating itself. If this anyone has issues with the advanced effects, I recommend rolling back to the previous Synapse version at least for now. Thanks to the dev for making chroma control possible.

**Comment by AndrewBabbitt97** [comment]
1. Don't support using any other 3rd party syncing software at the same time as Chroma Control modules. Eventually there will be an issue template having you verify things like this. I will not provide support for those situations.
2. There is a 5 led limitation with Chroma Connect, this is beyond my control. Will be documented on the FAQ page of the website.

**Comment by AndrewBabbitt97** [comment]
Latest version of Synapse should be working fine now.
