### ISSUE TITLE
Not Working / Not showing up

### ISSUE THREAD

**Issue by tisenor007** [ChromaControl/ChromaControl#49]
I had Aura Connect but that didn't work so I decided to install Chroma controller(aura addition), before I did this I uninstalled aura connect and razer synapse. When I went to install chroma controller right after I just installed synapse, it installed but all it did was freeze my lights in my computer and it didn't even show or change synapse at all. Please help me fix this issue.

**Comment by AndrewBabbitt97** [comment]
Screenshot of the Connect -> Devices tab in Synapse is needed along with your log file from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by tisenor007** [comment]
![Screenshot (264)](https://user-images.githubusercontent.com/77278112/112066252-c68b7f80-8b44-11eb-859c-b6048795ac1c.png)
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6185625/ASUS.log)


> Screenshot of the Connect -> Devices tab in Synapse is needed along with your log file from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by tisenor007** [comment]
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6185678/ASUS.log)
![Screenshot (264)](https://user-images.githubusercontent.com/77278112/112066522-40236d80-8b45-11eb-848a-9c2b035c3461.png)

I believe this is the correct things : )

**Comment by Sbm7** [comment]
Did you ever get it fixed?

**Comment by tisenor007** [comment]
No I didn't...... I would like to but... for now I just stuck with Armory crate and synapse working at the same time

**Comment by tisenor007** [comment]
Didn't receive much help with my issue, closing it off as unsolved........

**Comment by AndrewBabbitt97** [comment]
Issue lies with the Synapse install on your PC.

Log file ```C:\Program Files (x86)\Razer\ChromaBroadcast\logs\CB_ChromaControl.Asus.exe.log``` may give hints if it exists. I'm gonna try to see how I can get Razer support in on issues like this.
