### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by Theoxing** [ChromaControl/ChromaControl#51]
When i try to install it, it says that I can't install beta application. I don't know what to do if someone has ideas.

**Comment by AndrewBabbitt97** [comment]
Need a screenshot of the error + windows 10 version number.

**Comment by Theoxing** [comment]
![image](https://user-images.githubusercontent.com/15069089/112228448-98d03480-8c31-11eb-9313-920381828982.png)
Windows 10 Version 20H2

**Comment by AndrewBabbitt97** [comment]
This is a group policy block. There is a windows policy on your PC preventing installation. Is this a domain joined PC?

**Comment by Theoxing** [comment]
Oh is it because I have teams on my pc ? How do I remove it cause it tilts me af because it requires me to always change my password and shit.

**Comment by Theoxing** [comment]
ok just fixed it and installed.

**Comment by Theoxing** [comment]
ok it shows up in synapse but when i try things it just goes dark and nothing happens.

**Comment by AndrewBabbitt97** [comment]
Check #46
