### ISSUE TITLE
No installer...how to install? 

### ISSUE THREAD

**Issue by rynhere** [ChromaControl/ChromaControl#57]
I download .zip....I extract and then...??? Where's the .exe or the .msi or anything that will run.    .cs files? What do I do with those?

**Comment by AndrewBabbitt97** [comment]
.msixbundle

https://github.com/ChromaControl/ChromaControl/releases

**Comment by Stormtrail** [comment]
Andrew, not sure how you want to handle positive feedback but just wanted to say the .msi bundle for Asus worked flawlessly on a 2021 Asus G15 and Razer Basilisk Ultimate with updated Windows/Armory Crate/Synapse.

**Comment by AndrewBabbitt97** [comment]
Eventually people will be able to contribute to a list of tested devices
