### ISSUE TITLE
Very Bad

### ISSUE THREAD

**Issue by sirandr3w** [ChromaControl/ChromaControl#58]
Aura connect worked perfectly but now with this looks like a downgrade. Clean flash my Windows 10 but still not work. It is installed and synapse see the app but with Studio i can't change colors, only static colors. And when i install this chroma control, asus armoury crate does not find my ram. When i uninstall chroma control everything works again.

**Comment by muhdbs86** [comment]
Please see and read #46

**Comment by AndrewBabbitt97** [comment]
Aura connect uses the same code as this. This also doesn't do anything to armory crate that would prevent it from finding your ram.

**Comment by sirandr3w** [comment]
> Aura connect uses the same code as this. This also doesn't do anything to armory crate that would prevent it from finding your ram.

In this week i got some update of Synapse and Asus things, now it's working!!
