### ISSUE TITLE
Asus Aura not showing up on Razer Synapse

### ISSUE THREAD

**Issue by herobrine30396** [ChromaControl/ChromaControl#6]
After installing I opened Razer Synapse but it says that there is no razer compatible device connected.

**Comment by AndrewBabbitt97** [comment]
What razer devices do you have? Just FYI: this isn't a Razer support channel, I dont handle issues with Synapse here. You would have to take that over to the Razer insider forums. I only handle issues and bugs within my own code.

**Comment by HumanGamer** [comment]
Check my recent issue https://github.com/ChromaControl/ChromaControl/issues/9 for a way to fix this in the meantime, assuming you know how to compile it yourself.

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
