### ISSUE TITLE
Aura Sync effects pauses after 10 seconds when chroma control is disabled in synapse

### ISSUE THREAD

**Issue by Nayub-bit** [ChromaControl/ChromaControl#61]

**Comment by AndrewBabbitt97** [comment]
Switch in synapse doesn't do anything, outside of my control.

**Comment by Nayub-bit** [comment]
Don't worry, I found a fix. All I did was I went in task manager and disabled Chroma Control - ASUS in the startup tab. It seems to have fixed things, even though I have to open it manually every time I want everything to Synapse.
