### ISSUE TITLE
working before now its not

### ISSUE THREAD

**Issue by ta3s2** [ChromaControl/ChromaControl#62]
i got it working somehow before now is the installer disappeared. please make a lil guide on how to now. i had to reinstall windows and clear my drives so i dont have the thing from before

**Comment by AndrewBabbitt97** [comment]
It's there on the releases page: https://github.com/ChromaControl/ChromaControl/releases

Website will be going up in April with a single click button to install. I'm currently moving at the moment so my computer and accessories are all boxed up.

**Comment by ta3s2** [comment]
how do i find the other aura connect apps to delete it?
