### ISSUE TITLE
Corsair K68 RGB is completely jumbled up

### ISSUE THREAD

**Issue by xr88bliss** [ChromaControl/ChromaControl#64]
First off, thanks a lot for making this! I installed the Chroma Control Corsair app and set up my Corsair K68 keyboard and Harpoon mouse. Everything works fine until I try to use Visualizer or Chroma Studio. The effects do not appear as they should. For example, the visualizer seems to be improperly mapped and nothing makes sense. Same goes for other effects like Wave, Fire or Wheel. Here is the log, just in case...
[Corsair.log](https://github.com/ChromaControl/ChromaControl/files/6231568/Corsair.log)

**Comment by AndrewBabbitt97** [comment]
This is a limitation of the Chroma Connect module in Synapse, so there is nothing I can do. Static/Color cycle effects work best.
