### ISSUE TITLE
Doesn't appear to be working with Asus ROG Strix x570e gaming

### ISSUE THREAD

**Issue by sharkannon** [ChromaControl/ChromaControl#67]
I had a Asus Tuf b550 gaming that I'd setup, but I had a bad Channel so had to send it in for RMA.  ChromaControl worked just fine on it.  I then got a ASUS Rog Strix x570e Gaming, it was actually much more stable than my Tuf, but I can't seem to get Chroma Connect to work on it.

Hardware:
Hunstman Elite Keyboard
Razer Naga Trinity
Asus x570e Gaming with some RGP LED fans
2x Gskill Trident NEO DDR

Software:
Windows 10 Pro, 20H2 Build 19042.906
Razer Synapse 3.6.331.31613
Armory Crate: 4.0.8
HAL Central: 20210105 (Latest)

I can control the lights on the case/motherboard through Aura sync, and I can control the Keyboard/Mouse through Synapsis no problem.  I have the ChromaControl installed, and it shows up and is configurable in Synapsis, but the lights just don't change to match (They stick with whatever was originally set in Aura Sync).

I've uninstalled and reinstall ChromaControl to no avail. 
NOTE: This is a fresh windows install, as I rebuilt it just a day or 2 ago.

**Comment by KyleStilkey** [comment]
I'm guessing you use to have AuraConnect installed? If so make sure it's 100% removed as even trying to uninstall may not remove all of it causing issues. Just check through your ASUS folders under Programs and Programs (x86) and making sure all the files/folders for AuraConnect are deleted and restart.

Also for me on a few of my setups I had to run the program after the first setup to get it to actually run. It's been good so far since.

I would also make sure you have all updates installed under the Settings of Armory Crate as they have recently pushed of many patches of the past week.

**Comment by thisismejosh** [comment]
I also cannot get this to function at all. Unfortunately I am a github noob, and have no idea what to press to make this work. I am frustrated. I installed git and github, and still see no way to install. I don't see the file type the maker of the repository alludes to.

**Comment by sharkannon** [comment]
> I'm guessing you use to have AuraConnect installed? If so make sure it's 100% removed as even trying to uninstall may not remove all of it causing issues. Just check through your ASUS folders under Programs and Programs (x86) and making sure all the files/folders for AuraConnect are deleted and restart.

I had AuraConnect installed on the B550, uninstalled it and installed ChromaConnect, no problems.
Fresh windows install of the x570 and only install ChromaConnect, everything shows up correctly (and is configurable), but the lights just won't sync (They use the Aura defaults). 


> Also make sure your bios are up to date as later bios also get pushed with firmware updates to Aura.
Way ahead of you on that 


> Also for me on a few of my setups I had to run the program after the first setup to get it to actually run. It's been good so far since.
* Everything shows up fine, it's available in the Razer Synapsys to configure, it's just not syncing.
 
> I would also make sure you have all updates installed under the Settings of Armory Crate as they have recently pushed of many patches of the past week.
* Way ahead of. you on that (Hense why I listed the software).

**Comment by sharkannon** [comment]
Found the issue, probably want to update the DOCS to be clear.

you MUST have "in game lighting effects" enabled for Aura, if you don't, then this won't work.

**Comment by AndrewBabbitt97** [comment]
Will be on the website once it comes up this month.

**Comment by sharkannon** [comment]
Cool, thx

**Comment by sharkannon** [comment]
Ok, I reboot and now it's "Unreachable", though that appears to be something others are seeing too.
