### ISSUE TITLE
Document Dependencies & Versions For Chroma Control

### ISSUE THREAD

**Issue by Zifuta** [ChromaControl/ChromaControl#69]
I cannot controll RGB on my asus motherboard through synapse 3.

**Comment by rubilacxe95** [comment]
Same here. Razer Synapse just updated to Version 3.6.331.316.13 and now aura is unreachable again. im so fucking angry it updated by itself since everything was nice until the last update. can anyone provide the previous update so i can control my lightning stuff again? THX.

**Comment by ElguishexD** [comment]
Same problem here...

**Comment by ElguishexD** [comment]
https://dw60.uptodown.com/dwn/zYxACMZupFtAKsH_50mqRKZpdLJLAySmn9XdbzgjGdlCGE-eqv0O5w7ANb-JndfETajqVGtF0DG1QCz3hkI6Uoj1rsFXUHXa7XDavFoH12RsMuctZRFt0tnR-Ph1cp6X/GZcj901H81g3Mv2Uii-kulBMdTSkVNzuwczfMdVv3uQvMw3bCOp-H1BURVfx2aNl2IAffmCSrIw3JwaDkYb0O2yCaYmE6g1BTU17gjBit9L6VBGkvxyZJkf33SZu231P/VUui19VjUTw6Of1a6mvgdGGUmeUVIlaqeL50hy81gkIJCB2YVV19qu7HdH4cJH9oKsf1ezNQC3bo5mLEZ6UbfcBe7t9pSthHfualAJKHMrA=/razer-synapse-3-5-1215-121019.exe

**Comment by ElguishexD** [comment]
> https://dw60.uptodown.com/dwn/zYxACMZupFtAKsH_50mqRKZpdLJLAySmn9XdbzgjGdlCGE-eqv0O5w7ANb-JndfETajqVGtF0DG1QCz3hkI6Uoj1rsFXUHXa7XDavFoH12RsMuctZRFt0tnR-Ph1cp6X/GZcj901H81g3Mv2Uii-kulBMdTSkVNzuwczfMdVv3uQvMw3bCOp-H1BURVfx2aNl2IAffmCSrIw3JwaDkYb0O2yCaYmE6g1BTU17gjBit9L6VBGkvxyZJkf33SZu231P/VUui19VjUTw6Of1a6mvgdGGUmeUVIlaqeL50hy81gkIJCB2YVV19qu7HdH4cJH9oKsf1ezNQC3bo5mLEZ6UbfcBe7t9pSthHfualAJKHMrA=/razer-synapse-3-5-1215-121019.exe

A previous version of synapse.... woking just fine

**Comment by ElguishexD** [comment]
![WhatsApp Image 2021-04-12 at 12 08 31](https://user-images.githubusercontent.com/81433453/114426315-f1875300-9b87-11eb-9e96-b20079d35b2b.jpeg)

**Comment by AndrewBabbitt97** [comment]
Need logs from %localappdata%\Local\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by ElguishexD** [comment]
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6298993/ASUS.log)

**Comment by ElguishexD** [comment]
Don't sure if you asking me

**Comment by AndrewBabbitt97** [comment]
@ElguishexD If the lights aren't changing on your devices, the issue lies in Armory Crate/Aura itself. Chroma Control is fully working as expected. Based on your image, Synapse is working as well.

I have seen Aura not update LEDs.

1. Update BIOS to latest stable version (check ASUS support page)
2. Armory Crate -> Settings -> Update Center; go update everything on that page
3. Armory Crate -> Aura Sync -> In-Game lighting effects; turn this on

Report back after all of this

**Comment by ElguishexD** [comment]
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6299747/ASUS.log)

I have done everything you said

**Comment by AndrewBabbitt97** [comment]
Verify Armory Crate & Synapse are up to date. This was around a time where several bugs were found in Synapse.

**Comment by juancarrilloberdejo** [comment]
> > https://dw60.uptodown.com/dwn/zYxACMZupFtAKsH_50mqRKZpdLJLAySmn9XdbzgjGdlCGE-eqv0O5w7ANb-JndfETajqVGtF0DG1QCz3hkI6Uoj1rsFXUHXa7XDavFoH12RsMuctZRFt0tnR-Ph1cp6X/GZcj901H81g3Mv2Uii-kulBMdTSkVNzuwczfMdVv3uQvMw3bCOp-H1BURVfx2aNl2IAffmCSrIw3JwaDkYb0O2yCaYmE6g1BTU17gjBit9L6VBGkvxyZJkf33SZu231P/VUui19VjUTw6Of1a6mvgdGGUmeUVIlaqeL50hy81gkIJCB2YVV19qu7HdH4cJH9oKsf1ezNQC3bo5mLEZ6UbfcBe7t9pSthHfualAJKHMrA=/razer-synapse-3-5-1215-121019.exe
> 
> Una versión anterior de synapse ... woking muy bien

Excelente, muchas gracias por el aporte.

**Comment by AndrewBabbitt97** [comment]
Just FYI: I don't support anyone who isn't using a current version of Synapse. I do all testing against the latest version only.

**Comment by AndrewBabbitt97** [comment]
Closing, as this is no longer relevant with OpenRGB.
