### ISSUE TITLE
ASUS unreachable

### ISSUE THREAD

**Issue by ta3s2** [ChromaControl/ChromaControl#7]
just installed couple days later it stop working ay says asus unreachable in razer app

**Comment by ta3s2** [comment]
![asus](https://user-images.githubusercontent.com/73453240/97128443-98bb1f80-16f9-11eb-8bc5-4aabe40454d4.png)

**Comment by AndrewBabbitt97** [comment]
Looks like data was sent then this happened, something on your system interrupted the connection to AuraComnect.

**Comment by ta3s2** [comment]
I would have to shut down my pc for at least until the light turns off then start it and it’s fine

**Comment by AndrewBabbitt97** [comment]
Unreachable with the dots lit up means that it had successfully connected but something interrupted the connection. Need logs from C:\ProgramData\AuraConnect\logs to be able to confirm this. If confirmed, you would have to figure out what on your PC is causing this. Nothing I can do to change this.

**Comment by AndrewBabbitt97** [comment]
This issue looks related to AuraConnect and not ChromaControl. Closing this issue.

Please use the ChromaControl MSIX beta.
