### ISSUE TITLE
Corsair RAM stays on after PC goes to sleep

### ISSUE THREAD

**Issue by Tomerkat** [ChromaControl/ChromaControl#70]
Hi, I have a Corsair Vengeance RGB Pro and I connected it to Razer Synapse using ChromaControl.
When my PC goes to sleep, every RGB component turns off, but the RAM's lightning stays on. How can I fix that?

**Comment by AndrewBabbitt97** [comment]
Related to #37 

Although its been a while since I have used Corsair ram, If I recall correctly this is just a general Corsair ram issue even without Chroma Control.

**Comment by Tomerkat** [comment]
Fixed it. I changed the "Hardware Lightning" in iCue to no color.
