### ISSUE TITLE
Synapse taking over

### ISSUE THREAD

**Issue by WyRmiE** [ChromaControl/ChromaControl#71]
Hello 

Please i have selected it like this in Armory crate i want only MB and Memory to go by Synapse, when i unselect it its working, but each time PC reboots it will take over all 3 components and i have to open Armory select and deselect ARGB option.

Is this something we can do about or its not possible.

Thanks for great work

![image](https://user-images.githubusercontent.com/78855379/114318272-aed46500-9b0c-11eb-8dda-28bbd033b750.png)

**Comment by AndrewBabbitt97** [comment]
Nothing I can do about this. This is all on the Aura side.

Will eventually be able to select devices that will be controlled in ChromaControl. This will only effect which devices we send updates to, ChromaControl will still get exclusive access to the device.
