### ISSUE TITLE
can i customize my asus rog strix fully with razer?

### ISSUE THREAD

**Issue by Eugioo2004** [ChromaControl/ChromaControl#73]
is it possible to fully customize my asus rog strix with razer synapse? i realy want to customize the full keyboard and the lightbar under the laptop with razer synapse. is there a way to do this?

**Comment by AndrewBabbitt97** [comment]
There's an asus module: https://github.com/ChromaControl/ChromaControl/releases

**Comment by Eugioo2004** [comment]
yes i download that one

**Comment by Eugioo2004** [comment]
but it only places a asusconnect thing that changes the color of the whole laptop. not every single item

**Comment by Eugioo2004** [comment]
is that posible that i program my laptop by key in synapse?

**Comment by AndrewBabbitt97** [comment]
Yes, that's the best this can do. Its not possible to support individual LED control for 3rd party devices in Synapse. I have requested it from the Razer dev's. If/when it ever comes out I will add support for it.
