### ISSUE TITLE
app is running but nothing is appearing in synapse 

### ISSUE THREAD

**Issue by missilepack** [ChromaControl/ChromaControl#74]
I installed the beta version and saw that it was running on task manager but when I open synapse only my MSI graphics card is appearing. I have armoury crate installed btw. Is there something I'm missing? I'm new to this.

**Comment by missilepack** [comment]
i got it working nevermind

**Comment by Sbm7** [comment]
How did you get it working?

**Comment by Sbm7** [comment]
h

**Comment by Sbm7** [comment]
> i got it working nevermind

How? I am having the same issue.
