### ISSUE TITLE
Nothing showing in Synapse

### ISSUE THREAD

**Issue by TheJawa05** [ChromaControl/ChromaControl#8]
Just built a new PC with Asus Sync stuff and wanted it to sync with my Synapse stuff.  Installed your app, checked Synapse, and I don't see anything on there at all about Asus Sync

I have Synapse 3 and Armoury Crate.

**Comment by FearNaBoinne** [comment]
Same here... Nothing showing up in Synapse. I have AuraConnect, but as you indicated this was a reorganized rewrite with Aura and iCue support, I wanted to give it a try...

Given that this was last updated 12 months ago, and AuraConnect more recently than that, is this abandoned?

**Comment by AndrewBabbitt97** [comment]
There's an update coming, but I have been waiting for certain things to go through for me to publish an update that have been delayed due to COVID-19.

**Comment by FearNaBoinne** [comment]
Thanks for the update... I'll try it again then after it's updated...

**Comment by ticklemedaly** [comment]
I'll be watching closely - didn't realize that syncing my Corsair keyboard with my Synapse 3 is possible until I stumbled upon this.

Thanks @AndrewBabbitt97 for what you can do for everyone!!!

**Comment by HumanGamer** [comment]
Check my recent issue https://github.com/ChromaControl/ChromaControl/issues/9 for a way to fix this in the meantime, assuming you know how to compile it yourself.

**Comment by AndrewBabbitt97** [comment]
Beta version out: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
