### ISSUE TITLE
toggling it on and off

### ISSUE THREAD

**Issue by hackthis02** [ChromaControl/ChromaControl#83]
I only like to have it running while I'm playing a game that supports Razer Chroma. Is there a way to toggle the new MSIX build on and off via batch file or cmd?

**Comment by kats1123** [comment]
I second this. I prefer the rainbow effects in Armoury Create, so in the off chance I'm showing off my PC it just freezes even when disabled in synapse. I'm assuming this is because it's still active, synapse just isn't using it. the ability to just freeze the process would be great.

**Comment by AndrewBabbitt97** [comment]
You can always kill the process from the task manager and restart it from the start menu.

If you want to disable it at startup you can do so by disabling it at startup from the task manager startup tab.

UI will be added in the future that adds buttons for this as well.

**Comment by hackthis02** [comment]
That's nice. But what I was asking is if there is/will be a way to toggle it on and off via a batch file or cmd command. Like we could do when it was a service. Having to open task mgr to kill the process every time I close a game add isn't a really good option.

**Comment by AndrewBabbitt97** [comment]
Kill:
```TASKKILL /F /IM ChromaControl.Asus.exe```

Start:
```START ChromaControl.Asus.exe```

Note: Starting assumes that the executable is in your PATH environment variable, this may or may not be done automatically by windows. I'm not at my PC to check.

It's a standard executable,  so it's started and stopped like any other exe from the command line.

**Comment by kats1123** [comment]
Solved for me too! Thank you! I ended up using your in + pssuspend!

**Comment by hugopua** [comment]
Can i know what's the dos command for running chromacontrol.asus.exe in batch file? i got this error.

C:\Users\User>START "C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe"
Access is denied.
