### ISSUE TITLE
AURA not syncing with Razer Chroma

### ISSUE THREAD

**Issue by danieIchung** [ChromaControl/ChromaControl#84]
I've been using AURAConnect for quite some time now, and I recently found that it was archived and unsupported after experiencing some issues with syncing. After uninstalling AURAConnect and installing ChromaControl, the problems still remained the same: AURA was not syncing with Chroma, despite it showing up as a controllable device.

I did a bit of reading into the forums in hopes of finding a solution, but it seems that it is generally individualized.
My current setup in regards to what is connected to AURA includes:

- ROG STRIX B450-F Gaming Motherboard
- ROG STRIX GeForce RTX 2070 Super
- G.SKILL TridentZ RGB DDR4-3200 (2 x 8 GB)

Here are the logs:
- Chroma Control
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6412839/ASUS.log)

- Chroma Broadcast 
[CB_ChromaControl.Asus.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412840/CB_ChromaControl.Asus.exe.log)
[CB_RazerSynapseService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412841/CB_RazerSynapseService.exe.log)
[CB_RzSDKService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412842/CB_RzSDKService.exe.log)
[CB_wallpaper32.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412843/CB_wallpaper32.exe.log)
[CB_WraithPrism.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412844/CB_WraithPrism.exe.log)
[CB_WraithPrismHID.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412845/CB_WraithPrismHID.exe.log)
[CB_AuraConnect.exe.log](https://github.com/ChromaControl/ChromaControl/files/6412846/CB_AuraConnect.exe.log)

I should also mention that I'm also using a software that controls my CPU fan (Wraith Prism) that syncs directly to Synapse without issues. 

Finally, here is a screenshot of my Armoury Crate Update Center
![armoury crate](https://user-images.githubusercontent.com/81717550/116841293-bedce300-aba6-11eb-8c2e-5f2f05a40772.png)

Any form of help would be greatly appreciated.

**Comment by sordnotsword** [comment]
I have a similar issue.  I uninstalled chromaconnect and installed chromacontroll and it didn't work. I even uninstalled armuory crate, razer synapse, chroma control, and reinstalled them and it still doesn't work. I

**Comment by AndrewBabbitt97** [comment]
Issue OP is having is related to AURA SDK not always working. Ensure your BIOS are fully up to date. This is one of those issues that I'm unable to determine exactly why happens and the issue lies inside of AURA.

**Comment by danieIchung** [comment]
Just updated my BIOS and the problem still persists. Interestingly enough, my motherboard LED doesn't sync until I manually open Armoury Crate and switch over to the AURA effects tab. However, my RAM and GPU LED's sync just fine on startup without interference.

Should I go about contacting ASUS for support?

**Comment by AndrewBabbitt97** [comment]
Reaching out to ASUS is probably the best we can do. I have seen this issue many times, but never myself. Due to this I am unable to diagnose the issue. It is however on the ASUS/AURA side.
