### ISSUE TITLE
Don't show on razer synaspse 

### ISSUE THREAD

**Issue by boumantho** [ChromaControl/ChromaControl#85]
Hello , i installer the package and  it Don't show on razer synpasse before and after a restart 
[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6450006/ASUS.log)

**Comment by AndrewBabbitt97** [comment]
It can't initialize the AURA SDK, something wrong with your AURA install. I have no clue what it is, it's random and something I can't track down easily. TLDR; Aura SDK is super buggy

**Comment by AndrewBabbitt97** [comment]
Closing do to inactivity. Feel free to reopen if needed.
