### ISSUE TITLE
Adding NZXT Cam & Coolermaster

### ISSUE THREAD

**Issue by doomskunk** [ChromaControl/ChromaControl#87]
I love this! But was wondering will it be possible to add NZXT Cam (and Coolermaster) to the list of devices?

Keep up the amazing work!!!

**Comment by AndrewBabbitt97** [comment]
Cooler master already requested by someone else, NZXT will likely only be Kraken devices if even that.

**Comment by AndrewBabbitt97** [comment]
Closing in favor of #94

**Comment by kitoep** [comment]
Hello, I dont see the chroma control device for NZXT Cam, so NZXT CAM doesnt sync, in what version do you have support for it?
