### ISSUE TITLE
IDEA: Individual Device Control

### ISSUE THREAD

**Issue by Paladinleeds** [ChromaControl/ChromaControl#89]
So, the idea I've had, if the SDKs will permit it, is for Corsair and Asus devices (such as motherboard, GPU, individual RAM sticks, etc) to all show in Chroma Studio as separate devices. With this, it'll enable users to position their devices exact as they appear in their setup, and help create more fluid integrations. Similar to how each individual Hue bulb shows separately in Synapse.

**Comment by AndrewBabbitt97** [comment]
Limitation is in the Chroma Connect SDK, doesn't support multiple devices in Synapse.

**Comment by kats1123** [comment]
What if it would create a separate process for each of the items you would want. So like each ram stick a seperate service 1 for the actual rgb on the motherboard etc…?

**Comment by AndrewBabbitt97** [comment]
SDKs typically only accept one process taking control of devices at a time, so would need to be a single process. Synapse also has a limitation of one manufacture per process/executable on the disk.

If I had a way to go this effectively right now I would have already.

I have asked Chroma devs about this, nothing to announce on this right now.

**Comment by AndrewBabbitt97** [comment]
Closing this issue, I will create an issue to track this once Razer has implemented a better solution.
