### ISSUE TITLE
The reason this tool doesn't work is because the GUID is invalid.

### ISSUE THREAD

**Issue by HumanGamer** [ChromaControl/ChromaControl#9]
The reason this does not work is because an Invalid/Unsupported GUID is passed to the Razer Broadcast Library.

As far as I can tell, you have to ask razer for a supported GUID for the broadcast API.

The only thing I had to do to get the iCue support working was to set the GUID to ``removed`` which is the ID for ``Chroma Control - Corsair``

That is the only supported ID for Corsair at the moment.

The fix should be the same for Aura but I currently do not have any Aura devices.
The GUID used in AuraConnect is ``removed`` which is the ID for ``ASUS`` and should work for the Aura plugin of ChromaControl, but I am not able to test it.

If you're wondering how I got that ID, I ran this app through a native debugger and managed to dump the decrypted contents of the broadcast.dat (which is actually just a JSON file) from memory. That file contains all the supported IDs for the Broadcast API.

I assume normally you just wouldn't want to just hijack an id, and rather get your own. Though I have no idea where you would go to request this, but at least this works for me in the meantime.

**Comment by AndrewBabbitt97** [comment]
Please don't post GUIDs in the public, devs can reach out to Razer to request GUIDs. They are not to be shared in the open, even if you can obtain them through decompiling release binaries.

I am aware of this issue, waiting on certificates right now to sign binaries/releases holding up a newer release. COVID-19 has made this aspect a pain.

**Comment by HumanGamer** [comment]
> Please don't post GUIDs in the public, devs can reach out to Razer to request GUIDs. They are not to be shared in the open, even if you can obtain them through decompiling release binaries.
> 
> I am aware of this issue, waiting on certificates right now to sign binaries/releases holding up a newer release. COVID-19 has made this aspect a pain.

Oh I apologize. I assumed since you had included a GUID in AuraConnect it was fine...

How do you go about contacting Razer about this if you don't mind me asking?

**Comment by RobertjanTuit** [comment]
Any updates on the updated build with new valid certificas/guids?

**Comment by AndrewBabbitt97** [comment]
Good potential for a beta tonight

Some notes:

- I got my code signing certificate last night
- Updated [CUESDK.NET](https://github.com/RGBKit/CUESDK.NET) the other day to bring it up to Corsairs latest version
- Made some improvements to [RGBKit](https://github.com/RGBKit/RGBKit) over the past few days, I still think I may be able to get startup times reduced but I will be doing that In a later update now that I have things at least working decently for the time being
- Updated [RzChromaBroadcastAPI.NET] the other day with PRs from @HumanGamer (THANK YOU!)
- Project will now use [MSIX](https://docs.microsoft.com/en-us/windows/msix/overview) for packaging/distribution. This package is signed with my code signing certificate and will have the ability to perform auto updates
- App no longer runs as a system service, it uses [StartupTask](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.startuptask?view=winrt-19041) to create an entry for startup when a user logs in now

I want to add a UI to get logs and enable various debugging features, I will probably have something basic in the beta release. I also need to implement a basic deployment pipeline, the beta will probably be a manual release and Ill sort out the rest before stable.

Much of my free time the past few days has been spent debugging small little issues that have cropped up with the move to MSIX, but I am feeling pretty good about everything now though I do expect more issues to crop up over the beta period.

**Comment by MarshallYTHD** [comment]
If you do open it for beta today I will definitely download it.

**Comment by AndrewBabbitt97** [comment]
Beta released: https://github.com/ChromaControl/ChromaControl/releases/tag/msix-beta

**Comment by AndrewBabbitt97** [comment]
Closing due to new MSIX beta. Issue should now be resolved.
