### ISSUE TITLE
I can't identify the .exe-file

### ISSUE THREAD

**Issue by Princent95** [ChromaControl/ChromaControl#91]
Hey guys, i downloaded ChromaControl and Aura Connect and can't find in both the file where i can run a programm XD
I'm feeling like abot whereelse other people can't deinstall the programm XD

**Comment by AndrewBabbitt97** [comment]
#33 #55 #72

**Comment by Princent95** [comment]
Thank u! I have another question. I’m writing right know with the Razer 2 Level Support, because my Razer Tomahawk isn‘t working with the ROG Strix B450-E. Then I found a YouTube-Video, where a guy had the same issue like me. And I’m not sure, if only Aura connect (which I really can’t find anywhere to download, Chroma is already installed) helps. The biggest problem is, that Synapse isn‘t recognising or showing my Tomahawk. Any idea?

**Comment by AndrewBabbitt97** [comment]
Aura Connect is deprecated and archived, no longer supported. Chroma Control is the continuation of it (think of it as a name change).

If it's purely that Synapse doesn't recognize the Tomahawk I can't say. I personally use an O11 Dynamic Razer Edition. Unless it's an issue that only shows when using Chroma Control, it's outside of the scope of my project.
