### ISSUE TITLE
Cannot install asus version

### ISSUE THREAD

**Issue by mdotm25** [ChromaControl/ChromaControl#92]
App installation failed with error message: Deployment Add operation with target volume C: on Package ChromaControl.Asus_1.0.0.0_neutral_~_846pf09jn2fpg from:  (ChromaControl.Asus.Package_1.0.0.0_x86_x64%20(3).msixbundle)  failed with error 0x8007000D. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x8007000d)

**Comment by AndrewBabbitt97** [comment]
That error code isn't in Microsoft's list, this is a Windows/MSIX issue.

This could be many things, all of which are on your end:

- Issue with your Windows 10 install
- Bad Windows 10 update
- Corrupt download of the MSIX
- Modified MSIX (You cannot modify the MSIX in any way without resigning it, signature check will fail)

There is a note in the article link:
![winsupport](https://user-images.githubusercontent.com/2308261/121609959-37d72200-ca12-11eb-8883-1aa3d6f9b410.png)

Essentially for issues such as this, its not a ChromaControl issue. Its an issue with Windows itself and so you must reach out to Microsoft support for help on it.
