### ISSUE TITLE
New Hardware Providers

### ISSUE THREAD

**Issue by AndrewBabbitt97** [ChromaControl/ChromaControl#94]
Community is requesting new hardware providers, this issue will be to track progress on adding new ones.

- [x] NZXT
- [x] Cooler Master
- [x] Gigabyte
- [x] EVGA
- [x] Logitech
- [x] Roccat
- [x] Sound Blaster
- [x] PNY

**Comment by ItsLewisTV** [comment]
really looking forwardd to seeing this project grow, I have very recently bought a g502 lightspeed and am missing how good razers rgb controls are!

**Comment by felipecrs** [comment]
Can you please add MSI to the list? Their software is crap!

**Comment by AndrewBabbitt97** [comment]
@felipecrs Seeing as you would still have to have MSIs software installed to use it, there's no point. We use the same API that MSI uses for Synapse integration.

There is no benefit to me making a Chroma Control module for MSI. More than likely the performance would be worse than just using the already provided integration due to having to pass through more processes and code bases.

**Comment by felipecrs** [comment]
Well... I was never able to make Mystic Light work with Razer Connect.

**Comment by AndrewBabbitt97** [comment]
If there's an issue with the MSI software not working that's something you will have to take up with MSI and Razer support. For now, seeing as MSI supports the API already I wont be spending dev time on it in the foreseeable future. Not only that but It will be unlikely for me to get a GUID to support MSI when MSI is already partnered with Razer.

I have seen plenty of people using MSI just fine with Synapse. Priority is on RGB ecosystems that don't have support already in Synaspse.

**Comment by felipecrs** [comment]
That's right. Makes total sense.

**Comment by Zilveron** [comment]
Wondering if you can add Zotac graphics cards to the list.  Their software is NFG.  
Just installed for my Asus motherboard and seems to work great so far.  Many thanks for solving a headache!

**Comment by AndrewBabbitt97** [comment]
> Wondering if you can add Zotac graphics cards to the list. Their software is NFG.
> Just installed for my Asus motherboard and seems to work great so far. Many thanks for solving a headache!

As far as I can tell, Zotac doesn't have an RGB SDK that would allow for me to make a Chroma Control module.

**Comment by Zilveron** [comment]
> As far as I can tell, Zotac doesn't have an RGB SDK that would allow for me to make a Chroma Control module.
Well, that figures.  But thanks anyway.  I appreciate it.

**Comment by amk0** [comment]
Gigabyte would be awesome. They have the absolute worst software I've ever used. If I could skip the whole damn thing and just hook it up to Razer it would make my life so much easier.

**Comment by bitdope** [comment]
Gigabyte support would be nice.

**Comment by C3S4RM3W** [comment]
Hey, could you add support for OpenRGB? Has a built-in server and supports a lot of devices even Gigabyte, so having that as a toggle to sync all the supported devices from OpenRGB and control that from Razer synapse for ease of use would be awesome.

**Comment by susyabashti** [comment]
NZXT would be lit!!

**Comment by R1d3rBG** [comment]
Works amazing with Corsair, would be  great if I can enable it as well with RGB Fusion from Gigabyte :)

**Comment by five710** [comment]
Love your chroma control app but would love to see EVGA Precision X1 support added

**Comment by billyjbryant** [comment]
Any word on progress updates for any of these, such as Logitech and OpenRGB?

**Comment by AndrewBabbitt97** [comment]
Logitec is being handled in #200 
OpenRGB is in #209 

We have no estimate on when these will get merged, as they are:

1. Dependent on the in progress code rework
2. Not developed by me, as such it will depend on when the contributors have the time to merge upstream changes and get it working with the new device driver model.

**Comment by lingqi-su** [comment]
Any update on NZXT integration?

**Comment by AndrewBabbitt97** [comment]
@lingqi-su no one is currently working on NZXT support, and I do not have any hardware to support it myself.

**Comment by sturze** [comment]
i have a Gigabyte MB(designare z390) would absolutely love to see this work!

**Comment by esh-ka** [comment]
Hello @AndrewBabbitt97 !
Is there any progress on aorus integration?

**Comment by AndrewBabbitt97** [comment]
@esh-ka No one who has hardware has proposed to maintain a driver for it.

Until someone with hardware writes the code or someone donates hardware it won't be happening.

This is more of a call to action list.

**Comment by AndrewBabbitt97** [comment]
I would like to announce, Gigabye RGB Fusion support is coming. I am formally moving away from ASUS motherboards as they cause me a ton of problems now days. There are too many issues with ASUS hardware and software that I can no longer recommend them as a hardware vendor.

We will continue to support ASUS as a Chroma Control module, but I personally will no longer be able to test / make meaningful changes to the ASUS code. (It has been stable on our side for years anyways, so it will likely remain that way for a long time to come).

**Comment by AndrewBabbitt97** [comment]
Going forward we are entirely focused on OpenRGB support, which has support devices from all of the manufacturers in the OP.

Specific device support can be found here: https://openrgb.org/devices.html
