### ISSUE TITLE
led ordered incorrectly

### ISSUE THREAD

**Issue by TheHacker24680** [ChromaControl/ChromaControl#97]
so i have a corsair k55 and the colors sent to its 3 lighting zones are not ordered correctly as if there is a pattern going from left to right it would go to middle then left then right so is there a way to fix it ?

**Comment by TheHacker24680** [comment]
it worked correctly for some time but now it is messed up

**Comment by AndrewBabbitt97** [comment]
This is the same issue as #93 more details there even if the example applies to ram, it also applies to keyboards.

FYI: Keyboards are always going to be a terrible experience with ChromaControl until the Chroma Connect SDK gets improvements.
