### ISSUE TITLE
Do i need Icue to use Chromaconnectcorsair?

### ISSUE THREAD

**Issue by hugopua** [ChromaControl/ChromaControl#99]
Hi,

As the title mentioned, do i need the Icue installed? Thank you.

**Comment by AndrewBabbitt97** [comment]
Yes

**Comment by hugopua** [comment]
Hi. 

Thank you for your reply. My setup is Asus Crosshair Viii dark hero with Corsair Dominator Platinum x 4. 

I follow below link for setup and I installed chromaconnect for Asus. (Not for Corsair)
https://help.corsair.com/hc/en-us/articles/360035656371-Enable-Aura-Sync-control-for-your-Corsair-RGB-memory

The problem is when I enable memory RGB sync from Armoury crate. The memory rgb will crash but if I disable the memory rgb sync on Armoury crate and the memory rgb is not control by icue (this suppose control by icue since I disable the rgb sync from Armoury crate) but the memory rgb control by razer synapse.

**Comment by AndrewBabbitt97** [comment]
Are you only using Corsair RAM?

**Comment by hugopua** [comment]
Yes
